"""PC0 architecture-boundary acceptance fixtures (pytest and unittest compatible)."""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from copy import deepcopy
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from core.platform.architecture_contract import (
    PC0ArchitectureError,
    _source_sha256,
    _validate_composition,
    _validate_finance,
    evaluate_source_text,
    validate_pc0,
)


class PC0KernelBoundaryTests(unittest.TestCase):
    @staticmethod
    def _composition() -> dict:
        return json.loads((ROOT / "contracts/platform/v1/pc0_composition_baseline.json").read_text(encoding="utf-8"))

    @staticmethod
    def _finance_contracts() -> tuple[dict, dict, tuple[str, ...]]:
        directory = ROOT / "contracts/platform/v1"
        baseline = json.loads((directory / "pc0_frozen_finance_baseline.json").read_text(encoding="utf-8"))
        inventory = json.loads((directory / "pc0_frozen_finance_inventory.json").read_text(encoding="utf-8"))
        pc1 = json.loads((directory / "pc1_structural_authority.json").read_text(encoding="utf-8"))
        pc2 = json.loads((directory / "pc2_party_authority.json").read_text(encoding="utf-8"))
        pc3 = json.loads((directory / "pc3_semantic_authority.json").read_text(encoding="utf-8"))
        pc4 = json.loads((directory / "pc4_operating_context_authority.json").read_text(encoding="utf-8"))
        pc5 = json.loads((directory / "pc5_identity_policy_audit_authority.json").read_text(encoding="utf-8"))
        return baseline, inventory, (pc1["accepted_head"], pc2["accepted_head"], pc3["accepted_head"], pc4["accepted_head"], pc5["accepted_head"])

    @classmethod
    def _copy_frozen_finance(cls, destination: Path) -> tuple[dict, dict, tuple[str, ...]]:
        baseline, inventory, accepted_heads = cls._finance_contracts()
        for tree in inventory["trees"]:
            for relative in tree["files"]:
                source = ROOT / tree["root"] / relative
                target = destination / tree["root"] / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)
        for item in inventory["authorized_non_finance_extensions"]:
            source = ROOT / item["root"] / item["path"]
            target = destination / item["root"] / item["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
        return baseline, inventory, accepted_heads

    def test_complete_repository_contract_passes(self) -> None:
        report = validate_pc0(ROOT)
        self.assertEqual("PASS", report["status"])
        self.assertEqual("m64_reconciliation_controls_020", report["canonical_migration_head"])

    def test_every_frozen_composition_fingerprint_matches_canonical_source(self) -> None:
        composition = self._composition()
        self.assertEqual("sha256_git_canonical_lf", composition["fingerprint_mode"])
        actual = {relative: _source_sha256(ROOT / relative) for relative in composition["files"]}
        self.assertEqual(composition["files"], actual)

    def test_real_composition_source_change_fails(self) -> None:
        composition = self._composition()
        with tempfile.TemporaryDirectory() as directory:
            candidate_root = Path(directory)
            for relative in composition["files"]:
                destination = candidate_root / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(ROOT / relative, destination)
            database = candidate_root / "database.py"
            database.write_bytes(database.read_bytes() + b"\n# real mutation\n")
            with self.assertRaisesRegex(PC0ArchitectureError, "PC0-COMPOSITION-CHANGED: database.py"):
                _validate_composition(candidate_root, composition)

    def test_stale_composition_baseline_fails_deterministically(self) -> None:
        stale = deepcopy(self._composition())
        stale["files"]["database.py"] = "0" * 64
        with self.assertRaisesRegex(PC0ArchitectureError, "PC0-COMPOSITION-CHANGED: database.py"):
                _validate_composition(ROOT, stale)

    def test_frozen_finance_explicit_inventory_passes(self) -> None:
        baseline, inventory, accepted_head = self._finance_contracts()
        _validate_finance(ROOT, baseline, inventory, accepted_head)

    def test_finance_runtime_cache_artifacts_do_not_change_fingerprint(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            candidate_root = Path(directory)
            baseline, inventory, accepted_head = self._copy_frozen_finance(candidate_root)
            cache = candidate_root / "core/domain/finance/__pycache__/posting_engine.cpython-313.pyc"
            cache.parent.mkdir(parents=True)
            cache.write_bytes(b"generated bytecode")
            pytest_cache = candidate_root / "contracts/finance/.pytest_cache/v/cache/nodeids"
            pytest_cache.parent.mkdir(parents=True)
            pytest_cache.write_text("[]", encoding="utf-8")
            _validate_finance(candidate_root, baseline, inventory, accepted_head)

    def test_changed_protected_finance_source_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            candidate_root = Path(directory)
            baseline, inventory, accepted_head = self._copy_frozen_finance(candidate_root)
            source = candidate_root / "core/domain/finance/posting_engine.py"
            source.write_bytes(source.read_bytes() + b"\n# mutation\n")
            with self.assertRaisesRegex(PC0ArchitectureError, "PC0-FROZEN-FINANCE-CHANGED"):
                _validate_finance(candidate_root, baseline, inventory, accepted_head)

    def test_added_protected_finance_source_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            candidate_root = Path(directory)
            baseline, inventory, accepted_head = self._copy_frozen_finance(candidate_root)
            added = candidate_root / "core/domain/finance/unexpected_authority.py"
            added.write_text("# unexpected source\n", encoding="utf-8")
            with self.assertRaisesRegex(PC0ArchitectureError, "PC0-FROZEN-FINANCE-INVENTORY"):
                _validate_finance(candidate_root, baseline, inventory, accepted_head)

    def test_removed_protected_finance_source_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            candidate_root = Path(directory)
            baseline, inventory, accepted_head = self._copy_frozen_finance(candidate_root)
            (candidate_root / "contracts/finance/v1/account_role_catalog.json").unlink()
            with self.assertRaisesRegex(PC0ArchitectureError, "PC0-FROZEN-FINANCE-INVENTORY"):
                _validate_finance(candidate_root, baseline, inventory, accepted_head)

    def test_known_legacy_edge_passes_only_at_exact_source(self) -> None:
        path = ROOT / "core/api/accounting/accounting_router.py"
        self.assertEqual([], evaluate_source_text(ROOT, path.relative_to(ROOT).as_posix(), path.read_text(encoding="utf-8")))

    def test_equivalent_legacy_edge_from_new_source_fails(self) -> None:
        violations = evaluate_source_text(
            ROOT,
            "core/api/accounting/new_router.py",
            "from database import get_db\n",
        )
        self.assertEqual(1, len(violations))
        self.assertEqual("legacy_accounting", violations[0]["source_module"])
        self.assertEqual("application", violations[0]["target_module"])

    def test_wholly_new_prohibited_dependency_fails(self) -> None:
        violations = evaluate_source_text(
            ROOT,
            "core/domain/finance/new_illegal_dependency.py",
            "from core.users.user_model import User\n",
        )
        self.assertEqual(1, len(violations))
        self.assertEqual("finance", violations[0]["source_module"])
        self.assertEqual("identity", violations[0]["target_module"])

    def test_new_unmapped_production_source_fails_closed(self) -> None:
        with self.assertRaisesRegex(PC0ArchitectureError, "PC0-UNMAPPED-SOURCE"):
            evaluate_source_text(ROOT, "core/new_feature/handler.py", "from database import get_db\n")

    def test_exception_baseline_has_no_wildcard_or_duplicate_identity(self) -> None:
        baseline = json.loads((ROOT / "contracts/platform/v1/pc0_legacy_exception_baseline.json").read_text(encoding="utf-8"))
        self.assertIs(False, baseline["wildcards_allowed"])
        keys = []
        for item in baseline["exceptions"]:
            key = tuple(item[name] for name in ("source_path", "import_name", "source_module", "target_module"))
            self.assertFalse(any(char in value for value in key for char in "*?["))
            keys.append(key)
        self.assertEqual(len(keys), len(set(keys)))

    def test_windows_gate_uses_only_approved_active_python(self) -> None:
        source = (ROOT / "XBOS_PC0_RUN_ACCEPTANCE.cmd").read_text(encoding="utf-8")
        self.assertNotIn("py -3.13", source)
        for marker in (
            "python --version",
            '"Python 3.13.3"',
            '"xbos-track-b-b1"',
            'python -c "import sys; print(sys.executable)"',
            "%VIRTUAL_ENV%\\Scripts\\python.exe",
            "python -m pytest --version",
            "python tests\\contracts\\test_pc0_kernel_boundaries.py",
            "python -m pytest -q",
            "python scripts\\verify_pc0_kernel_boundaries.py --development",
            "git diff --check",
            "PC0_SINGLE_GATE=PASS",
        ):
            self.assertIn(marker, source)


if __name__ == "__main__":
    unittest.main()
