import json
from pathlib import Path

import pytest
from sqlalchemy.engine import make_url

from core.persistence.m13_foundation import (
    ADOPTION_REHEARSAL_DATABASE,
    APPEND_ONLY_TABLES,
    FOUNDATION_REVISION,
    FOUNDATION_TABLES,
    FRESH_REHEARSAL_DATABASE,
    SOURCE_STATE_REVISION,
    checked_rehearsal_url,
)


ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "contracts" / "persistence" / "v1" / "m13_neutral_financial_foundation.json"
UP_SQL = ROOT / "alembic_neutral" / "sql" / "m13_financial_foundation_up.sql"
DOWN_SQL = ROOT / "alembic_neutral" / "sql" / "m13_financial_foundation_down.sql"


def _contract():
    return json.loads(CONTRACT.read_text(encoding="utf-8"))


def test_m13_contract_has_one_ordered_canonical_lineage():
    contract = _contract()
    lineage = contract["canonical_lineage"]
    assert lineage["source_state_revision"] == SOURCE_STATE_REVISION
    assert lineage["foundation_revision"] == FOUNDATION_REVISION
    assert lineage["script_location"] == "alembic_neutral"


def test_m13_scope_is_empty_and_non_activating():
    scope = _contract()["scope"]
    assert scope["creates_empty_structures_only"] is True
    assert scope["seeds_event_catalog"] is False
    assert scope["emits_financial_events"] is False
    assert scope["transforms_history"] is False
    assert scope["changes_source_writers"] is False
    assert scope["switches_main_alembic_authority"] is False


def test_manifest_and_python_policy_agree_on_tables():
    assert tuple(_contract()["foundation_tables"]) == FOUNDATION_TABLES
    assert len(FOUNDATION_TABLES) == len(set(FOUNDATION_TABLES)) == 15


def test_superseded_backfill_names_are_not_installed():
    contract = _contract()
    assert contract["transformation_naming"]["approved"] == [
        "historical_transformation_runs",
        "historical_transformation_exceptions",
    ]
    sql = UP_SQL.read_text(encoding="utf-8")
    assert "canonical_backfill_runs" not in sql
    assert "canonical_backfill_exceptions" not in sql


@pytest.mark.parametrize("table_name", FOUNDATION_TABLES)
def test_every_foundation_table_has_upgrade_and_downgrade_ddl(table_name):
    up = UP_SQL.read_text(encoding="utf-8")
    down = DOWN_SQL.read_text(encoding="utf-8")
    assert f"CREATE TABLE public.{table_name}" in up
    assert f"DROP TABLE IF EXISTS public.{table_name}" in down


def test_financial_storage_uses_approved_types_and_identity():
    sql = UP_SQL.read_text(encoding="utf-8")
    assert "NUMERIC(24,8)" in sql
    assert "TIMESTAMPTZ" in sql
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "UUID NOT NULL DEFAULT gen_random_uuid()" in sql
    assert "DOUBLE PRECISION" not in sql
    assert " REAL" not in sql


def test_tenant_owned_relationships_use_composite_keys():
    sql = UP_SQL.read_text(encoding="utf-8")
    assert "uq_users_tenant_id_id UNIQUE (tenant_id, id)" in sql
    assert "uq_taxonomy_nodes_tenant_id_id UNIQUE (tenant_id, id)" in sql
    assert "(tenant_id, organization_unit_id)" in sql
    assert "(tenant_id, source_record_id)" in sql
    assert "(tenant_id, actor_user_id)" in sql
    assert "ON DELETE CASCADE" not in sql


@pytest.mark.parametrize("table_name", sorted(APPEND_ONLY_TABLES))
def test_append_only_tables_are_trigger_protected(table_name):
    sql = UP_SQL.read_text(encoding="utf-8")
    if table_name == "financial_event_type_versions":
        assert "tr_financial_event_types_immutable" in sql
    elif table_name == "financial_event_taxonomy":
        assert "tr_financial_event_taxonomy_immutable" in sql
    else:
        assert "tr_financial_events_immutable" in sql


def test_event_catalog_is_versioned_but_not_seeded_by_m1():
    sql = UP_SQL.read_text(encoding="utf-8")
    assert "PRIMARY KEY (event_type_code, event_version)" in sql
    assert "INSERT INTO public.financial_event_type_versions" not in sql
    assert "xbos_validate_financial_event_amount" in sql


def test_outbox_content_is_immutable_but_delivery_fields_can_change():
    sql = UP_SQL.read_text(encoding="utf-8")
    assert "tr_outbox_content_immutable" in sql
    assert "NEW.delivery_state" not in sql.split(
        "CREATE OR REPLACE FUNCTION public.xbos_protect_outbox_content()", 1
    )[1]


def test_rehearsal_url_guard_accepts_only_fixed_local_databases():
    base = make_url("postgresql+psycopg2://postgres:password@localhost:5432/xbos")
    assert checked_rehearsal_url(base, FRESH_REHEARSAL_DATABASE).database == FRESH_REHEARSAL_DATABASE
    assert checked_rehearsal_url(base, ADOPTION_REHEARSAL_DATABASE).database == ADOPTION_REHEARSAL_DATABASE

    with pytest.raises(RuntimeError):
        checked_rehearsal_url(base, "xbos")
    with pytest.raises(RuntimeError):
        checked_rehearsal_url(
            "postgresql+psycopg2://postgres:password@db.example.com:5432/xbos",
            FRESH_REHEARSAL_DATABASE,
        )


def test_reconstruction_lineage_remains_separate_until_activation_gate():
    root_revision = (
        ROOT
        / "alembic_neutral"
        / "versions"
        / "m13_source_state_001_source_state_baseline.py"
    ).read_text(encoding="utf-8")
    foundation_revision = (
        ROOT
        / "alembic_neutral"
        / "versions"
        / "m13_financial_foundation_002_empty_financial_foundation.py"
    ).read_text(encoding="utf-8")
    assert 'down_revision = None' in root_revision
    assert f'down_revision = "{SOURCE_STATE_REVISION}"' in foundation_revision
    assert _contract()["activation_gate"]["main_lineage_switch"] == "separate_approval"
