CREATE TABLE public.restaurant_customer_delivery_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    policy_code VARCHAR(120) NOT NULL,
    policy_version INTEGER NOT NULL DEFAULT 1,
    address_match_rule JSONB NOT NULL,
    fee_catalog_entry_public_id UUID NOT NULL,
    fee_price_public_id UUID NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    row_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cc_delivery_policy_public UNIQUE(public_id),
    CONSTRAINT uq_cc_delivery_policy_version UNIQUE(tenant_id,location_id,policy_code,policy_version),
    CONSTRAINT fk_cc_delivery_policy_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_delivery_policy_organization FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_delivery_policy_location FOREIGN KEY(tenant_id,location_id)
        REFERENCES public.locations(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_delivery_policy_entry FOREIGN KEY(fee_catalog_entry_public_id)
        REFERENCES public.so1_catalog_entries(public_id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_delivery_policy_price FOREIGN KEY(fee_price_public_id)
        REFERENCES public.so1_prices(public_id) ON DELETE RESTRICT,
    CONSTRAINT ck_cc_delivery_policy_code CHECK(
        policy_code=lower(btrim(policy_code)) AND length(policy_code)>0
    ),
    CONSTRAINT ck_cc_delivery_policy_version CHECK(policy_version>=1),
    CONSTRAINT ck_cc_delivery_policy_rule CHECK(jsonb_typeof(address_match_rule)='object'),
    CONSTRAINT ck_cc_delivery_policy_window CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_cc_delivery_policy_row_version CHECK(row_version>=1)
);

CREATE INDEX ix_cc_delivery_policy_resolution
    ON public.restaurant_customer_delivery_policies(
        tenant_id,location_id,active,effective_from,effective_to,policy_code,policy_version
    );

CREATE TABLE public.restaurant_customer_order_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    merchant_public_id UUID NOT NULL,
    context_binding_public_id UUID NOT NULL,
    service_mode VARCHAR(24) NOT NULL,
    table_resource_public_id UUID NULL,
    contact_binding_public_id UUID NULL,
    delivery_address_binding_public_id UUID NULL,
    authoritative_snapshot JSONB NOT NULL,
    commercial_fingerprint CHAR(64) NOT NULL,
    observed_quote_ref VARCHAR(240) NULL,
    observed_quote_version VARCHAR(240) NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    claimed_client_submit_ref_hash CHAR(64) NULL,
    order_public_id UUID NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cc_order_confirmation_public UNIQUE(public_id),
    CONSTRAINT uq_cc_order_confirmation_tenant_public UNIQUE(tenant_id,public_id),
    CONSTRAINT fk_cc_order_confirmation_tenant FOREIGN KEY(tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_organization FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_location FOREIGN KEY(tenant_id,location_id)
        REFERENCES public.locations(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_merchant FOREIGN KEY(merchant_public_id)
        REFERENCES public.pa_merchants(public_id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_context FOREIGN KEY(tenant_id,context_binding_public_id)
        REFERENCES public.ia0_interaction_context_bindings(tenant_id,public_id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_table FOREIGN KEY(tenant_id,table_resource_public_id)
        REFERENCES public.so5_resources(tenant_id,public_id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_contact FOREIGN KEY(tenant_id,contact_binding_public_id)
        REFERENCES public.ia0_interaction_context_bindings(tenant_id,public_id) ON DELETE RESTRICT,
    CONSTRAINT fk_cc_order_confirmation_address FOREIGN KEY(tenant_id,delivery_address_binding_public_id)
        REFERENCES public.ia0_interaction_context_bindings(tenant_id,public_id) ON DELETE RESTRICT,
    CONSTRAINT ck_cc_order_confirmation_mode CHECK(service_mode IN ('dine_in','takeaway','delivery')),
    CONSTRAINT ck_cc_order_confirmation_snapshot CHECK(jsonb_typeof(authoritative_snapshot)='object'),
    CONSTRAINT ck_cc_order_confirmation_fingerprint CHECK(commercial_fingerprint~'^[0-9a-f]{64}$'),
    CONSTRAINT ck_cc_order_confirmation_claim_hash CHECK(
        claimed_client_submit_ref_hash IS NULL OR claimed_client_submit_ref_hash~'^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_cc_order_confirmation_expiry CHECK(expires_at>created_at),
    CONSTRAINT ck_cc_order_confirmation_row_version CHECK(row_version>=1)
);

CREATE UNIQUE INDEX uq_cc_confirmation_claimed_submit
    ON public.restaurant_customer_order_confirmations(tenant_id,claimed_client_submit_ref_hash)
    WHERE claimed_client_submit_ref_hash IS NOT NULL;

CREATE INDEX ix_cc_confirmation_lookup
    ON public.restaurant_customer_order_confirmations(tenant_id,public_id,expires_at);

CREATE OR REPLACE FUNCTION public.restaurant_customer_confirmation_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF ROW(
        NEW.tenant_id,
        NEW.organization_unit_id,
        NEW.location_id,
        NEW.merchant_public_id,
        NEW.context_binding_public_id,
        NEW.service_mode,
        NEW.table_resource_public_id,
        NEW.contact_binding_public_id,
        NEW.delivery_address_binding_public_id,
        NEW.authoritative_snapshot,
        NEW.commercial_fingerprint,
        NEW.observed_quote_ref,
        NEW.observed_quote_version,
        NEW.expires_at,
        NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.tenant_id,
        OLD.organization_unit_id,
        OLD.location_id,
        OLD.merchant_public_id,
        OLD.context_binding_public_id,
        OLD.service_mode,
        OLD.table_resource_public_id,
        OLD.contact_binding_public_id,
        OLD.delivery_address_binding_public_id,
        OLD.authoritative_snapshot,
        OLD.commercial_fingerprint,
        OLD.observed_quote_ref,
        OLD.observed_quote_version,
        OLD.expires_at,
        OLD.created_at
    ) THEN
        RAISE EXCEPTION 'Customer Channel confirmation commercial fields are immutable';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER trg_cc_confirmation_immutable
BEFORE UPDATE ON public.restaurant_customer_order_confirmations
FOR EACH ROW EXECUTE FUNCTION public.restaurant_customer_confirmation_immutable();

COMMENT ON TABLE public.restaurant_customer_delivery_policies IS
'XBOS Restaurant Customer Channel authoritative tenant/location delivery eligibility and SO1 fee binding.';

COMMENT ON TABLE public.restaurant_customer_order_confirmations IS
'Durable immutable Customer Channel commercial confirmation; claim/order linkage may advance without changing commercial truth.';
