CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_tenant_id_id'
    ) THEN
        ALTER TABLE public.users
            ADD CONSTRAINT uq_users_tenant_id_id UNIQUE (tenant_id, id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_taxonomy_nodes_tenant_id_id'
    ) THEN
        ALTER TABLE public.taxonomy_nodes
            ADD CONSTRAINT uq_taxonomy_nodes_tenant_id_id UNIQUE (tenant_id, id);
    END IF;
END
$$;

CREATE TABLE public.organization_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    parent_id BIGINT NULL,
    unit_type VARCHAR(32) NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    timezone_name VARCHAR(64) NULL,
    business_calendar_policy_id BIGINT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_organization_units_public_id UNIQUE (public_id),
    CONSTRAINT uq_organization_units_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_organization_units_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT fk_organization_units_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_units_parent FOREIGN KEY (tenant_id, parent_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_organization_units_code_trimmed
        CHECK (code = btrim(code) AND length(code) > 0),
    CONSTRAINT ck_organization_units_name_nonempty
        CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_organization_units_parent_not_self
        CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_organization_units_row_version CHECK (row_version >= 1)
);
CREATE INDEX ix_organization_units_tenant_parent
    ON public.organization_units (tenant_id, parent_id);
CREATE INDEX ix_organization_units_tenant_type_active
    ON public.organization_units (tenant_id, unit_type, active);

CREATE TABLE public.currency_assets (
    code VARCHAR(12) PRIMARY KEY,
    asset_kind VARCHAR(16) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    minor_unit_scale SMALLINT NOT NULL,
    maximum_storage_scale SMALLINT NOT NULL DEFAULT 8,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_currency_assets_kind
        CHECK (asset_kind IN ('fiat','crypto','points','other')),
    CONSTRAINT ck_currency_assets_code_upper
        CHECK (code = upper(btrim(code)) AND length(code) > 0),
    CONSTRAINT ck_currency_assets_minor_scale
        CHECK (minor_unit_scale BETWEEN 0 AND 8),
    CONSTRAINT ck_currency_assets_max_scale
        CHECK (maximum_storage_scale BETWEEN minor_unit_scale AND 8),
    CONSTRAINT ck_currency_assets_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE public.tenant_currency_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    rounding_mode VARCHAR(24) NOT NULL,
    cash_rounding_increment NUMERIC(24,8) NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    policy_version INTEGER NOT NULL,
    CONSTRAINT uq_tenant_currency_policy_version
        UNIQUE (tenant_id, currency_code, policy_version),
    CONSTRAINT fk_tenant_currency_policies_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tenant_currency_policies_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT ck_tenant_currency_policy_version CHECK (policy_version > 0),
    CONSTRAINT ck_tenant_currency_policy_effective
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_tenant_currency_policy_increment
        CHECK (cash_rounding_increment >= 0),
    CONSTRAINT ck_tenant_currency_policy_mode_nonempty
        CHECK (length(btrim(rounding_mode)) > 0)
);
CREATE INDEX ix_tenant_currency_policy_effective
    ON public.tenant_currency_policies
    (tenant_id, currency_code, effective_from DESC);

CREATE TABLE public.business_cycle_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NULL,
    policy_code VARCHAR(64) NOT NULL,
    policy_version INTEGER NOT NULL,
    timezone_name VARCHAR(64) NOT NULL,
    cycle_type VARCHAR(24) NOT NULL,
    cycle_definition JSONB NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    approved_by_user_id INTEGER NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_business_cycle_policies_public_id UNIQUE (public_id),
    CONSTRAINT uq_business_cycle_policies_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_business_cycle_policy_version
        UNIQUE (tenant_id, policy_code, policy_version),
    CONSTRAINT fk_business_cycle_policies_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_business_cycle_policies_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_business_cycle_policies_actor FOREIGN KEY
        (tenant_id, approved_by_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_business_cycle_policies_type
        CHECK (cycle_type IN ('shift','daily','monthly','custom')),
    CONSTRAINT ck_business_cycle_policies_version CHECK (policy_version > 0),
    CONSTRAINT ck_business_cycle_policies_definition_object
        CHECK (jsonb_typeof(cycle_definition) = 'object'),
    CONSTRAINT ck_business_cycle_policies_effective
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_business_cycle_policies_code_nonempty
        CHECK (length(btrim(policy_code)) > 0)
);
CREATE INDEX ix_business_cycle_policy_effective
    ON public.business_cycle_policies
    (tenant_id, policy_code, effective_from DESC);

ALTER TABLE public.organization_units
    ADD CONSTRAINT fk_organization_units_business_calendar_policy
    FOREIGN KEY (tenant_id, business_calendar_policy_id)
    REFERENCES public.business_cycle_policies(tenant_id, id)
    ON DELETE RESTRICT;

CREATE TABLE public.kernel_source_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NULL,
    source_component VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_external_id VARCHAR(160) NOT NULL,
    aggregate_version VARCHAR(80) NULL,
    source_occurred_at TIMESTAMPTZ NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    retired_at TIMESTAMPTZ NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_kernel_source_records_public_id UNIQUE (public_id),
    CONSTRAINT uq_kernel_source_records_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_kernel_source_records_identity UNIQUE
        (tenant_id, source_component, aggregate_type, aggregate_external_id),
    CONSTRAINT fk_kernel_source_records_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_kernel_source_records_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_kernel_source_records_component
        CHECK (source_component = lower(btrim(source_component)) AND length(source_component) > 0),
    CONSTRAINT ck_kernel_source_records_aggregate_type
        CHECK (aggregate_type = lower(btrim(aggregate_type)) AND length(aggregate_type) > 0),
    CONSTRAINT ck_kernel_source_records_external_id
        CHECK (aggregate_external_id = btrim(aggregate_external_id) AND length(aggregate_external_id) > 0),
    CONSTRAINT ck_kernel_source_records_retired
        CHECK (retired_at IS NULL OR retired_at >= registered_at),
    CONSTRAINT ck_kernel_source_records_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_source_records_tenant_component
    ON public.kernel_source_records (tenant_id, source_component, aggregate_type);
CREATE INDEX ix_source_records_org_registered
    ON public.kernel_source_records
    (tenant_id, organization_unit_id, registered_at DESC);

CREATE TABLE public.financial_counterparties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    counterparty_kind VARCHAR(24) NOT NULL,
    party_id BIGINT NULL,
    organization_unit_id BIGINT NULL,
    source_record_id BIGINT NULL,
    display_name_snapshot VARCHAR(200) NOT NULL,
    contact_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_financial_counterparties_public_id UNIQUE (public_id),
    CONSTRAINT uq_financial_counterparties_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_financial_counterparties_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_counterparties_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_counterparties_source FOREIGN KEY
        (tenant_id, source_record_id)
        REFERENCES public.kernel_source_records(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_counterparties_kind
        CHECK (counterparty_kind IN ('party','organization_unit','external','system')),
    CONSTRAINT ck_financial_counterparties_display_name
        CHECK (length(btrim(display_name_snapshot)) > 0),
    CONSTRAINT ck_financial_counterparties_contact_object
        CHECK (jsonb_typeof(contact_snapshot) = 'object'),
    CONSTRAINT ck_financial_counterparties_kind_reference CHECK (
        (counterparty_kind = 'party' AND party_id IS NOT NULL) OR
        (counterparty_kind = 'organization_unit' AND organization_unit_id IS NOT NULL) OR
        (counterparty_kind = 'external' AND source_record_id IS NOT NULL) OR
        counterparty_kind = 'system'
    )
);
CREATE INDEX ix_counterparties_tenant_kind_active
    ON public.financial_counterparties (tenant_id, counterparty_kind, active);
CREATE INDEX ix_counterparties_source
    ON public.financial_counterparties (tenant_id, source_record_id)
    WHERE source_record_id IS NOT NULL;
CREATE INDEX ix_counterparties_party
    ON public.financial_counterparties (tenant_id, party_id)
    WHERE party_id IS NOT NULL;

CREATE TABLE public.operational_financial_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    parent_account_id BIGINT NULL,
    account_class VARCHAR(32) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    code VARCHAR(64) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    channel_code VARCHAR(64) NULL,
    external_account_mask VARCHAR(80) NULL,
    aggregation_role VARCHAR(24) NOT NULL DEFAULT 'leaf',
    reconciliation_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    opened_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_operational_financial_accounts_public_id UNIQUE (public_id),
    CONSTRAINT uq_operational_financial_accounts_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_operational_financial_accounts_org_code
        UNIQUE (tenant_id, organization_unit_id, code),
    CONSTRAINT fk_operational_financial_accounts_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_financial_accounts_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_financial_accounts_parent FOREIGN KEY
        (tenant_id, parent_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_financial_accounts_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT ck_operational_financial_accounts_class
        CHECK (account_class IN ('treasury','control_account','commercial_settlement')),
    CONSTRAINT ck_operational_financial_accounts_type
        CHECK (account_type IN ('cash','mobile_money','bank','card','gateway','receivable','payable','clearing','other')),
    CONSTRAINT ck_operational_financial_accounts_aggregation
        CHECK (aggregation_role IN ('leaf','parent_aggregate','presentation_only')),
    CONSTRAINT ck_operational_financial_accounts_code
        CHECK (code = btrim(code) AND length(code) > 0),
    CONSTRAINT ck_operational_financial_accounts_name
        CHECK (length(btrim(display_name)) > 0),
    CONSTRAINT ck_operational_financial_accounts_closed
        CHECK (closed_at IS NULL OR closed_at >= opened_at),
    CONSTRAINT ck_operational_financial_accounts_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_operational_accounts_recon
    ON public.operational_financial_accounts
    (tenant_id, organization_unit_id, reconciliation_enabled, active);
CREATE INDEX ix_operational_accounts_parent
    ON public.operational_financial_accounts (tenant_id, parent_account_id);
CREATE INDEX ix_operational_accounts_class_type
    ON public.operational_financial_accounts
    (tenant_id, account_class, account_type, active);

CREATE TABLE public.payment_provider_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NULL,
    provider_code VARCHAR(64) NOT NULL,
    external_account_reference VARCHAR(255) NOT NULL,
    credential_reference VARCHAR(255) NOT NULL,
    webhook_key_reference VARCHAR(255) NULL,
    environment VARCHAR(16) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_payment_provider_accounts_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_provider_accounts_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_payment_provider_accounts_external
        UNIQUE (provider_code, environment, external_account_reference),
    CONSTRAINT fk_payment_provider_accounts_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_provider_accounts_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_provider_accounts_environment
        CHECK (environment IN ('sandbox','production')),
    CONSTRAINT ck_payment_provider_accounts_credential
        CHECK (length(btrim(credential_reference)) > 0),
    CONSTRAINT ck_payment_provider_accounts_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_payment_provider_accounts_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_provider_accounts_tenant_provider
    ON public.payment_provider_accounts (tenant_id, provider_code, active);

CREATE TABLE public.idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    processing_state VARCHAR(24) NOT NULL,
    result_source_record_id BIGINT NULL,
    response_code INTEGER NULL,
    response_snapshot JSONB NULL,
    locked_until TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_idempotency_records_scope_key
        UNIQUE (tenant_id, scope, idempotency_key),
    CONSTRAINT fk_idempotency_records_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_idempotency_records_source FOREIGN KEY
        (tenant_id, result_source_record_id)
        REFERENCES public.kernel_source_records(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_idempotency_records_state
        CHECK (processing_state IN ('processing','completed','failed','expired')),
    CONSTRAINT ck_idempotency_records_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_records_completed
        CHECK (processing_state <> 'completed' OR completed_at IS NOT NULL),
    CONSTRAINT ck_idempotency_records_expiry
        CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT ck_idempotency_records_response_object
        CHECK (response_snapshot IS NULL OR jsonb_typeof(response_snapshot) = 'object')
);
CREATE INDEX ix_idempotency_processing_lease
    ON public.idempotency_records (processing_state, locked_until)
    WHERE processing_state = 'processing';
CREATE INDEX ix_idempotency_expiry
    ON public.idempotency_records (expires_at)
    WHERE expires_at IS NOT NULL;

CREATE TABLE public.financial_event_type_versions (
    event_type_code VARCHAR(80) NOT NULL,
    event_version SMALLINT NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    definition TEXT NOT NULL,
    amount_policy VARCHAR(24) NOT NULL,
    default_economic_role VARCHAR(32) NOT NULL,
    reconciliation_effect VARCHAR(32) NOT NULL,
    account_role_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    posting_eligible BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    approved_at TIMESTAMPTZ NOT NULL,
    definition_hash CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_financial_event_type_versions
        PRIMARY KEY (event_type_code, event_version),
    CONSTRAINT uq_financial_event_type_versions_hash UNIQUE (definition_hash),
    CONSTRAINT ck_financial_event_type_versions_code
        CHECK (event_type_code = upper(btrim(event_type_code)) AND length(event_type_code) > 0),
    CONSTRAINT ck_financial_event_type_versions_version CHECK (event_version > 0),
    CONSTRAINT ck_financial_event_type_versions_amount_policy
        CHECK (amount_policy IN ('positive','nonzero','zero_allowed')),
    CONSTRAINT ck_financial_event_type_versions_economic_role CHECK (
        default_economic_role IN (
            'recognition','settlement_in','settlement_out','allocation',
            'deallocation','transfer','liability_recognition','control','correction'
        )
    ),
    CONSTRAINT ck_financial_event_type_versions_recon_effect
        CHECK (reconciliation_effect IN ('inflow','outflow','movement','control','commercial','none')),
    CONSTRAINT ck_financial_event_type_versions_effective
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_financial_event_type_versions_hash
        CHECK (definition_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_financial_event_type_versions_role_policy_object
        CHECK (jsonb_typeof(account_role_policy) = 'object'),
    CONSTRAINT ck_financial_event_type_versions_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE public.financial_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    event_type_code VARCHAR(80) NOT NULL,
    event_version SMALLINT NOT NULL,
    amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    economic_role VARCHAR(32) NOT NULL,
    source_operational_account_id BIGINT NULL,
    target_operational_account_id BIGINT NULL,
    source_record_id BIGINT NOT NULL,
    original_event_id BIGINT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    classification_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    posting_context JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence_hash CHAR(64) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_financial_events_public_id UNIQUE (public_id),
    CONSTRAINT uq_financial_events_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_financial_events_idempotency
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT fk_financial_events_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_type FOREIGN KEY
        (event_type_code, event_version)
        REFERENCES public.financial_event_type_versions(event_type_code, event_version)
        ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_source_account FOREIGN KEY
        (tenant_id, source_operational_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_target_account FOREIGN KEY
        (tenant_id, target_operational_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_source_record FOREIGN KEY
        (tenant_id, source_record_id)
        REFERENCES public.kernel_source_records(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_original FOREIGN KEY
        (tenant_id, original_event_id)
        REFERENCES public.financial_events(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_events_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_events_actor
        CHECK (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service), '') IS NOT NULL),
    CONSTRAINT ck_financial_events_account_distinct CHECK (
        source_operational_account_id IS NULL OR
        target_operational_account_id IS NULL OR
        source_operational_account_id <> target_operational_account_id
    ),
    CONSTRAINT ck_financial_events_calendar_version CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_financial_events_economic_role CHECK (
        economic_role IN (
            'recognition','settlement_in','settlement_out','allocation',
            'deallocation','transfer','liability_recognition','control','correction'
        )
    ),
    CONSTRAINT ck_financial_events_classification_object
        CHECK (jsonb_typeof(classification_snapshot) = 'object'),
    CONSTRAINT ck_financial_events_posting_context_object
        CHECK (jsonb_typeof(posting_context) = 'object'),
    CONSTRAINT ck_financial_events_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT ck_financial_events_evidence_hash
        CHECK (evidence_hash IS NULL OR evidence_hash ~ '^[0-9a-f]{64}$')
);
CREATE INDEX ix_financial_events_org_occurred
    ON public.financial_events
    (tenant_id, organization_unit_id, occurred_at DESC, id DESC);
CREATE INDEX ix_financial_events_business_type
    ON public.financial_events
    (tenant_id, organization_unit_id, business_date, event_type_code);
CREATE INDEX ix_financial_events_source
    ON public.financial_events (tenant_id, source_record_id, occurred_at);
CREATE INDEX ix_financial_events_source_account_date
    ON public.financial_events
    (tenant_id, source_operational_account_id, business_date, id)
    WHERE source_operational_account_id IS NOT NULL;
CREATE INDEX ix_financial_events_target_account_date
    ON public.financial_events
    (tenant_id, target_operational_account_id, business_date, id)
    WHERE target_operational_account_id IS NOT NULL;
CREATE INDEX ix_financial_events_correlation
    ON public.financial_events (tenant_id, correlation_id, recorded_at);
CREATE INDEX ix_financial_events_original
    ON public.financial_events (tenant_id, original_event_id)
    WHERE original_event_id IS NOT NULL;
CREATE INDEX brin_financial_events_recorded_at
    ON public.financial_events USING BRIN (recorded_at);

CREATE TABLE public.financial_event_taxonomy (
    tenant_id INTEGER NOT NULL,
    financial_event_id BIGINT NOT NULL,
    taxonomy_node_id INTEGER NOT NULL,
    classification_role VARCHAR(32) NOT NULL,
    classification_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_financial_event_taxonomy
        PRIMARY KEY (financial_event_id, taxonomy_node_id, classification_role),
    CONSTRAINT fk_financial_event_taxonomy_event FOREIGN KEY
        (tenant_id, financial_event_id)
        REFERENCES public.financial_events(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_event_taxonomy_node FOREIGN KEY
        (tenant_id, taxonomy_node_id)
        REFERENCES public.taxonomy_nodes(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_event_taxonomy_role
        CHECK (length(btrim(classification_role)) > 0),
    CONSTRAINT ck_financial_event_taxonomy_snapshot_object
        CHECK (jsonb_typeof(classification_snapshot) = 'object')
);
CREATE INDEX ix_financial_event_taxonomy_node
    ON public.financial_event_taxonomy
    (tenant_id, taxonomy_node_id, financial_event_id);

CREATE TABLE public.outbox_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    source_event_public_id UUID NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_public_id UUID NOT NULL,
    event_name VARCHAR(120) NOT NULL,
    event_version SMALLINT NOT NULL,
    payload JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    delivery_state VARCHAR(24) NOT NULL DEFAULT 'pending',
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ NULL,
    delivery_attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    locked_by VARCHAR(120) NULL,
    locked_until TIMESTAMPTZ NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    CONSTRAINT uq_outbox_messages_public_id UNIQUE (public_id),
    CONSTRAINT uq_outbox_messages_source_event UNIQUE (tenant_id, source_event_public_id),
    CONSTRAINT fk_outbox_messages_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_outbox_messages_state
        CHECK (delivery_state IN ('pending','published','retrying','dead_letter')),
    CONSTRAINT ck_outbox_messages_payload_object CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_outbox_messages_payload_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_outbox_messages_attempts CHECK (delivery_attempts >= 0),
    CONSTRAINT ck_outbox_messages_version CHECK (event_version > 0),
    CONSTRAINT ck_outbox_messages_published
        CHECK (delivery_state <> 'published' OR published_at IS NOT NULL)
);
CREATE INDEX ix_outbox_delivery_queue
    ON public.outbox_messages (delivery_state, available_at, id)
    WHERE delivery_state IN ('pending','retrying');
CREATE INDEX ix_outbox_lock_expiry
    ON public.outbox_messages (locked_until)
    WHERE locked_until IS NOT NULL;
CREATE INDEX ix_outbox_tenant_created
    ON public.outbox_messages (tenant_id, created_at DESC);

CREATE TABLE public.historical_transformation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    run_type VARCHAR(64) NOT NULL,
    mapping_rule_version VARCHAR(40) NOT NULL,
    source_checkpoint VARCHAR(160) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    run_state VARCHAR(24) NOT NULL,
    started_by_user_id INTEGER NOT NULL,
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_historical_transformation_runs_public_id UNIQUE (public_id),
    CONSTRAINT fk_historical_transformation_runs_actor FOREIGN KEY (started_by_user_id)
        REFERENCES public.users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_historical_transformation_runs_state
        CHECK (run_state IN ('planned','running','completed','failed','abandoned')),
    CONSTRAINT ck_historical_transformation_runs_times
        CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT ck_historical_transformation_runs_summary_object
        CHECK (jsonb_typeof(summary) = 'object')
);

CREATE TABLE public.historical_transformation_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transformation_run_id BIGINT NOT NULL,
    tenant_id INTEGER NOT NULL,
    source_table VARCHAR(80) NOT NULL,
    source_id BIGINT NOT NULL,
    exception_code VARCHAR(80) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    evidence JSONB NOT NULL,
    resolution_state VARCHAR(24) NOT NULL DEFAULT 'open',
    resolution_note TEXT NULL,
    resolved_by_user_id INTEGER NULL,
    resolved_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_historical_transformation_exception_identity UNIQUE
        (transformation_run_id, tenant_id, source_table, source_id, exception_code),
    CONSTRAINT fk_historical_transformation_exceptions_run FOREIGN KEY (transformation_run_id)
        REFERENCES public.historical_transformation_runs(id) ON DELETE RESTRICT,
    CONSTRAINT fk_historical_transformation_exceptions_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_historical_transformation_exceptions_resolver FOREIGN KEY
        (tenant_id, resolved_by_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_historical_transformation_exceptions_severity
        CHECK (severity IN ('info','warning','error','critical')),
    CONSTRAINT ck_historical_transformation_exceptions_resolution
        CHECK (resolution_state IN ('open','accepted','corrected','excluded')),
    CONSTRAINT ck_historical_transformation_exceptions_evidence_object
        CHECK (jsonb_typeof(evidence) = 'object'),
    CONSTRAINT ck_historical_transformation_exceptions_resolution_actor CHECK (
        (resolution_state = 'open' AND resolved_by_user_id IS NULL AND resolved_at IS NULL) OR
        (resolution_state <> 'open' AND resolved_by_user_id IS NOT NULL AND resolved_at IS NOT NULL)
    )
);
CREATE INDEX ix_historical_transformation_exceptions_open
    ON public.historical_transformation_exceptions
    (transformation_run_id, severity, exception_code)
    WHERE resolution_state = 'open';

CREATE OR REPLACE FUNCTION public.xbos_reject_immutable_financial_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is immutable; append a correcting fact instead', TG_TABLE_NAME
        USING ERRCODE = '55000';
END
$$;

CREATE OR REPLACE FUNCTION public.xbos_validate_financial_event_amount()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    selected_policy VARCHAR(24);
BEGIN
    SELECT amount_policy INTO selected_policy
    FROM public.financial_event_type_versions
    WHERE event_type_code = NEW.event_type_code
      AND event_version = NEW.event_version;

    IF selected_policy = 'positive' AND NEW.amount <= 0 THEN
        RAISE EXCEPTION 'event amount must be positive for % v%', NEW.event_type_code, NEW.event_version
            USING ERRCODE = '23514';
    ELSIF selected_policy = 'nonzero' AND NEW.amount = 0 THEN
        RAISE EXCEPTION 'event amount must be nonzero for % v%', NEW.event_type_code, NEW.event_version
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION public.xbos_protect_outbox_content()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF ROW(
        NEW.public_id, NEW.tenant_id, NEW.source_event_public_id,
        NEW.aggregate_type, NEW.aggregate_public_id, NEW.event_name,
        NEW.event_version, NEW.payload, NEW.payload_hash,
        NEW.created_at, NEW.correlation_id, NEW.causation_id
    ) IS DISTINCT FROM ROW(
        OLD.public_id, OLD.tenant_id, OLD.source_event_public_id,
        OLD.aggregate_type, OLD.aggregate_public_id, OLD.event_name,
        OLD.event_version, OLD.payload, OLD.payload_hash,
        OLD.created_at, OLD.correlation_id, OLD.causation_id
    ) THEN
        RAISE EXCEPTION 'outbox message content and identity are immutable'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER tr_financial_event_types_immutable
BEFORE UPDATE OR DELETE ON public.financial_event_type_versions
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_financial_mutation();

CREATE TRIGGER tr_financial_events_validate_amount
BEFORE INSERT ON public.financial_events
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_financial_event_amount();

CREATE TRIGGER tr_financial_events_immutable
BEFORE UPDATE OR DELETE ON public.financial_events
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_financial_mutation();

CREATE TRIGGER tr_financial_event_taxonomy_immutable
BEFORE UPDATE OR DELETE ON public.financial_event_taxonomy
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_financial_mutation();

CREATE TRIGGER tr_outbox_content_immutable
BEFORE UPDATE ON public.outbox_messages
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_outbox_content();
