CREATE TABLE public.ledger_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    legal_entity_unit_id BIGINT NOT NULL,
    parent_account_id BIGINT NULL,
    account_code VARCHAR(64) NOT NULL,
    account_name VARCHAR(180) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    normal_balance VARCHAR(8) NOT NULL,
    currency_policy VARCHAR(24) NOT NULL DEFAULT 'fixed',
    fixed_currency_code VARCHAR(12) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_ledger_accounts_public_id UNIQUE (public_id),
    CONSTRAINT uq_ledger_accounts_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_ledger_accounts_entity_code
        UNIQUE (tenant_id, legal_entity_unit_id, account_code),
    CONSTRAINT fk_ledger_accounts_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_accounts_entity FOREIGN KEY
        (tenant_id, legal_entity_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_accounts_parent FOREIGN KEY
        (tenant_id, parent_account_id)
        REFERENCES public.ledger_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_accounts_currency FOREIGN KEY (fixed_currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT ck_ledger_accounts_type CHECK (
        account_type IN ('asset','liability','equity','income','expense','contra','statistical')
    ),
    CONSTRAINT ck_ledger_accounts_normal_balance
        CHECK (normal_balance IN ('debit','credit')),
    CONSTRAINT ck_ledger_accounts_currency_policy
        CHECK (currency_policy IN ('any','base_only','fixed')),
    CONSTRAINT ck_ledger_accounts_fixed_currency CHECK (
        (currency_policy = 'fixed' AND fixed_currency_code IS NOT NULL) OR
        (currency_policy <> 'fixed' AND fixed_currency_code IS NULL)
    ),
    CONSTRAINT ck_ledger_accounts_effective
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_ledger_accounts_code
        CHECK (account_code = btrim(account_code) AND length(account_code) > 0),
    CONSTRAINT ck_ledger_accounts_name
        CHECK (length(btrim(account_name)) > 0),
    CONSTRAINT ck_ledger_accounts_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_ledger_accounts_parent
    ON public.ledger_accounts (tenant_id, parent_account_id);
CREATE INDEX ix_ledger_accounts_type_active
    ON public.ledger_accounts
    (tenant_id, legal_entity_unit_id, account_type, active);

CREATE TABLE public.accounting_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    legal_entity_unit_id BIGINT NOT NULL,
    period_code VARCHAR(32) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    period_state VARCHAR(16) NOT NULL DEFAULT 'open',
    closed_by_user_id INTEGER NULL,
    closed_at TIMESTAMPTZ NULL,
    reopened_by_user_id INTEGER NULL,
    reopened_at TIMESTAMPTZ NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_accounting_periods_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_accounting_periods_code
        UNIQUE (tenant_id, legal_entity_unit_id, period_code),
    CONSTRAINT uq_accounting_periods_range
        UNIQUE (tenant_id, legal_entity_unit_id, period_start, period_end),
    CONSTRAINT fk_accounting_periods_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_accounting_periods_entity FOREIGN KEY
        (tenant_id, legal_entity_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_accounting_periods_closed_by FOREIGN KEY
        (tenant_id, closed_by_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_accounting_periods_reopened_by FOREIGN KEY
        (tenant_id, reopened_by_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_accounting_periods_state
        CHECK (period_state IN ('open','closed','reopened')),
    CONSTRAINT ck_accounting_periods_range
        CHECK (period_end >= period_start),
    CONSTRAINT ck_accounting_periods_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_accounting_periods_closed_state CHECK (
        period_state <> 'closed' OR closed_at IS NOT NULL
    ),
    CONSTRAINT ck_accounting_periods_reopened_state CHECK (
        period_state <> 'reopened' OR reopened_at IS NOT NULL
    )
);
CREATE INDEX ix_accounting_periods_lookup
    ON public.accounting_periods
    (tenant_id, legal_entity_unit_id, period_state, period_start, period_end);

CREATE TABLE public.ledger_account_role_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    legal_entity_unit_id BIGINT NOT NULL,
    account_role VARCHAR(80) NOT NULL,
    binding_key VARCHAR(160) NOT NULL DEFAULT 'default',
    currency_code VARCHAR(12) NOT NULL,
    ledger_account_id BIGINT NOT NULL,
    operational_account_id BIGINT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_ledger_role_bindings_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_ledger_role_binding_identity UNIQUE
        (tenant_id, legal_entity_unit_id, account_role, binding_key, currency_code, effective_from),
    CONSTRAINT fk_ledger_role_bindings_entity FOREIGN KEY
        (tenant_id, legal_entity_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_role_bindings_account FOREIGN KEY
        (tenant_id, ledger_account_id)
        REFERENCES public.ledger_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_role_bindings_operational FOREIGN KEY
        (tenant_id, operational_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_role_bindings_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT ck_ledger_role_bindings_role
        CHECK (account_role = lower(btrim(account_role)) AND length(account_role) > 0),
    CONSTRAINT ck_ledger_role_bindings_key
        CHECK (binding_key = btrim(binding_key) AND length(binding_key) > 0),
    CONSTRAINT ck_ledger_role_bindings_effective
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_ledger_role_bindings_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_ledger_role_bindings_resolve
    ON public.ledger_account_role_bindings
    (tenant_id, legal_entity_unit_id, account_role, binding_key, currency_code, active);

CREATE TABLE public.journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    legal_entity_unit_id BIGINT NOT NULL,
    accounting_period_id BIGINT NOT NULL,
    journal_code VARCHAR(32) NOT NULL,
    entry_number VARCHAR(80) NOT NULL,
    entry_state VARCHAR(24) NOT NULL DEFAULT 'draft',
    transaction_currency_code VARCHAR(12) NOT NULL,
    base_currency_code VARCHAR(12) NOT NULL,
    posting_date DATE NOT NULL,
    business_date DATE NOT NULL,
    description TEXT NOT NULL,
    posting_profile_code VARCHAR(80) NOT NULL,
    reversal_entry_id BIGINT NULL,
    created_by_user_id INTEGER NULL,
    created_by_service VARCHAR(120) NULL,
    approved_by_user_id INTEGER NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    posted_at TIMESTAMPTZ NULL,
    correlation_id UUID NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_journal_entries_public_id UNIQUE (public_id),
    CONSTRAINT uq_journal_entries_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_journal_entries_number UNIQUE
        (tenant_id, legal_entity_unit_id, journal_code, entry_number),
    CONSTRAINT fk_journal_entries_entity FOREIGN KEY
        (tenant_id, legal_entity_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_entries_period FOREIGN KEY
        (tenant_id, accounting_period_id)
        REFERENCES public.accounting_periods(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_entries_transaction_currency
        FOREIGN KEY (transaction_currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_entries_base_currency
        FOREIGN KEY (base_currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_entries_reversal FOREIGN KEY
        (tenant_id, reversal_entry_id)
        REFERENCES public.journal_entries(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_entries_creator FOREIGN KEY
        (tenant_id, created_by_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_entries_approver FOREIGN KEY
        (tenant_id, approved_by_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_journal_entries_state
        CHECK (entry_state IN ('draft','pending_approval','posted','reversed')),
    CONSTRAINT ck_journal_entries_creator CHECK (
        created_by_user_id IS NOT NULL OR NULLIF(btrim(created_by_service), '') IS NOT NULL
    ),
    CONSTRAINT ck_journal_entries_posted CHECK (
        entry_state NOT IN ('posted','reversed') OR posted_at IS NOT NULL
    ),
    CONSTRAINT ck_journal_entries_profile
        CHECK (posting_profile_code = lower(btrim(posting_profile_code)) AND length(posting_profile_code) > 0),
    CONSTRAINT ck_journal_entries_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_journal_entries_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_journal_entries_period_state
    ON public.journal_entries
    (tenant_id, accounting_period_id, entry_state, posting_date, id);
CREATE INDEX ix_journal_entries_correlation
    ON public.journal_entries (tenant_id, correlation_id);
CREATE INDEX ix_journal_entries_reversal
    ON public.journal_entries (tenant_id, reversal_entry_id)
    WHERE reversal_entry_id IS NOT NULL;

CREATE TABLE public.journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    journal_entry_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    ledger_account_id BIGINT NOT NULL,
    account_role VARCHAR(80) NOT NULL,
    description TEXT NULL,
    transaction_currency_code VARCHAR(12) NOT NULL,
    transaction_debit_amount NUMERIC(24,8) NOT NULL DEFAULT 0,
    transaction_credit_amount NUMERIC(24,8) NOT NULL DEFAULT 0,
    base_currency_code VARCHAR(12) NOT NULL,
    base_debit_amount NUMERIC(24,8) NOT NULL DEFAULT 0,
    base_credit_amount NUMERIC(24,8) NOT NULL DEFAULT 0,
    fx_rate NUMERIC(30,12) NULL,
    counterparty_id BIGINT NULL,
    organization_unit_id BIGINT NULL,
    source_record_id BIGINT NULL,
    dimension_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_journal_lines_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_journal_lines_number
        UNIQUE (tenant_id, journal_entry_id, line_number),
    CONSTRAINT fk_journal_lines_entry FOREIGN KEY
        (tenant_id, journal_entry_id)
        REFERENCES public.journal_entries(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_account FOREIGN KEY
        (tenant_id, ledger_account_id)
        REFERENCES public.ledger_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_transaction_currency
        FOREIGN KEY (transaction_currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_base_currency
        FOREIGN KEY (base_currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_counterparty FOREIGN KEY
        (tenant_id, counterparty_id)
        REFERENCES public.financial_counterparties(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_source FOREIGN KEY
        (tenant_id, source_record_id)
        REFERENCES public.kernel_source_records(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_journal_lines_line_number CHECK (line_number > 0),
    CONSTRAINT ck_journal_lines_role
        CHECK (account_role = lower(btrim(account_role)) AND length(account_role) > 0),
    CONSTRAINT ck_journal_lines_transaction_side CHECK (
        transaction_debit_amount >= 0 AND transaction_credit_amount >= 0 AND
        ((transaction_debit_amount > 0 AND transaction_credit_amount = 0) OR
         (transaction_debit_amount = 0 AND transaction_credit_amount > 0))
    ),
    CONSTRAINT ck_journal_lines_base_side CHECK (
        base_debit_amount >= 0 AND base_credit_amount >= 0 AND
        ((base_debit_amount > 0 AND base_credit_amount = 0) OR
         (base_debit_amount = 0 AND base_credit_amount > 0))
    ),
    CONSTRAINT ck_journal_lines_fx CHECK (
        (transaction_currency_code = base_currency_code AND (fx_rate IS NULL OR fx_rate = 1)) OR
        (transaction_currency_code <> base_currency_code AND fx_rate > 0)
    ),
    CONSTRAINT ck_journal_lines_dimension_object
        CHECK (jsonb_typeof(dimension_snapshot) = 'object')
);
CREATE INDEX ix_journal_lines_entry
    ON public.journal_lines (tenant_id, journal_entry_id, line_number);
CREATE INDEX ix_journal_lines_account
    ON public.journal_lines (tenant_id, ledger_account_id, journal_entry_id);

CREATE TABLE public.journal_entry_event_links (
    tenant_id INTEGER NOT NULL,
    journal_entry_id BIGINT NOT NULL,
    financial_event_id BIGINT NOT NULL,
    source_amount NUMERIC(24,8) NULL,
    allocation_role VARCHAR(32) NULL,
    CONSTRAINT pk_journal_entry_event_links
        PRIMARY KEY (journal_entry_id, financial_event_id),
    CONSTRAINT fk_journal_event_links_entry FOREIGN KEY
        (tenant_id, journal_entry_id)
        REFERENCES public.journal_entries(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_journal_event_links_event FOREIGN KEY
        (tenant_id, financial_event_id)
        REFERENCES public.financial_events(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_journal_event_links_amount
        CHECK (source_amount IS NULL OR source_amount > 0)
);
CREATE INDEX ix_journal_event_links_event
    ON public.journal_entry_event_links
    (tenant_id, financial_event_id, journal_entry_id);

CREATE OR REPLACE FUNCTION public.xbos_validate_posted_journal_balance()
RETURNS trigger
LANGUAGE plpgsql
AS $body$
DECLARE
    selected_entry_id BIGINT;
    selected_tenant_id INTEGER;
    selected_state VARCHAR(24);
    line_count BIGINT;
    transaction_debits NUMERIC(24,8);
    transaction_credits NUMERIC(24,8);
    base_debits NUMERIC(24,8);
    base_credits NUMERIC(24,8);
BEGIN
    IF TG_TABLE_NAME = 'journal_entries' THEN
        selected_entry_id := NEW.id;
        selected_tenant_id := NEW.tenant_id;
    ELSE
        selected_entry_id := COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
        selected_tenant_id := COALESCE(NEW.tenant_id, OLD.tenant_id);
    END IF;

    SELECT entry_state
      INTO selected_state
      FROM public.journal_entries
     WHERE tenant_id = selected_tenant_id
       AND id = selected_entry_id;

    IF selected_state IN ('posted','reversed') THEN
        SELECT count(*),
               COALESCE(sum(transaction_debit_amount), 0),
               COALESCE(sum(transaction_credit_amount), 0),
               COALESCE(sum(base_debit_amount), 0),
               COALESCE(sum(base_credit_amount), 0)
          INTO line_count, transaction_debits, transaction_credits, base_debits, base_credits
          FROM public.journal_lines
         WHERE tenant_id = selected_tenant_id
           AND journal_entry_id = selected_entry_id;

        IF line_count < 2 THEN
            RAISE EXCEPTION USING MESSAGE = 'posted journal entry must contain at least two lines';
        END IF;
        IF transaction_debits <> transaction_credits THEN
            RAISE EXCEPTION USING MESSAGE = 'posted journal transaction currency is not balanced';
        END IF;
        IF base_debits <> base_credits THEN
            RAISE EXCEPTION USING MESSAGE = 'posted journal base currency is not balanced';
        END IF;
    END IF;
    RETURN NULL;
END
$body$;

CREATE CONSTRAINT TRIGGER trg_journal_entries_balanced
AFTER INSERT OR UPDATE ON public.journal_entries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_posted_journal_balance();

CREATE CONSTRAINT TRIGGER trg_journal_lines_balanced
AFTER INSERT OR UPDATE OR DELETE ON public.journal_lines
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_posted_journal_balance();

CREATE OR REPLACE FUNCTION public.xbos_reject_posted_journal_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $body$
DECLARE
    protected_state VARCHAR(24);
BEGIN
    IF TG_TABLE_NAME = 'journal_entries' THEN
        protected_state := OLD.entry_state;
        IF protected_state IN ('posted','reversed') THEN
            RAISE EXCEPTION USING MESSAGE = 'posted journal entries are immutable; post a correcting entry';
        END IF;
    ELSE
        SELECT entry_state
          INTO protected_state
          FROM public.journal_entries
         WHERE tenant_id = OLD.tenant_id
           AND id = OLD.journal_entry_id;
        IF protected_state IN ('posted','reversed') THEN
            RAISE EXCEPTION USING MESSAGE = 'posted journal lines are immutable; post a correcting entry';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END
$body$;

CREATE TRIGGER trg_journal_entries_immutable
BEFORE UPDATE OR DELETE ON public.journal_entries
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_posted_journal_mutation();

CREATE TRIGGER trg_journal_lines_immutable
BEFORE UPDATE OR DELETE ON public.journal_lines
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_posted_journal_mutation();
