CREATE TABLE public.financial_dimension_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    dimension_code VARCHAR(64) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_financial_dimension_types_public_id UNIQUE (public_id),
    CONSTRAINT uq_financial_dimension_types_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_financial_dimension_types_code UNIQUE (tenant_id, dimension_code),
    CONSTRAINT fk_financial_dimension_types_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_dimension_types_code CHECK (
        dimension_code = lower(btrim(dimension_code))
        AND dimension_code ~ '^[a-z][a-z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_financial_dimension_types_name
        CHECK (length(btrim(display_name)) > 0),
    CONSTRAINT ck_financial_dimension_types_effective
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_financial_dimension_types_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_financial_dimension_types_active
    ON public.financial_dimension_types (tenant_id, active, dimension_code);

CREATE TABLE public.financial_dimension_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    dimension_type_id BIGINT NOT NULL,
    parent_value_id BIGINT NULL,
    value_code VARCHAR(120) NOT NULL,
    display_name VARCHAR(180) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_financial_dimension_values_public_id UNIQUE (public_id),
    CONSTRAINT uq_financial_dimension_values_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_financial_dimension_values_type_id_id
        UNIQUE (tenant_id, dimension_type_id, id),
    CONSTRAINT uq_financial_dimension_values_code
        UNIQUE (tenant_id, dimension_type_id, value_code),
    CONSTRAINT fk_financial_dimension_values_type FOREIGN KEY
        (tenant_id, dimension_type_id)
        REFERENCES public.financial_dimension_types(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_dimension_values_parent FOREIGN KEY
        (tenant_id, dimension_type_id, parent_value_id)
        REFERENCES public.financial_dimension_values(tenant_id, dimension_type_id, id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_financial_dimension_values_code CHECK (
        value_code = btrim(value_code) AND length(value_code) > 0
    ),
    CONSTRAINT ck_financial_dimension_values_name
        CHECK (length(btrim(display_name)) > 0),
    CONSTRAINT ck_financial_dimension_values_parent_not_self
        CHECK (parent_value_id IS NULL OR parent_value_id <> id),
    CONSTRAINT ck_financial_dimension_values_effective
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_financial_dimension_values_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_financial_dimension_values_resolve
    ON public.financial_dimension_values
    (tenant_id, dimension_type_id, value_code, active, effective_from);
CREATE INDEX ix_financial_dimension_values_parent
    ON public.financial_dimension_values (tenant_id, dimension_type_id, parent_value_id);

CREATE TABLE public.posting_dimension_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    legal_entity_unit_id BIGINT NOT NULL,
    posting_profile_code VARCHAR(80) NOT NULL,
    account_role VARCHAR(80) NOT NULL,
    dimension_type_id BIGINT NOT NULL,
    requirement VARCHAR(16) NOT NULL,
    default_dimension_value_id BIGINT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_posting_dimension_policies_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_posting_dimension_policy_identity UNIQUE
        (tenant_id, legal_entity_unit_id, posting_profile_code,
         account_role, dimension_type_id, effective_from),
    CONSTRAINT fk_posting_dimension_policies_entity FOREIGN KEY
        (tenant_id, legal_entity_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_posting_dimension_policies_type FOREIGN KEY
        (tenant_id, dimension_type_id)
        REFERENCES public.financial_dimension_types(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_posting_dimension_policies_default FOREIGN KEY
        (tenant_id, dimension_type_id, default_dimension_value_id)
        REFERENCES public.financial_dimension_values(tenant_id, dimension_type_id, id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_posting_dimension_policies_profile CHECK (
        posting_profile_code = lower(btrim(posting_profile_code))
        AND (posting_profile_code = '*' OR posting_profile_code ~ '^[a-z][a-z0-9_]{0,79}$')
    ),
    CONSTRAINT ck_posting_dimension_policies_role CHECK (
        account_role = lower(btrim(account_role))
        AND (account_role = '*' OR account_role ~ '^[a-z][a-z0-9_]{0,79}$')
    ),
    CONSTRAINT ck_posting_dimension_policies_requirement
        CHECK (requirement IN ('required','optional','forbidden')),
    CONSTRAINT ck_posting_dimension_policies_default CHECK (
        requirement <> 'forbidden' OR default_dimension_value_id IS NULL
    ),
    CONSTRAINT ck_posting_dimension_policies_effective
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_posting_dimension_policies_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE INDEX ix_posting_dimension_policies_resolve
    ON public.posting_dimension_policies
    (tenant_id, legal_entity_unit_id, posting_profile_code,
     account_role, active, effective_from);

ALTER TABLE public.journal_lines
    ADD CONSTRAINT ck_journal_lines_financial_dimensions_object CHECK (
        NOT (dimension_snapshot ? 'financial_dimensions')
        OR jsonb_typeof(dimension_snapshot -> 'financial_dimensions') = 'object'
    );

CREATE OR REPLACE FUNCTION public.xbos_reject_dimension_configuration_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $body$
DECLARE
    old_row JSONB;
    new_row JSONB;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING MESSAGE =
            'financial dimension configuration is historical; deactivate or end-date it';
    END IF;
    old_row := to_jsonb(OLD);
    new_row := to_jsonb(NEW);
    IF old_row ->> 'tenant_id' IS DISTINCT FROM new_row ->> 'tenant_id'
       OR old_row ->> 'id' IS DISTINCT FROM new_row ->> 'id' THEN
        RAISE EXCEPTION USING MESSAGE =
            'financial dimension identity is immutable';
    END IF;
    IF TG_TABLE_NAME = 'financial_dimension_types' AND (
        old_row ->> 'dimension_code' IS DISTINCT FROM new_row ->> 'dimension_code' OR
        old_row ->> 'effective_from' IS DISTINCT FROM new_row ->> 'effective_from'
    ) THEN
        RAISE EXCEPTION USING MESSAGE =
            'financial dimension type identity is immutable';
    END IF;
    IF TG_TABLE_NAME = 'financial_dimension_values' AND (
        old_row ->> 'dimension_type_id' IS DISTINCT FROM new_row ->> 'dimension_type_id' OR
        old_row ->> 'value_code' IS DISTINCT FROM new_row ->> 'value_code' OR
        old_row ->> 'parent_value_id' IS DISTINCT FROM new_row ->> 'parent_value_id' OR
        old_row ->> 'effective_from' IS DISTINCT FROM new_row ->> 'effective_from'
    ) THEN
        RAISE EXCEPTION USING MESSAGE =
            'financial dimension value identity is immutable';
    END IF;
    IF TG_TABLE_NAME = 'posting_dimension_policies' AND (
        old_row ->> 'legal_entity_unit_id' IS DISTINCT FROM new_row ->> 'legal_entity_unit_id' OR
        old_row ->> 'posting_profile_code' IS DISTINCT FROM new_row ->> 'posting_profile_code' OR
        old_row ->> 'account_role' IS DISTINCT FROM new_row ->> 'account_role' OR
        old_row ->> 'dimension_type_id' IS DISTINCT FROM new_row ->> 'dimension_type_id' OR
        old_row ->> 'requirement' IS DISTINCT FROM new_row ->> 'requirement' OR
        old_row ->> 'default_dimension_value_id' IS DISTINCT FROM new_row ->> 'default_dimension_value_id' OR
        old_row ->> 'effective_from' IS DISTINCT FROM new_row ->> 'effective_from'
    ) THEN
        RAISE EXCEPTION USING MESSAGE =
            'posting dimension policy semantics are immutable';
    END IF;
    RETURN NEW;
END
$body$;

CREATE TRIGGER trg_financial_dimension_types_history
BEFORE UPDATE OR DELETE ON public.financial_dimension_types
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_dimension_configuration_mutation();

CREATE TRIGGER trg_financial_dimension_values_history
BEFORE UPDATE OR DELETE ON public.financial_dimension_values
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_dimension_configuration_mutation();

CREATE TRIGGER trg_posting_dimension_policies_history
BEFORE UPDATE OR DELETE ON public.posting_dimension_policies
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_dimension_configuration_mutation();
