CREATE TABLE public.financial_obligations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    debtor_party_id UUID NOT NULL,
    creditor_party_id UUID NOT NULL,
    commercial_transaction_public_id UUID NULL,
    obligation_type VARCHAR(64) NOT NULL,
    obligation_state VARCHAR(32) NOT NULL DEFAULT 'open',
    original_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    due_at TIMESTAMPTZ NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_financial_obligations_public_id UNIQUE (public_id),
    CONSTRAINT uq_financial_obligations_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_financial_obligations_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_financial_obligations_source_identity
        UNIQUE (tenant_id, source_component, source_record_id, obligation_type),
    CONSTRAINT uq_financial_obligations_line_target
        UNIQUE (tenant_id, organization_unit_id, id, currency_code),
    CONSTRAINT uq_financial_obligations_allocation_target
        UNIQUE (tenant_id, id, currency_code),
    CONSTRAINT fk_financial_obligations_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_obligations_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_obligations_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_obligations_actor_user FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_obligations_party_distinct
        CHECK (debtor_party_id <> creditor_party_id),
    CONSTRAINT ck_financial_obligations_amount CHECK (original_amount > 0),
    CONSTRAINT ck_financial_obligations_state CHECK (
        obligation_state IN (
            'open', 'partially_satisfied', 'satisfied', 'cancelled', 'written_off'
        )
    ),
    CONSTRAINT ck_financial_obligations_type
        CHECK (obligation_type ~ '^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT ck_financial_obligations_calendar_version
        CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_financial_obligations_row_version CHECK (row_version > 0),
    CONSTRAINT ck_financial_obligations_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_financial_obligations_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_financial_obligations_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_financial_obligations_party_balance
    ON public.financial_obligations
    (tenant_id, debtor_party_id, currency_code, obligation_state, due_at);
CREATE INDEX ix_financial_obligations_org_business_date
    ON public.financial_obligations
    (tenant_id, organization_unit_id, business_date, id);
CREATE INDEX ix_financial_obligations_correlation
    ON public.financial_obligations (tenant_id, correlation_id);

CREATE TABLE public.financial_obligation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    obligation_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    line_type VARCHAR(64) NOT NULL,
    description_snapshot TEXT NOT NULL,
    quantity NUMERIC(24,8) NOT NULL DEFAULT 1,
    unit_amount NUMERIC(24,8) NOT NULL,
    line_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_financial_obligation_lines_public_id UNIQUE (public_id),
    CONSTRAINT uq_financial_obligation_lines_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_financial_obligation_lines_number
        UNIQUE (tenant_id, obligation_id, line_number),
    CONSTRAINT uq_financial_obligation_lines_source
        UNIQUE (tenant_id, obligation_id, source_component, source_record_id),
    CONSTRAINT fk_financial_obligation_lines_obligation FOREIGN KEY
        (tenant_id, organization_unit_id, obligation_id, currency_code)
        REFERENCES public.financial_obligations
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_financial_obligation_lines_actor_user FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_obligation_lines_number CHECK (line_number > 0),
    CONSTRAINT ck_financial_obligation_lines_type
        CHECK (line_type ~ '^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT ck_financial_obligation_lines_description
        CHECK (length(btrim(description_snapshot)) > 0),
    CONSTRAINT ck_financial_obligation_lines_quantity CHECK (quantity > 0),
    CONSTRAINT ck_financial_obligation_lines_unit_amount CHECK (unit_amount >= 0),
    CONSTRAINT ck_financial_obligation_lines_amount CHECK (line_amount > 0),
    CONSTRAINT ck_financial_obligation_lines_calendar_version
        CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_financial_obligation_lines_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_financial_obligation_lines_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_financial_obligation_lines_obligation
    ON public.financial_obligation_lines (tenant_id, obligation_id, line_number);

CREATE TABLE public.value_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    owner_party_id UUID NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    payment_settlement_public_id UUID NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_value_sources_public_id UNIQUE (public_id),
    CONSTRAINT uq_value_sources_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_value_sources_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_value_sources_source_identity
        UNIQUE (tenant_id, source_component, source_record_id, source_type),
    CONSTRAINT uq_value_sources_settlement
        UNIQUE (tenant_id, payment_settlement_public_id),
    CONSTRAINT uq_value_sources_allocation_source
        UNIQUE (tenant_id, id, currency_code),
    CONSTRAINT fk_value_sources_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_value_sources_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_value_sources_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_value_sources_actor_user FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_value_sources_type
        CHECK (source_type ~ '^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT ck_value_sources_amount CHECK (source_amount > 0),
    CONSTRAINT ck_value_sources_calendar_version CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_value_sources_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_value_sources_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_value_sources_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_value_sources_owner
    ON public.value_sources
    (tenant_id, owner_party_id, currency_code, business_date, id);
CREATE INDEX ix_value_sources_correlation
    ON public.value_sources (tenant_id, correlation_id);

CREATE TABLE public.payment_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    value_source_id BIGINT NOT NULL,
    obligation_id BIGINT NOT NULL,
    allocation_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    cross_organization_policy_code VARCHAR(80) NULL,
    cross_organization_policy_version INTEGER NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_allocations_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_allocations_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_payment_allocations_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_payment_allocations_source_identity
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_payment_allocations_reversal_target
        UNIQUE (tenant_id, organization_unit_id, id, currency_code),
    CONSTRAINT fk_payment_allocations_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_allocations_actor_user FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_allocations_value_source FOREIGN KEY
        (tenant_id, value_source_id, currency_code)
        REFERENCES public.value_sources
        (tenant_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_allocations_obligation FOREIGN KEY
        (tenant_id, obligation_id, currency_code)
        REFERENCES public.financial_obligations
        (tenant_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_allocations_amount CHECK (allocation_amount > 0),
    CONSTRAINT ck_payment_allocations_calendar_version
        CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_payment_allocations_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_payment_allocations_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_payment_allocations_cross_org_policy CHECK (
        (cross_organization_policy_code IS NULL
         AND cross_organization_policy_version IS NULL)
        OR
        (length(btrim(cross_organization_policy_code)) > 0
         AND cross_organization_policy_version > 0)
    ),
    CONSTRAINT ck_payment_allocations_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_payment_allocations_obligation
    ON public.payment_allocations
    (tenant_id, obligation_id, occurred_at, id);
CREATE INDEX ix_payment_allocations_value_source
    ON public.payment_allocations
    (tenant_id, value_source_id, occurred_at, id);

CREATE TABLE public.allocation_reversals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_allocation_id BIGINT NOT NULL,
    reversal_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_allocation_reversals_public_id UNIQUE (public_id),
    CONSTRAINT uq_allocation_reversals_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_allocation_reversals_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_allocation_reversals_source_identity
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT fk_allocation_reversals_allocation FOREIGN KEY
        (tenant_id, organization_unit_id, payment_allocation_id, currency_code)
        REFERENCES public.payment_allocations
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_allocation_reversals_actor_user FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_allocation_reversals_amount CHECK (reversal_amount > 0),
    CONSTRAINT ck_allocation_reversals_reason
        CHECK (reason_code ~ '^[a-z][a-z0-9_]{0,79}$'),
    CONSTRAINT ck_allocation_reversals_calendar_version
        CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_allocation_reversals_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_allocation_reversals_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_allocation_reversals_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_allocation_reversals_allocation
    ON public.allocation_reversals
    (tenant_id, payment_allocation_id, occurred_at, id);

CREATE OR REPLACE FUNCTION public.xbos_reject_obligation_fact_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $body$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '55000',
        MESSAGE = TG_TABLE_NAME || ' is immutable; append a compensating fact instead';
END
$body$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_allocation_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $body$
DECLARE
    source_org_id BIGINT;
    obligation_org_id BIGINT;
BEGIN
    SELECT organization_unit_id INTO source_org_id
    FROM public.value_sources
    WHERE tenant_id = NEW.tenant_id AND id = NEW.value_source_id;

    SELECT organization_unit_id INTO obligation_org_id
    FROM public.financial_obligations
    WHERE tenant_id = NEW.tenant_id AND id = NEW.obligation_id;

    IF obligation_org_id IS NOT NULL
       AND NEW.organization_unit_id <> obligation_org_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'allocation organization must be the obligation organization';
    END IF;

    IF source_org_id IS NOT NULL AND obligation_org_id IS NOT NULL THEN
        IF source_org_id <> obligation_org_id
           AND NEW.cross_organization_policy_code IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                MESSAGE = 'cross-organization allocation requires explicit policy';
        END IF;
        IF source_org_id = obligation_org_id
           AND NEW.cross_organization_policy_code IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                MESSAGE = 'cross-organization policy is invalid for same-organization allocation';
        END IF;
    END IF;
    RETURN NEW;
END
$body$;

CREATE OR REPLACE FUNCTION public.xbos_protect_financial_obligation_authority()
RETURNS trigger
LANGUAGE plpgsql
AS $body$
BEGIN
    IF OLD.public_id IS DISTINCT FROM NEW.public_id
       OR OLD.tenant_id IS DISTINCT FROM NEW.tenant_id
       OR OLD.organization_unit_id IS DISTINCT FROM NEW.organization_unit_id
       OR OLD.debtor_party_id IS DISTINCT FROM NEW.debtor_party_id
       OR OLD.creditor_party_id IS DISTINCT FROM NEW.creditor_party_id
       OR OLD.commercial_transaction_public_id IS DISTINCT FROM NEW.commercial_transaction_public_id
       OR OLD.obligation_type IS DISTINCT FROM NEW.obligation_type
       OR OLD.original_amount IS DISTINCT FROM NEW.original_amount
       OR OLD.currency_code IS DISTINCT FROM NEW.currency_code
       OR OLD.due_at IS DISTINCT FROM NEW.due_at
       OR OLD.occurred_at IS DISTINCT FROM NEW.occurred_at
       OR OLD.recorded_at IS DISTINCT FROM NEW.recorded_at
       OR OLD.business_date IS DISTINCT FROM NEW.business_date
       OR OLD.calendar_policy_version IS DISTINCT FROM NEW.calendar_policy_version
       OR OLD.correlation_id IS DISTINCT FROM NEW.correlation_id
       OR OLD.actor_user_id IS DISTINCT FROM NEW.actor_user_id
       OR OLD.actor_service IS DISTINCT FROM NEW.actor_service
       OR OLD.source_component IS DISTINCT FROM NEW.source_component
       OR OLD.source_record_id IS DISTINCT FROM NEW.source_record_id
       OR OLD.idempotency_scope IS DISTINCT FROM NEW.idempotency_scope
       OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
       OR OLD.request_fingerprint IS DISTINCT FROM NEW.request_fingerprint
       OR OLD.metadata IS DISTINCT FROM NEW.metadata THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'financial obligation authority is immutable';
    END IF;
    IF NEW.row_version <> OLD.row_version + 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'financial obligation state change requires one row-version increment';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END
$body$;

CREATE TRIGGER trg_financial_obligations_protect_authority
BEFORE UPDATE ON public.financial_obligations
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_financial_obligation_authority();

CREATE TRIGGER trg_financial_obligations_no_delete
BEFORE DELETE ON public.financial_obligations
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();

CREATE TRIGGER trg_financial_obligation_lines_immutable
BEFORE UPDATE OR DELETE ON public.financial_obligation_lines
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();

CREATE TRIGGER trg_value_sources_immutable
BEFORE UPDATE OR DELETE ON public.value_sources
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();

CREATE TRIGGER trg_payment_allocations_immutable
BEFORE UPDATE OR DELETE ON public.payment_allocations
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();

CREATE TRIGGER trg_payment_allocations_validate_scope
BEFORE INSERT ON public.payment_allocations
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_allocation_scope();

CREATE TRIGGER trg_allocation_reversals_immutable
BEFORE UPDATE OR DELETE ON public.allocation_reversals
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();
