CREATE TABLE public.allocation_scope_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    policy_code VARCHAR(80) NOT NULL,
    policy_version INTEGER NOT NULL,
    source_organization_unit_id BIGINT NOT NULL,
    target_organization_unit_id BIGINT NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    effective_from DATE NOT NULL,
    effective_through DATE NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_allocation_scope_policy UNIQUE (tenant_id, policy_code, policy_version),
    CONSTRAINT fk_allocation_scope_policy_source_org FOREIGN KEY (tenant_id, source_organization_unit_id)
      REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_allocation_scope_policy_target_org FOREIGN KEY (tenant_id, target_organization_unit_id)
      REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_allocation_scope_policy_currency FOREIGN KEY (currency_code)
      REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT ck_allocation_scope_policy_code CHECK (policy_code ~ '^[a-z][a-z0-9_]{0,79}$'),
    CONSTRAINT ck_allocation_scope_policy_version CHECK (policy_version > 0),
    CONSTRAINT ck_allocation_scope_policy_distinct_org CHECK (source_organization_unit_id <> target_organization_unit_id),
    CONSTRAINT ck_allocation_scope_policy_dates CHECK (effective_through IS NULL OR effective_through >= effective_from),
    CONSTRAINT ck_allocation_scope_policy_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_allocation_scope_policy_lookup ON public.allocation_scope_policies
  (tenant_id, source_organization_unit_id, target_organization_unit_id, currency_code, active);

CREATE TRIGGER trg_allocation_scope_policies_immutable
BEFORE UPDATE OR DELETE ON public.allocation_scope_policies
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_allocation_scope()
RETURNS trigger LANGUAGE plpgsql AS $body$
DECLARE
    source_row public.value_sources%%ROWTYPE;
    obligation_row public.financial_obligations%%ROWTYPE;
    active_source NUMERIC(24,8);
    active_obligation NUMERIC(24,8);
BEGIN
    SELECT * INTO source_row FROM public.value_sources
      WHERE tenant_id=NEW.tenant_id AND id=NEW.value_source_id FOR UPDATE;
    SELECT * INTO obligation_row FROM public.financial_obligations
      WHERE tenant_id=NEW.tenant_id AND id=NEW.obligation_id FOR UPDATE;

    IF source_row.id IS NULL OR obligation_row.id IS NULL THEN
      RAISE EXCEPTION USING ERRCODE='23503', MESSAGE='allocation source or obligation is absent';
    END IF;
    IF NEW.organization_unit_id <> obligation_row.organization_unit_id THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='allocation organization must be the obligation organization';
    END IF;
    IF obligation_row.obligation_state IN ('cancelled','written_off') THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='terminal obligation cannot accept allocation';
    END IF;
    IF NEW.currency_code <> source_row.currency_code OR NEW.currency_code <> obligation_row.currency_code THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='allocation currency must match source and obligation';
    END IF;

    IF source_row.organization_unit_id = obligation_row.organization_unit_id THEN
      IF NEW.cross_organization_policy_code IS NOT NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='cross-organization policy is invalid for same-organization allocation';
      END IF;
    ELSE
      IF NOT EXISTS (
        SELECT 1 FROM public.allocation_scope_policies p
        WHERE p.tenant_id=NEW.tenant_id
          AND p.policy_code=NEW.cross_organization_policy_code
          AND p.policy_version=NEW.cross_organization_policy_version
          AND p.source_organization_unit_id=source_row.organization_unit_id
          AND p.target_organization_unit_id=obligation_row.organization_unit_id
          AND p.currency_code=NEW.currency_code AND p.active
          AND p.effective_from <= NEW.business_date
          AND (p.effective_through IS NULL OR p.effective_through >= NEW.business_date)
      ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='cross-organization allocation policy is not authoritative';
      END IF;
    END IF;

    SELECT source_row.source_amount - COALESCE(SUM(pa.allocation_amount - COALESCE(ar.reversed,0)),0)
      INTO active_source
    FROM public.payment_allocations pa
    LEFT JOIN (SELECT tenant_id,payment_allocation_id,SUM(reversal_amount) reversed
               FROM public.allocation_reversals GROUP BY tenant_id,payment_allocation_id) ar
      ON ar.tenant_id=pa.tenant_id AND ar.payment_allocation_id=pa.id
    WHERE pa.tenant_id=NEW.tenant_id AND pa.value_source_id=NEW.value_source_id;

    SELECT obligation_row.original_amount - COALESCE(SUM(pa.allocation_amount - COALESCE(ar.reversed,0)),0)
      INTO active_obligation
    FROM public.payment_allocations pa
    LEFT JOIN (SELECT tenant_id,payment_allocation_id,SUM(reversal_amount) reversed
               FROM public.allocation_reversals GROUP BY tenant_id,payment_allocation_id) ar
      ON ar.tenant_id=pa.tenant_id AND ar.payment_allocation_id=pa.id
    WHERE pa.tenant_id=NEW.tenant_id AND pa.obligation_id=NEW.obligation_id;

    IF NEW.allocation_amount > active_source THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='allocation exceeds value-source capacity';
    END IF;
    IF NEW.allocation_amount > active_obligation THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='allocation exceeds obligation capacity';
    END IF;
    RETURN NEW;
END
$body$;

CREATE OR REPLACE FUNCTION public.xbos_validate_allocation_reversal_capacity()
RETURNS trigger LANGUAGE plpgsql AS $body$
DECLARE
    allocation_row public.payment_allocations%%ROWTYPE;
    source_public_id UUID;
    obligation_public_id UUID;
    already_reversed NUMERIC(24,8);
BEGIN
    SELECT * INTO allocation_row FROM public.payment_allocations
      WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_allocation_id;

    IF allocation_row.id IS NULL THEN
      RAISE EXCEPTION USING ERRCODE='23503', MESSAGE='reversal allocation is absent';
    END IF;
    SELECT public_id INTO source_public_id FROM public.value_sources
      WHERE tenant_id=NEW.tenant_id AND id=allocation_row.value_source_id;
    SELECT public_id INTO obligation_public_id FROM public.financial_obligations
      WHERE tenant_id=NEW.tenant_id AND id=allocation_row.obligation_id;
    PERFORM 1 FROM public.value_sources WHERE tenant_id=NEW.tenant_id AND public_id=source_public_id FOR UPDATE;
    PERFORM 1 FROM public.financial_obligations WHERE tenant_id=NEW.tenant_id AND public_id=obligation_public_id FOR UPDATE;
    PERFORM 1 FROM public.payment_allocations WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_allocation_id FOR UPDATE;

    SELECT COALESCE(SUM(reversal_amount),0) INTO already_reversed
      FROM public.allocation_reversals
      WHERE tenant_id=NEW.tenant_id AND payment_allocation_id=NEW.payment_allocation_id;
    IF already_reversed + NEW.reversal_amount > allocation_row.allocation_amount THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='reversal exceeds active allocation capacity';
    END IF;
    RETURN NEW;
END
$body$;

DROP TRIGGER trg_payment_allocations_validate_scope ON public.payment_allocations;
CREATE TRIGGER trg_payment_allocations_validate_scope
BEFORE INSERT ON public.payment_allocations
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_allocation_scope();

CREATE TRIGGER trg_allocation_reversals_validate_capacity
BEFORE INSERT ON public.allocation_reversals
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_allocation_reversal_capacity();
