CREATE TABLE public.obligation_state_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    obligation_id BIGINT NOT NULL,
    from_state VARCHAR(32) NULL,
    to_state VARCHAR(32) NOT NULL,
    transition_kind VARCHAR(40) NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_obligation_state_transition_obligation FOREIGN KEY (tenant_id,obligation_id)
      REFERENCES public.financial_obligations(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_obligation_state_transition_from CHECK (from_state IS NULL OR from_state IN ('open','partially_satisfied','satisfied','cancelled','written_off')),
    CONSTRAINT ck_obligation_state_transition_to CHECK (to_state IN ('open','partially_satisfied','satisfied','cancelled','written_off')),
    CONSTRAINT ck_obligation_state_transition_kind CHECK (transition_kind IN ('created','baseline_adoption','satisfaction_projection','manual_terminal')),
    CONSTRAINT ck_obligation_state_transition_distinct CHECK (from_state IS NULL OR from_state <> to_state),
    CONSTRAINT ck_obligation_state_transition_metadata CHECK (jsonb_typeof(metadata)='object')
);

CREATE INDEX ix_obligation_state_transitions_as_of
  ON public.obligation_state_transitions(tenant_id,obligation_id,effective_at DESC,id DESC);

INSERT INTO public.obligation_state_transitions
  (tenant_id,obligation_id,from_state,to_state,transition_kind,effective_at,correlation_id,actor_user_id,actor_service,recorded_at)
SELECT tenant_id,id,NULL,obligation_state,'baseline_adoption',recorded_at,correlation_id,actor_user_id,actor_service,recorded_at
FROM public.financial_obligations;

CREATE OR REPLACE FUNCTION public.xbos_record_obligation_state_transition()
RETURNS trigger LANGUAGE plpgsql AS $body$
DECLARE selected_kind VARCHAR(40);
BEGIN
  IF TG_OP='INSERT' THEN
    INSERT INTO public.obligation_state_transitions
      (tenant_id,obligation_id,from_state,to_state,transition_kind,effective_at,correlation_id,actor_user_id,actor_service)
    VALUES (NEW.tenant_id,NEW.id,NULL,NEW.obligation_state,'created',NEW.occurred_at,NEW.correlation_id,NEW.actor_user_id,NEW.actor_service);
  ELSIF OLD.obligation_state IS DISTINCT FROM NEW.obligation_state THEN
    selected_kind := CASE WHEN NEW.obligation_state IN ('cancelled','written_off') THEN 'manual_terminal' ELSE 'satisfaction_projection' END;
    INSERT INTO public.obligation_state_transitions
      (tenant_id,obligation_id,from_state,to_state,transition_kind,effective_at,correlation_id,actor_user_id,actor_service)
    VALUES (NEW.tenant_id,NEW.id,OLD.obligation_state,NEW.obligation_state,selected_kind,statement_timestamp(),NEW.correlation_id,NEW.actor_user_id,NEW.actor_service);
  END IF;
  RETURN NEW;
END
$body$;

CREATE TRIGGER trg_obligation_state_transition_insert
AFTER INSERT ON public.financial_obligations
FOR EACH ROW EXECUTE FUNCTION public.xbos_record_obligation_state_transition();

CREATE TRIGGER trg_obligation_state_transition_update
AFTER UPDATE OF obligation_state ON public.financial_obligations
FOR EACH ROW EXECUTE FUNCTION public.xbos_record_obligation_state_transition();

CREATE TRIGGER trg_obligation_state_transitions_immutable
BEFORE UPDATE OR DELETE ON public.obligation_state_transitions
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_obligation_fact_mutation();
