ALTER TABLE public.operational_financial_accounts
    ADD CONSTRAINT uq_operational_financial_accounts_settlement_target
    UNIQUE (tenant_id, id, currency_code);

CREATE TABLE public.canonical_payment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payer_party_id UUID NULL,
    request_state VARCHAR(32) NOT NULL DEFAULT 'open',
    purpose_code VARCHAR(80) NOT NULL,
    requested_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_canonical_payment_requests_public_id UNIQUE (public_id),
    CONSTRAINT uq_canonical_payment_requests_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_canonical_payment_requests_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_canonical_payment_requests_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_canonical_payment_requests_intent_target
        UNIQUE (tenant_id, organization_unit_id, id, currency_code),
    CONSTRAINT fk_canonical_payment_requests_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_requests_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_requests_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_requests_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_canonical_payment_requests_state CHECK (
        request_state IN ('draft','open','partially_satisfied','satisfied','cancelled','expired')
    ),
    CONSTRAINT ck_canonical_payment_requests_purpose
        CHECK (purpose_code ~ '^[a-z][a-z0-9_.-]{0,79}$'),
    CONSTRAINT ck_canonical_payment_requests_amount CHECK (requested_amount > 0),
    CONSTRAINT ck_canonical_payment_requests_expiry
        CHECK (expires_at IS NULL OR expires_at > occurred_at),
    CONSTRAINT ck_canonical_payment_requests_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_canonical_payment_requests_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_canonical_payment_requests_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_canonical_payment_requests_version CHECK (row_version > 0),
    CONSTRAINT ck_canonical_payment_requests_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_canonical_payment_requests_party_state
    ON public.canonical_payment_requests
    (tenant_id, payer_party_id, request_state, business_date, id);

CREATE TABLE public.canonical_payment_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_request_id BIGINT NULL,
    financial_obligation_public_id UUID NULL,
    intent_state VARCHAR(32) NOT NULL DEFAULT 'pending',
    requested_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    payment_method_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    expires_at TIMESTAMPTZ NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_canonical_payment_intents_public_id UNIQUE (public_id),
    CONSTRAINT uq_canonical_payment_intents_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_canonical_payment_intents_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_canonical_payment_intents_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_canonical_payment_intents_child_target
        UNIQUE (tenant_id, organization_unit_id, id, currency_code),
    CONSTRAINT fk_canonical_payment_intents_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_intents_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_intents_request FOREIGN KEY
        (tenant_id, organization_unit_id, payment_request_id, currency_code)
        REFERENCES public.canonical_payment_requests
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_intents_obligation FOREIGN KEY
        (financial_obligation_public_id)
        REFERENCES public.financial_obligations(public_id) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_intents_currency FOREIGN KEY (currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_intents_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_canonical_payment_intents_state CHECK (
        intent_state IN (
            'pending','processing','partially_succeeded','succeeded','failed','cancelled','expired'
        )
    ),
    CONSTRAINT ck_canonical_payment_intents_amount CHECK (requested_amount > 0),
    CONSTRAINT ck_canonical_payment_intents_method_policy
        CHECK (jsonb_typeof(payment_method_policy) = 'object'),
    CONSTRAINT ck_canonical_payment_intents_expiry
        CHECK (expires_at IS NULL OR expires_at > occurred_at),
    CONSTRAINT ck_canonical_payment_intents_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_canonical_payment_intents_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_canonical_payment_intents_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_canonical_payment_intents_version CHECK (row_version > 0),
    CONSTRAINT ck_canonical_payment_intents_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_canonical_payment_intents_state
    ON public.canonical_payment_intents
    (tenant_id, organization_unit_id, intent_state, business_date, id);
CREATE INDEX ix_canonical_payment_intents_obligation
    ON public.canonical_payment_intents (tenant_id, financial_obligation_public_id)
    WHERE financial_obligation_public_id IS NOT NULL;

CREATE TABLE public.canonical_payment_tenders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_intent_id BIGINT NOT NULL,
    tender_number INTEGER NOT NULL,
    tender_state VARCHAR(24) NOT NULL DEFAULT 'pending',
    tender_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    payment_method_code VARCHAR(64) NOT NULL,
    instrument_reference VARCHAR(255) NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_canonical_payment_tenders_public_id UNIQUE (public_id),
    CONSTRAINT uq_canonical_payment_tenders_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_canonical_payment_tenders_number
        UNIQUE (tenant_id, payment_intent_id, tender_number),
    CONSTRAINT uq_canonical_payment_tenders_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_canonical_payment_tenders_attempt_target
        UNIQUE (tenant_id, organization_unit_id, payment_intent_id, id, currency_code),
    CONSTRAINT fk_canonical_payment_tenders_intent FOREIGN KEY
        (tenant_id, organization_unit_id, payment_intent_id, currency_code)
        REFERENCES public.canonical_payment_intents
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_tenders_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_canonical_payment_tenders_number CHECK (tender_number > 0),
    CONSTRAINT ck_canonical_payment_tenders_state CHECK (
        tender_state IN ('pending','processing','partially_succeeded','succeeded','failed','cancelled')
    ),
    CONSTRAINT ck_canonical_payment_tenders_amount CHECK (tender_amount > 0),
    CONSTRAINT ck_canonical_payment_tenders_method
        CHECK (payment_method_code ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT ck_canonical_payment_tenders_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_canonical_payment_tenders_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_canonical_payment_tenders_version CHECK (row_version > 0),
    CONSTRAINT ck_canonical_payment_tenders_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_canonical_payment_tenders_intent
    ON public.canonical_payment_tenders (tenant_id, payment_intent_id, tender_number);

CREATE TABLE public.canonical_payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_intent_id BIGINT NOT NULL,
    payment_tender_id BIGINT NULL,
    provider_account_id BIGINT NULL,
    attempt_state VARCHAR(32) NOT NULL DEFAULT 'pending',
    attempted_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    payment_method_code VARCHAR(64) NOT NULL,
    payment_rail_code VARCHAR(64) NOT NULL,
    orchestrator_code VARCHAR(64) NOT NULL,
    underlying_provider_code VARCHAR(64) NULL,
    external_attempt_reference VARCHAR(255) NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_canonical_payment_attempts_public_id UNIQUE (public_id),
    CONSTRAINT uq_canonical_payment_attempts_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_canonical_payment_attempts_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_canonical_payment_attempts_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_canonical_payment_attempts_provider_reference
        UNIQUE (provider_account_id, external_attempt_reference),
    CONSTRAINT uq_canonical_payment_attempts_evidence_target
        UNIQUE (tenant_id, organization_unit_id, id, currency_code),
    CONSTRAINT uq_canonical_payment_attempts_callback_target
        UNIQUE (tenant_id, organization_unit_id, id),
    CONSTRAINT fk_canonical_payment_attempts_intent FOREIGN KEY
        (tenant_id, organization_unit_id, payment_intent_id, currency_code)
        REFERENCES public.canonical_payment_intents
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_attempts_tender FOREIGN KEY
        (tenant_id, organization_unit_id, payment_intent_id, payment_tender_id, currency_code)
        REFERENCES public.canonical_payment_tenders
        (tenant_id, organization_unit_id, payment_intent_id, id, currency_code)
        ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_attempts_provider_account FOREIGN KEY
        (tenant_id, provider_account_id)
        REFERENCES public.payment_provider_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_canonical_payment_attempts_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_canonical_payment_attempts_state CHECK (
        attempt_state IN (
            'pending','processing','requires_action','authorized','succeeded','failed','cancelled','expired'
        )
    ),
    CONSTRAINT ck_canonical_payment_attempts_amount CHECK (attempted_amount > 0),
    CONSTRAINT ck_canonical_payment_attempts_method
        CHECK (payment_method_code ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT ck_canonical_payment_attempts_rail
        CHECK (payment_rail_code ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT ck_canonical_payment_attempts_orchestrator
        CHECK (orchestrator_code ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT ck_canonical_payment_attempts_provider_pair CHECK (
        (provider_account_id IS NULL AND underlying_provider_code IS NULL)
        OR provider_account_id IS NOT NULL
    ),
    CONSTRAINT ck_canonical_payment_attempts_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_canonical_payment_attempts_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_canonical_payment_attempts_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_canonical_payment_attempts_version CHECK (row_version > 0),
    CONSTRAINT ck_canonical_payment_attempts_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_canonical_payment_attempts_intent_state
    ON public.canonical_payment_attempts
    (tenant_id, payment_intent_id, attempt_state, occurred_at, id);
CREATE INDEX ix_canonical_payment_attempts_provider
    ON public.canonical_payment_attempts
    (tenant_id, provider_account_id, attempt_state, occurred_at, id)
    WHERE provider_account_id IS NOT NULL;

CREATE TABLE public.provider_callback_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    provider_account_id BIGINT NOT NULL,
    payment_attempt_id BIGINT NULL,
    provider_event_reference VARCHAR(255) NOT NULL,
    event_type_code VARCHAR(120) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    signature_status VARCHAR(24) NOT NULL,
    processing_state VARCHAR(24) NOT NULL DEFAULT 'received',
    evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_provider_callback_events_public_id UNIQUE (public_id),
    CONSTRAINT uq_provider_callback_events_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_provider_callback_events_provider_event
        UNIQUE (tenant_id, provider_account_id, provider_event_reference),
    CONSTRAINT uq_provider_callback_events_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_provider_callback_events_settlement_target
        UNIQUE (tenant_id, organization_unit_id, id),
    CONSTRAINT fk_provider_callback_events_org FOREIGN KEY
        (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_callback_events_provider FOREIGN KEY
        (tenant_id, provider_account_id)
        REFERENCES public.payment_provider_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_callback_events_attempt FOREIGN KEY
        (tenant_id, organization_unit_id, payment_attempt_id)
        REFERENCES public.canonical_payment_attempts(tenant_id, organization_unit_id, id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_provider_callback_events_reference
        CHECK (length(btrim(provider_event_reference)) > 0),
    CONSTRAINT ck_provider_callback_events_type
        CHECK (length(btrim(event_type_code)) > 0),
    CONSTRAINT ck_provider_callback_events_hash
        CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_provider_callback_events_signature CHECK (
        signature_status IN ('unverified','verified','rejected','not_applicable')
    ),
    CONSTRAINT ck_provider_callback_events_processing CHECK (
        processing_state IN ('received','authenticated','rejected','routed','processed','ignored')
    ),
    CONSTRAINT ck_provider_callback_events_evidence
        CHECK (jsonb_typeof(evidence_payload) = 'object'),
    CONSTRAINT ck_provider_callback_events_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_provider_callback_events_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_provider_callback_events_processing
    ON public.provider_callback_events
    (tenant_id, processing_state, received_at, id);

CREATE TABLE public.payment_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_intent_id BIGINT NOT NULL,
    payment_attempt_id BIGINT NULL,
    provider_callback_event_id BIGINT NULL,
    operational_account_id BIGINT NOT NULL,
    settlement_state VARCHAR(32) NOT NULL DEFAULT 'pending',
    settlement_direction VARCHAR(16) NOT NULL DEFAULT 'incoming',
    gross_amount NUMERIC(24,8) NOT NULL,
    fee_amount NUMERIC(24,8) NOT NULL DEFAULT 0,
    net_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    payment_method_code VARCHAR(64) NOT NULL,
    payment_rail_code VARCHAR(64) NOT NULL,
    finality_status VARCHAR(24) NOT NULL,
    availability_state VARCHAR(24) NOT NULL DEFAULT 'pending',
    external_settlement_reference VARCHAR(255) NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_settlements_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_settlements_tenant_public_id UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_payment_settlements_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_payment_settlements_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_payment_settlements_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT uq_payment_settlements_external
        UNIQUE (tenant_id, operational_account_id, external_settlement_reference),
    CONSTRAINT uq_payment_settlements_reversal_target
        UNIQUE (tenant_id, organization_unit_id, id, currency_code),
    CONSTRAINT fk_payment_settlements_intent FOREIGN KEY
        (tenant_id, organization_unit_id, payment_intent_id, currency_code)
        REFERENCES public.canonical_payment_intents
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_settlements_attempt FOREIGN KEY
        (tenant_id, organization_unit_id, payment_attempt_id, currency_code)
        REFERENCES public.canonical_payment_attempts
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_settlements_callback FOREIGN KEY
        (tenant_id, organization_unit_id, provider_callback_event_id)
        REFERENCES public.provider_callback_events
        (tenant_id, organization_unit_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_settlements_operational_account FOREIGN KEY
        (tenant_id, operational_account_id, currency_code)
        REFERENCES public.operational_financial_accounts
        (tenant_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_settlements_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_settlements_state CHECK (
        settlement_state IN ('pending','confirmed','failed','partially_reversed','reversed')
    ),
    CONSTRAINT ck_payment_settlements_direction
        CHECK (settlement_direction IN ('incoming','outgoing')),
    CONSTRAINT ck_payment_settlements_amounts CHECK (
        gross_amount > 0 AND fee_amount >= 0 AND net_amount >= 0
        AND net_amount = gross_amount - fee_amount
    ),
    CONSTRAINT ck_payment_settlements_method
        CHECK (payment_method_code ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT ck_payment_settlements_rail
        CHECK (payment_rail_code ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT ck_payment_settlements_finality
        CHECK (finality_status IN ('unverified','provisional','final','rejected','not_applicable')),
    CONSTRAINT ck_payment_settlements_availability
        CHECK (availability_state IN ('pending','available','reserved','released','unavailable')),
    CONSTRAINT ck_payment_settlements_external_evidence CHECK (
        finality_status <> 'final'
        OR payment_rail_code IN ('cash','internal_credit')
        OR provider_callback_event_id IS NOT NULL
    ),
    CONSTRAINT ck_payment_settlements_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_payment_settlements_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_payment_settlements_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_payment_settlements_version CHECK (row_version > 0),
    CONSTRAINT ck_payment_settlements_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_payment_settlements_state
    ON public.payment_settlements
    (tenant_id, organization_unit_id, settlement_state, business_date, id);
CREATE INDEX ix_payment_settlements_account
    ON public.payment_settlements
    (tenant_id, operational_account_id, currency_code, availability_state, occurred_at, id);

CREATE TABLE public.payment_settlement_reversals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_settlement_id BIGINT NOT NULL,
    reversal_amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_settlement_reversals_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_settlement_reversals_scope_key
        UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT uq_payment_settlement_reversals_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT fk_payment_settlement_reversals_settlement FOREIGN KEY
        (tenant_id, organization_unit_id, payment_settlement_id, currency_code)
        REFERENCES public.payment_settlements
        (tenant_id, organization_unit_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_settlement_reversals_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_settlement_reversals_amount CHECK (reversal_amount > 0),
    CONSTRAINT ck_payment_settlement_reversals_reason
        CHECK (reason_code ~ '^[a-z][a-z0-9_.-]{0,79}$'),
    CONSTRAINT ck_payment_settlement_reversals_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_payment_settlement_reversals_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_payment_settlement_reversals_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_payment_settlement_reversals_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_payment_settlement_reversals_settlement
    ON public.payment_settlement_reversals
    (tenant_id, payment_settlement_id, occurred_at, id);

ALTER TABLE public.value_sources
    ADD CONSTRAINT fk_value_sources_payment_settlement FOREIGN KEY
    (tenant_id, payment_settlement_public_id)
    REFERENCES public.payment_settlements(tenant_id, public_id) ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION public.xbos_reject_immutable_payment_evidence()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '%% is immutable; append a compensating fact instead', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_provider_callback_events_immutable
    BEFORE UPDATE OR DELETE ON public.provider_callback_events
    FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();

CREATE TRIGGER trg_payment_settlement_reversals_immutable
    BEFORE UPDATE OR DELETE ON public.payment_settlement_reversals
    FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();
