ALTER TABLE public.canonical_payment_attempts
    ADD COLUMN retry_of_attempt_id BIGINT NULL,
    ADD COLUMN timeout_at TIMESTAMPTZ NULL,
    ADD COLUMN terminal_at TIMESTAMPTZ NULL,
    ADD COLUMN failure_code VARCHAR(120) NULL;

ALTER TABLE public.canonical_payment_attempts
    ADD CONSTRAINT fk_canonical_payment_attempts_retry
        FOREIGN KEY (tenant_id, retry_of_attempt_id)
        REFERENCES public.canonical_payment_attempts(tenant_id, id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_canonical_payment_attempts_timeout
        CHECK (timeout_at IS NULL OR timeout_at > occurred_at),
    ADD CONSTRAINT ck_canonical_payment_attempts_terminal
        CHECK (
            (attempt_state IN ('succeeded','failed','cancelled','expired')) = (terminal_at IS NOT NULL)
        ),
    ADD CONSTRAINT ck_canonical_payment_attempts_failure
        CHECK (
            (attempt_state = 'failed' AND failure_code IS NOT NULL AND length(btrim(failure_code)) > 0)
            OR (attempt_state <> 'failed' AND failure_code IS NULL)
        );

CREATE INDEX ix_canonical_payment_attempts_retry
    ON public.canonical_payment_attempts (tenant_id, retry_of_attempt_id)
    WHERE retry_of_attempt_id IS NOT NULL;

CREATE UNIQUE INDEX uq_canonical_payment_attempts_unbound_external
    ON public.canonical_payment_attempts
    (tenant_id, orchestrator_code, external_attempt_reference)
    WHERE provider_account_id IS NULL AND external_attempt_reference IS NOT NULL;

CREATE TABLE public.canonical_payment_attempt_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_attempt_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    from_state VARCHAR(32) NULL,
    to_state VARCHAR(32) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    failure_code VARCHAR(120) NULL,
    external_attempt_reference_snapshot VARCHAR(255) NULL,
    evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_attempt_transitions_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_attempt_transitions_sequence
        UNIQUE (tenant_id, payment_attempt_id, sequence_number),
    CONSTRAINT uq_payment_attempt_transitions_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT fk_payment_attempt_transitions_attempt FOREIGN KEY
        (tenant_id, organization_unit_id, payment_attempt_id)
        REFERENCES public.canonical_payment_attempts
        (tenant_id, organization_unit_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_attempt_transitions_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_attempt_transitions_sequence CHECK (sequence_number > 0),
    CONSTRAINT ck_payment_attempt_transitions_from CHECK (
        from_state IS NULL OR from_state IN (
            'pending','processing','requires_action','authorized',
            'succeeded','failed','cancelled','expired'
        )
    ),
    CONSTRAINT ck_payment_attempt_transitions_to CHECK (
        to_state IN (
            'pending','processing','requires_action','authorized',
            'succeeded','failed','cancelled','expired'
        )
    ),
    CONSTRAINT ck_payment_attempt_transitions_reason
        CHECK (reason_code ~ '^[a-z][a-z0-9_.-]{0,79}$'),
    CONSTRAINT ck_payment_attempt_transitions_failure CHECK (
        (to_state = 'failed' AND failure_code IS NOT NULL AND length(btrim(failure_code)) > 0)
        OR (to_state <> 'failed' AND failure_code IS NULL)
    ),
    CONSTRAINT ck_payment_attempt_transitions_evidence
        CHECK (jsonb_typeof(evidence_payload) = 'object'),
    CONSTRAINT ck_payment_attempt_transitions_calendar
        CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_payment_attempt_transitions_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_payment_attempt_transitions_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_payment_attempt_transitions_history
    ON public.canonical_payment_attempt_transitions
    (tenant_id, payment_attempt_id, sequence_number);

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_attempt_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    prior public.canonical_payment_attempts;
BEGIN
    IF NEW.retry_of_attempt_id IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT * INTO prior
    FROM public.canonical_payment_attempts
    WHERE tenant_id = NEW.tenant_id AND id = NEW.retry_of_attempt_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING MESSAGE = 'retry attempt authority does not exist';
    END IF;
    IF prior.id = NEW.id
       OR prior.payment_intent_id <> NEW.payment_intent_id
       OR prior.organization_unit_id <> NEW.organization_unit_id
       OR prior.currency_code <> NEW.currency_code
       OR prior.attempt_state NOT IN ('failed','cancelled','expired') THEN
        RAISE EXCEPTION USING MESSAGE = 'retry must follow a terminal unsuccessful attempt for the same intent';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_attempt_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    attempt public.canonical_payment_attempts;
    expected_sequence INTEGER;
BEGIN
    SELECT * INTO attempt
    FROM public.canonical_payment_attempts
    WHERE tenant_id = NEW.tenant_id AND id = NEW.payment_attempt_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt transition target does not exist';
    END IF;
    SELECT COALESCE(MAX(sequence_number), 0) + 1 INTO expected_sequence
    FROM public.canonical_payment_attempt_transitions
    WHERE tenant_id = NEW.tenant_id AND payment_attempt_id = NEW.payment_attempt_id;
    IF NEW.sequence_number <> expected_sequence THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt transition sequence is not contiguous';
    END IF;
    IF expected_sequence = 1 THEN
        IF NEW.from_state IS NOT NULL OR NEW.to_state <> attempt.attempt_state THEN
            RAISE EXCEPTION USING MESSAGE = 'initial payment attempt transition is invalid';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.from_state IS DISTINCT FROM attempt.attempt_state THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt transition source differs from current state';
    END IF;
    IF NOT (
        (attempt.attempt_state = 'pending' AND NEW.to_state IN ('processing','failed','cancelled','expired'))
        OR (attempt.attempt_state = 'processing' AND NEW.to_state IN ('requires_action','authorized','succeeded','failed','cancelled','expired'))
        OR (attempt.attempt_state = 'requires_action' AND NEW.to_state IN ('processing','authorized','succeeded','failed','cancelled','expired'))
        OR (attempt.attempt_state = 'authorized' AND NEW.to_state IN ('succeeded','failed','cancelled','expired'))
    ) THEN
        RAISE EXCEPTION USING MESSAGE = 'invalid payment attempt state transition';
    END IF;
    IF NEW.to_state = 'expired'
       AND (attempt.timeout_at IS NULL OR NEW.occurred_at < attempt.timeout_at) THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt cannot expire before its timeout authority';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_capture_initial_payment_attempt_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.canonical_payment_attempt_transitions (
        tenant_id, organization_unit_id, payment_attempt_id, sequence_number,
        from_state, to_state, reason_code, external_attempt_reference_snapshot,
        evidence_payload, occurred_at, business_date, calendar_policy_version,
        correlation_id, actor_user_id, actor_service,
        source_component, source_record_id, metadata
    ) VALUES (
        NEW.tenant_id, NEW.organization_unit_id, NEW.id, 1,
        NULL, NEW.attempt_state, 'attempt_created', NEW.external_attempt_reference,
        '{}'::jsonb, NEW.occurred_at, NEW.business_date, NEW.calendar_policy_version,
        NEW.correlation_id, NEW.actor_user_id, NEW.actor_service,
        NEW.source_component, NEW.source_record_id || '.initial', '{}'::jsonb
    );
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_guard_payment_attempt_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    latest public.canonical_payment_attempt_transitions;
BEGIN
    IF NEW.tenant_id <> OLD.tenant_id
       OR NEW.organization_unit_id <> OLD.organization_unit_id
       OR NEW.payment_intent_id <> OLD.payment_intent_id
       OR NEW.payment_tender_id IS DISTINCT FROM OLD.payment_tender_id
       OR NEW.provider_account_id IS DISTINCT FROM OLD.provider_account_id
       OR NEW.retry_of_attempt_id IS DISTINCT FROM OLD.retry_of_attempt_id
       OR NEW.attempted_amount <> OLD.attempted_amount
       OR NEW.currency_code <> OLD.currency_code
       OR NEW.payment_method_code <> OLD.payment_method_code
       OR NEW.payment_rail_code <> OLD.payment_rail_code
       OR NEW.orchestrator_code <> OLD.orchestrator_code
       OR NEW.underlying_provider_code IS DISTINCT FROM OLD.underlying_provider_code
       OR NEW.timeout_at IS DISTINCT FROM OLD.timeout_at
       OR NEW.occurred_at <> OLD.occurred_at
       OR NEW.business_date <> OLD.business_date
       OR NEW.correlation_id <> OLD.correlation_id
       OR NEW.source_component <> OLD.source_component
       OR NEW.source_record_id <> OLD.source_record_id
       OR NEW.idempotency_scope <> OLD.idempotency_scope
       OR NEW.idempotency_key <> OLD.idempotency_key
       OR NEW.request_fingerprint <> OLD.request_fingerprint
       OR NEW.public_id <> OLD.public_id
       OR NEW.recorded_at <> OLD.recorded_at
       OR NEW.calendar_policy_version <> OLD.calendar_policy_version
       OR NEW.actor_user_id IS DISTINCT FROM OLD.actor_user_id
       OR NEW.actor_service IS DISTINCT FROM OLD.actor_service
       OR NEW.metadata IS DISTINCT FROM OLD.metadata
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt identity and routing fields are immutable';
    END IF;
    IF NEW.attempt_state = OLD.attempt_state OR NEW.row_version <> OLD.row_version + 1 THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt update requires one governed state transition';
    END IF;
    SELECT * INTO latest
    FROM public.canonical_payment_attempt_transitions
    WHERE tenant_id = OLD.tenant_id AND payment_attempt_id = OLD.id
    ORDER BY sequence_number DESC LIMIT 1;
    IF latest.from_state IS DISTINCT FROM OLD.attempt_state
       OR latest.to_state IS DISTINCT FROM NEW.attempt_state
       OR latest.external_attempt_reference_snapshot IS DISTINCT FROM NEW.external_attempt_reference
       OR latest.failure_code IS DISTINCT FROM NEW.failure_code THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt update lacks matching append-only transition evidence';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_confirm_payment_attempt_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_state VARCHAR(32);
    latest_state VARCHAR(32);
BEGIN
    SELECT attempt_state INTO current_state
    FROM public.canonical_payment_attempts
    WHERE tenant_id = NEW.tenant_id AND id = NEW.payment_attempt_id;
    SELECT to_state INTO latest_state
    FROM public.canonical_payment_attempt_transitions
    WHERE tenant_id = NEW.tenant_id AND payment_attempt_id = NEW.payment_attempt_id
    ORDER BY sequence_number DESC LIMIT 1;
    IF current_state IS DISTINCT FROM latest_state THEN
        RAISE EXCEPTION USING MESSAGE = 'payment attempt state and append-only history diverge';
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_payment_attempt_validate_insert
    BEFORE INSERT ON public.canonical_payment_attempts
    FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_attempt_insert();

CREATE TRIGGER trg_payment_attempt_initial_transition
    AFTER INSERT ON public.canonical_payment_attempts
    FOR EACH ROW EXECUTE FUNCTION public.xbos_capture_initial_payment_attempt_transition();

CREATE TRIGGER trg_payment_attempt_transition_validate
    BEFORE INSERT ON public.canonical_payment_attempt_transitions
    FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_attempt_transition();

CREATE TRIGGER trg_payment_attempt_transition_immutable
    BEFORE UPDATE OR DELETE ON public.canonical_payment_attempt_transitions
    FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();

CREATE CONSTRAINT TRIGGER trg_payment_attempt_history_consistent
    AFTER INSERT ON public.canonical_payment_attempt_transitions
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION public.xbos_confirm_payment_attempt_history();

CREATE TRIGGER trg_payment_attempt_guard_update
    BEFORE UPDATE ON public.canonical_payment_attempts
    FOR EACH ROW EXECUTE FUNCTION public.xbos_guard_payment_attempt_update();

CREATE TRIGGER trg_payment_attempt_reject_delete
    BEFORE DELETE ON public.canonical_payment_attempts
    FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();
