ALTER TABLE public.payment_settlements
    ADD COLUMN value_date DATE NULL,
    ADD COLUMN terminal_at TIMESTAMPTZ NULL,
    ADD COLUMN failure_code VARCHAR(80) NULL,
    ADD COLUMN evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN reversed_amount NUMERIC(24,8) NOT NULL DEFAULT 0;

ALTER TABLE public.payment_settlements
    DROP CONSTRAINT ck_payment_settlements_external_evidence;

ALTER TABLE public.payment_settlements
    ADD CONSTRAINT uq_payment_settlements_transition_target
        UNIQUE (tenant_id, organization_unit_id, id),
    ADD CONSTRAINT ck_payment_settlements_value_date
        CHECK (value_date IS NOT NULL),
    ADD CONSTRAINT ck_payment_settlements_terminal CHECK (
        (settlement_state = 'pending' AND terminal_at IS NULL)
        OR (settlement_state IN ('confirmed','failed','partially_reversed','reversed')
            AND terminal_at IS NOT NULL)
    ),
    ADD CONSTRAINT ck_payment_settlements_failure CHECK (
        (settlement_state = 'failed' AND failure_code IS NOT NULL)
        OR (settlement_state <> 'failed' AND failure_code IS NULL)
    ),
    ADD CONSTRAINT ck_payment_settlements_evidence
        CHECK (jsonb_typeof(evidence_payload) = 'object'),
    ADD CONSTRAINT ck_payment_settlements_reversed_amount
        CHECK (reversed_amount >= 0 AND reversed_amount <= gross_amount),
    ADD CONSTRAINT ck_payment_settlements_external_evidence CHECK (
        finality_status <> 'final'
        OR payment_rail_code IN ('cash','internal_credit')
        OR provider_callback_event_id IS NOT NULL
        OR (payment_attempt_id IS NOT NULL
            AND external_settlement_reference IS NOT NULL
            AND evidence_payload <> '{}'::jsonb)
    );

CREATE UNIQUE INDEX uq_payment_settlements_provider_identity
    ON public.payment_settlements
    (tenant_id, payment_rail_code, external_settlement_reference)
    WHERE external_settlement_reference IS NOT NULL;

CREATE TABLE public.payment_settlement_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_settlement_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    from_state VARCHAR(32) NULL,
    to_state VARCHAR(32) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    finality_status VARCHAR(24) NOT NULL,
    availability_state VARCHAR(24) NOT NULL,
    failure_code VARCHAR(80) NULL,
    external_settlement_reference_snapshot VARCHAR(255) NULL,
    value_date_snapshot DATE NOT NULL,
    evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(200) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_settlement_transitions_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_settlement_transitions_sequence
        UNIQUE (tenant_id, payment_settlement_id, sequence_number),
    CONSTRAINT uq_payment_settlement_transitions_source
        UNIQUE (tenant_id, source_component, source_record_id),
    CONSTRAINT fk_payment_settlement_transitions_settlement FOREIGN KEY
        (tenant_id, organization_unit_id, payment_settlement_id)
        REFERENCES public.payment_settlements
        (tenant_id, organization_unit_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_settlement_transitions_actor FOREIGN KEY
        (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_settlement_transitions_sequence CHECK (sequence_number > 0),
    CONSTRAINT ck_payment_settlement_transitions_from CHECK (
        from_state IS NULL OR from_state IN
        ('pending','confirmed','failed','partially_reversed','reversed')
    ),
    CONSTRAINT ck_payment_settlement_transitions_to CHECK (
        to_state IN ('pending','confirmed','failed','partially_reversed','reversed')
    ),
    CONSTRAINT ck_payment_settlement_transitions_reason
        CHECK (reason_code ~ '^[a-z][a-z0-9_.-]{0,79}$'),
    CONSTRAINT ck_payment_settlement_transitions_failure CHECK (
        (to_state = 'failed' AND failure_code IS NOT NULL)
        OR (to_state <> 'failed' AND failure_code IS NULL)
    ),
    CONSTRAINT ck_payment_settlement_transitions_finality CHECK (
        finality_status IN ('unverified','provisional','final','rejected','not_applicable')
    ),
    CONSTRAINT ck_payment_settlement_transitions_availability CHECK (
        availability_state IN ('pending','available','reserved','released','unavailable')
    ),
    CONSTRAINT ck_payment_settlement_transitions_evidence
        CHECK (jsonb_typeof(evidence_payload) = 'object'),
    CONSTRAINT ck_payment_settlement_transitions_calendar
        CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_payment_settlement_transitions_actor CHECK (
        actor_user_id IS NOT NULL
        OR (actor_service IS NOT NULL AND length(btrim(actor_service)) > 0)
    ),
    CONSTRAINT ck_payment_settlement_transitions_metadata
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_payment_settlement_transitions_history
    ON public.payment_settlement_transitions
    (tenant_id, payment_settlement_id, sequence_number);

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_settlement_insert()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    intent public.canonical_payment_intents;
    attempt public.canonical_payment_attempts;
    account public.operational_financial_accounts;
BEGIN
    SELECT * INTO intent FROM public.canonical_payment_intents
    WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_intent_id FOR SHARE;
    IF NOT FOUND OR intent.organization_unit_id <> NEW.organization_unit_id
       OR intent.currency_code <> NEW.currency_code THEN
        RAISE EXCEPTION USING MESSAGE='settlement intent scope or currency mismatch';
    END IF;
    IF NEW.gross_amount > intent.requested_amount THEN
        RAISE EXCEPTION USING MESSAGE='settlement exceeds payment intent amount';
    END IF;
    IF NEW.payment_attempt_id IS NOT NULL THEN
        SELECT * INTO attempt FROM public.canonical_payment_attempts
        WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_attempt_id FOR SHARE;
        IF NOT FOUND OR attempt.payment_intent_id <> NEW.payment_intent_id
           OR attempt.organization_unit_id <> NEW.organization_unit_id
           OR attempt.currency_code <> NEW.currency_code
           OR attempt.attempt_state <> 'succeeded'
           OR NEW.gross_amount > attempt.attempted_amount THEN
            RAISE EXCEPTION USING MESSAGE='settlement requires matching successful attempt authority';
        END IF;
        IF attempt.payment_method_code <> NEW.payment_method_code
           OR attempt.payment_rail_code <> NEW.payment_rail_code THEN
            RAISE EXCEPTION USING MESSAGE='settlement routing differs from payment attempt';
        END IF;
    ELSIF NEW.payment_rail_code NOT IN ('cash','internal_credit') THEN
        RAISE EXCEPTION USING MESSAGE='external settlement requires payment attempt authority';
    END IF;
    SELECT * INTO account FROM public.operational_financial_accounts
    WHERE tenant_id=NEW.tenant_id AND id=NEW.operational_account_id FOR SHARE;
    IF NOT FOUND OR account.organization_unit_id <> NEW.organization_unit_id
       OR account.currency_code <> NEW.currency_code OR NOT account.active
       OR account.aggregation_role <> 'leaf' THEN
        RAISE EXCEPTION USING MESSAGE='settlement operational account is unavailable';
    END IF;
    IF NEW.settlement_state <> 'pending' OR NEW.row_version <> 1
       OR NEW.terminal_at IS NOT NULL OR NEW.failure_code IS NOT NULL
       OR NEW.reversed_amount <> 0 THEN
        RAISE EXCEPTION USING MESSAGE='settlement must begin pending with version one';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_capture_initial_payment_settlement_transition()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO public.payment_settlement_transitions (
        tenant_id, organization_unit_id, payment_settlement_id, sequence_number,
        from_state, to_state, reason_code, finality_status, availability_state,
        failure_code, external_settlement_reference_snapshot, value_date_snapshot,
        evidence_payload, occurred_at, business_date, calendar_policy_version,
        correlation_id, actor_user_id, actor_service, source_component,
        source_record_id, metadata
    ) VALUES (
        NEW.tenant_id, NEW.organization_unit_id, NEW.id, 1,
        NULL, 'pending', 'settlement_created', NEW.finality_status, NEW.availability_state,
        NULL, NEW.external_settlement_reference, NEW.value_date,
        NEW.evidence_payload, NEW.occurred_at, NEW.business_date, NEW.calendar_policy_version,
        NEW.correlation_id, NEW.actor_user_id, NEW.actor_service,
        'm43.initial_settlement', NEW.public_id::text, NEW.metadata
    );
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_settlement_transition()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    settlement public.payment_settlements;
    count_rows INTEGER;
    reversal_match INTEGER;
BEGIN
    SELECT * INTO settlement FROM public.payment_settlements
    WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_settlement_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION USING MESSAGE='settlement transition target missing'; END IF;
    SELECT count(*) INTO count_rows FROM public.payment_settlement_transitions
    WHERE tenant_id=NEW.tenant_id AND payment_settlement_id=NEW.payment_settlement_id;
    IF NEW.sequence_number <> count_rows + 1 THEN
        RAISE EXCEPTION USING MESSAGE='settlement transition sequence is not contiguous';
    END IF;
    IF count_rows=0 THEN
        IF NEW.from_state IS NOT NULL OR NEW.to_state <> 'pending' THEN
            RAISE EXCEPTION USING MESSAGE='initial settlement transition is invalid';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.from_state <> settlement.settlement_state THEN
        RAISE EXCEPTION USING MESSAGE='settlement transition source differs from current state';
    END IF;
    IF NOT (
        (NEW.from_state='pending' AND NEW.to_state IN ('confirmed','failed'))
        OR (NEW.from_state='confirmed' AND NEW.to_state IN ('partially_reversed','reversed'))
        OR (NEW.from_state='partially_reversed' AND NEW.to_state IN ('partially_reversed','reversed'))
    ) THEN RAISE EXCEPTION USING MESSAGE='invalid settlement state transition'; END IF;
    IF NEW.occurred_at < settlement.occurred_at THEN
        RAISE EXCEPTION USING MESSAGE='settlement transition precedes settlement';
    END IF;
    IF NEW.to_state IN ('confirmed','failed','partially_reversed','reversed')
       AND NEW.evidence_payload='{}'::jsonb THEN
        RAISE EXCEPTION USING MESSAGE='settlement transition requires evidence';
    END IF;
    IF NEW.to_state='confirmed' AND settlement.payment_rail_code NOT IN ('cash','internal_credit')
       AND NEW.external_settlement_reference_snapshot IS NULL THEN
        RAISE EXCEPTION USING MESSAGE='confirmed external settlement requires provider transaction identity';
    END IF;
    IF NEW.to_state IN ('partially_reversed','reversed') THEN
        SELECT count(*) INTO reversal_match
        FROM public.payment_settlement_reversals r
        WHERE r.tenant_id=NEW.tenant_id
          AND r.payment_settlement_id=NEW.payment_settlement_id
          AND r.source_component=NEW.source_component
          AND r.source_record_id || '.transition'=NEW.source_record_id;
        IF reversal_match<>1 THEN
            RAISE EXCEPTION USING MESSAGE='reversal state requires matching append-only reversal fact';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_guard_payment_settlement_update()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE latest public.payment_settlement_transitions; reversal_sum NUMERIC(24,8);
BEGIN
    IF NEW.tenant_id<>OLD.tenant_id OR NEW.organization_unit_id<>OLD.organization_unit_id
       OR NEW.payment_intent_id<>OLD.payment_intent_id
       OR NEW.payment_attempt_id IS DISTINCT FROM OLD.payment_attempt_id
       OR NEW.provider_callback_event_id IS DISTINCT FROM OLD.provider_callback_event_id
       OR NEW.operational_account_id<>OLD.operational_account_id
       OR NEW.settlement_direction<>OLD.settlement_direction
       OR NEW.gross_amount<>OLD.gross_amount OR NEW.fee_amount<>OLD.fee_amount
       OR NEW.net_amount<>OLD.net_amount OR NEW.currency_code<>OLD.currency_code
       OR NEW.payment_method_code<>OLD.payment_method_code
       OR NEW.payment_rail_code<>OLD.payment_rail_code
       OR NEW.value_date<>OLD.value_date OR NEW.occurred_at<>OLD.occurred_at
       OR NEW.business_date<>OLD.business_date OR NEW.correlation_id<>OLD.correlation_id
       OR NEW.source_component<>OLD.source_component OR NEW.source_record_id<>OLD.source_record_id
       OR NEW.idempotency_scope<>OLD.idempotency_scope OR NEW.idempotency_key<>OLD.idempotency_key
       OR NEW.request_fingerprint<>OLD.request_fingerprint OR NEW.metadata<>OLD.metadata THEN
        RAISE EXCEPTION USING MESSAGE='immutable settlement identity or monetary truth cannot be updated';
    END IF;
    IF NEW.row_version<>OLD.row_version+1 THEN
        RAISE EXCEPTION USING MESSAGE='settlement row version must increment once';
    END IF;
    SELECT * INTO latest FROM public.payment_settlement_transitions
    WHERE tenant_id=OLD.tenant_id AND payment_settlement_id=OLD.id
    ORDER BY sequence_number DESC LIMIT 1;
    IF latest.sequence_number<>NEW.row_version OR latest.from_state<>OLD.settlement_state
       OR latest.to_state<>NEW.settlement_state OR latest.finality_status<>NEW.finality_status
       OR latest.availability_state<>NEW.availability_state
       OR latest.failure_code IS DISTINCT FROM NEW.failure_code
       OR latest.external_settlement_reference_snapshot IS DISTINCT FROM NEW.external_settlement_reference
       OR latest.evidence_payload<>NEW.evidence_payload THEN
        RAISE EXCEPTION USING MESSAGE='settlement update lacks matching append-only transition evidence';
    END IF;
    SELECT COALESCE(sum(reversal_amount),0) INTO reversal_sum
    FROM public.payment_settlement_reversals
    WHERE tenant_id=OLD.tenant_id AND payment_settlement_id=OLD.id;
    IF NEW.reversed_amount<>reversal_sum
       OR (NEW.settlement_state='partially_reversed' AND NOT (reversal_sum>0 AND reversal_sum<NEW.gross_amount))
       OR (NEW.settlement_state='reversed' AND reversal_sum<>NEW.gross_amount)
       OR (NEW.settlement_state IN ('pending','confirmed','failed') AND reversal_sum<>0) THEN
        RAISE EXCEPTION USING MESSAGE='settlement reversal state differs from append-only reversal facts';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_settlement_reversal()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE settlement public.payment_settlements; total NUMERIC(24,8);
BEGIN
    SELECT * INTO settlement FROM public.payment_settlements
    WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_settlement_id FOR UPDATE;
    IF NOT FOUND OR settlement.organization_unit_id<>NEW.organization_unit_id
       OR settlement.currency_code<>NEW.currency_code THEN
        RAISE EXCEPTION USING MESSAGE='reversal settlement scope or currency mismatch';
    END IF;
    IF settlement.settlement_state NOT IN ('confirmed','partially_reversed') THEN
        RAISE EXCEPTION USING MESSAGE='only confirmed settlement value can be reversed';
    END IF;
    SELECT COALESCE(sum(reversal_amount),0) INTO total
    FROM public.payment_settlement_reversals
    WHERE tenant_id=NEW.tenant_id AND payment_settlement_id=NEW.payment_settlement_id;
    IF total+NEW.reversal_amount>settlement.gross_amount THEN
        RAISE EXCEPTION USING MESSAGE='settlement reversal exceeds original gross amount';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.xbos_apply_payment_settlement_reversal()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE settlement public.payment_settlements; total NUMERIC(24,8); target VARCHAR(32);
BEGIN
    SELECT * INTO settlement FROM public.payment_settlements
    WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_settlement_id FOR UPDATE;
    SELECT sum(reversal_amount) INTO total FROM public.payment_settlement_reversals
    WHERE tenant_id=NEW.tenant_id AND payment_settlement_id=NEW.payment_settlement_id;
    IF total=settlement.gross_amount THEN target:='reversed'; ELSE target:='partially_reversed'; END IF;
    INSERT INTO public.payment_settlement_transitions (
        tenant_id, organization_unit_id, payment_settlement_id, sequence_number,
        from_state, to_state, reason_code, finality_status, availability_state,
        failure_code, external_settlement_reference_snapshot, value_date_snapshot,
        evidence_payload, occurred_at, business_date, calendar_policy_version,
        correlation_id, actor_user_id, actor_service, source_component, source_record_id, metadata
    ) VALUES (
        NEW.tenant_id, NEW.organization_unit_id, NEW.payment_settlement_id,
        settlement.row_version+1, settlement.settlement_state, target, NEW.reason_code,
        'final', CASE WHEN target='reversed' THEN 'released' ELSE 'reserved' END,
        NULL, settlement.external_settlement_reference, settlement.value_date,
        jsonb_build_object('reversal_public_id',NEW.public_id,'reversal_amount',NEW.reversal_amount,
                           'cumulative_reversed_amount',total),
        NEW.occurred_at, NEW.business_date, NEW.calendar_policy_version,
        NEW.correlation_id, NEW.actor_user_id, NEW.actor_service,
        NEW.source_component, NEW.source_record_id || '.transition', NEW.metadata
    );
    UPDATE public.payment_settlements SET
        settlement_state=target, finality_status='final',
        availability_state=CASE WHEN target='reversed' THEN 'released' ELSE 'reserved' END,
        terminal_at=NEW.occurred_at, failure_code=NULL,
        evidence_payload=jsonb_build_object('reversal_public_id',NEW.public_id,
                                             'reversal_amount',NEW.reversal_amount,
                                             'cumulative_reversed_amount',total),
        reversed_amount=total, row_version=row_version+1, updated_at=now()
    WHERE id=NEW.payment_settlement_id;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_payment_settlement_validate_insert
    BEFORE INSERT ON public.payment_settlements
    FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_settlement_insert();
CREATE TRIGGER trg_payment_settlement_initial_transition
    AFTER INSERT ON public.payment_settlements
    FOR EACH ROW EXECUTE FUNCTION public.xbos_capture_initial_payment_settlement_transition();
CREATE TRIGGER trg_payment_settlement_transition_validate
    BEFORE INSERT ON public.payment_settlement_transitions
    FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_settlement_transition();
CREATE TRIGGER trg_payment_settlement_transition_immutable
    BEFORE UPDATE OR DELETE ON public.payment_settlement_transitions
    FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();
CREATE TRIGGER trg_payment_settlement_guard_update
    BEFORE UPDATE ON public.payment_settlements
    FOR EACH ROW EXECUTE FUNCTION public.xbos_guard_payment_settlement_update();
CREATE TRIGGER trg_payment_settlement_reject_delete
    BEFORE DELETE ON public.payment_settlements
    FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();
CREATE TRIGGER trg_payment_settlement_reversal_validate
    BEFORE INSERT ON public.payment_settlement_reversals
    FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_settlement_reversal();
CREATE TRIGGER trg_payment_settlement_reversal_apply
    AFTER INSERT ON public.payment_settlement_reversals
    FOR EACH ROW EXECUTE FUNCTION public.xbos_apply_payment_settlement_reversal();
