ALTER TABLE public.canonical_payment_tenders
    ADD COLUMN terminal_at TIMESTAMPTZ NULL,
    ADD COLUMN failure_code VARCHAR(80) NULL,
    ADD COLUMN evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.payment_settlements ADD COLUMN payment_tender_id BIGINT NULL;
ALTER TABLE public.payment_settlements ADD CONSTRAINT fk_payment_settlements_tender
    FOREIGN KEY(tenant_id,organization_unit_id,payment_intent_id,payment_tender_id,currency_code)
    REFERENCES public.canonical_payment_tenders(tenant_id,organization_unit_id,payment_intent_id,id,currency_code) ON DELETE RESTRICT;

ALTER TABLE public.canonical_payment_tenders
    ADD CONSTRAINT uq_canonical_payment_tenders_transition_target UNIQUE(tenant_id,organization_unit_id,id),
    ADD CONSTRAINT ck_canonical_payment_tenders_terminal CHECK((tender_state IN ('pending','processing','partially_succeeded') AND terminal_at IS NULL) OR (tender_state IN ('succeeded','failed','cancelled') AND terminal_at IS NOT NULL)),
    ADD CONSTRAINT ck_canonical_payment_tenders_failure CHECK((tender_state='failed' AND failure_code IS NOT NULL) OR (tender_state<>'failed' AND failure_code IS NULL)),
    ADD CONSTRAINT ck_canonical_payment_tenders_evidence CHECK(jsonb_typeof(evidence_payload)='object');

CREATE UNIQUE INDEX uq_canonical_payment_attempts_tender_success ON public.canonical_payment_attempts(tenant_id,payment_tender_id) WHERE payment_tender_id IS NOT NULL AND attempt_state='succeeded';

CREATE TABLE public.payment_tender_transitions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL, payment_tender_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL, from_state VARCHAR(24) NULL, to_state VARCHAR(24) NOT NULL,
    reason_code VARCHAR(80) NOT NULL, failure_code VARCHAR(80) NULL,
    evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(), business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL, correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL, actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL, source_record_id VARCHAR(200) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_tender_transitions_public_id UNIQUE(public_id),
    CONSTRAINT uq_payment_tender_transitions_sequence UNIQUE(tenant_id,payment_tender_id,sequence_number),
    CONSTRAINT uq_payment_tender_transitions_source UNIQUE(tenant_id,source_component,source_record_id),
    CONSTRAINT fk_payment_tender_transitions_tender FOREIGN KEY(tenant_id,organization_unit_id,payment_tender_id) REFERENCES public.canonical_payment_tenders(tenant_id,organization_unit_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_tender_transitions_actor FOREIGN KEY(tenant_id,actor_user_id) REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_payment_tender_transitions_sequence CHECK(sequence_number>0),
    CONSTRAINT ck_payment_tender_transitions_from CHECK(from_state IS NULL OR from_state IN ('pending','processing','partially_succeeded','succeeded','failed','cancelled')),
    CONSTRAINT ck_payment_tender_transitions_to CHECK(to_state IN ('pending','processing','partially_succeeded','succeeded','failed','cancelled')),
    CONSTRAINT ck_payment_tender_transitions_reason CHECK(reason_code ~ '^[a-z][a-z0-9_.-]{0,79}$'),
    CONSTRAINT ck_payment_tender_transitions_failure CHECK((to_state='failed' AND failure_code IS NOT NULL) OR (to_state<>'failed' AND failure_code IS NULL)),
    CONSTRAINT ck_payment_tender_transitions_evidence CHECK(jsonb_typeof(evidence_payload)='object'),
    CONSTRAINT ck_payment_tender_transitions_calendar CHECK(calendar_policy_version>0),
    CONSTRAINT ck_payment_tender_transitions_actor CHECK(actor_user_id IS NOT NULL OR (actor_service IS NOT NULL AND length(btrim(actor_service))>0)),
    CONSTRAINT ck_payment_tender_transitions_metadata CHECK(jsonb_typeof(metadata)='object')
);
CREATE INDEX ix_payment_tender_transitions_history ON public.payment_tender_transitions(tenant_id,payment_tender_id,sequence_number);

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_tender_insert() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE intent public.canonical_payment_intents; active_count INTEGER; active_total NUMERIC(24,8); next_number INTEGER; maximum INTEGER; mixed BOOLEAN;
BEGIN
    SELECT * INTO intent FROM public.canonical_payment_intents WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_intent_id FOR UPDATE;
    IF NOT FOUND OR intent.organization_unit_id<>NEW.organization_unit_id OR intent.currency_code<>NEW.currency_code OR intent.intent_state NOT IN('pending','processing') THEN RAISE EXCEPTION USING MESSAGE='tender requires active matching intent authority'; END IF;
    IF NOT (intent.payment_method_policy->'allowed_methods' @> jsonb_build_array(NEW.payment_method_code)) THEN RAISE EXCEPTION USING MESSAGE='tender method is not allowed by intent'; END IF;
    maximum=(intent.payment_method_policy->>'max_tenders')::integer; mixed=(intent.payment_method_policy->>'allow_mixed_tender')::boolean;
    SELECT count(*)::integer,COALESCE(sum(tender_amount),0) INTO active_count,active_total FROM public.canonical_payment_tenders WHERE tenant_id=NEW.tenant_id AND payment_intent_id=NEW.payment_intent_id AND tender_state NOT IN('failed','cancelled');
    SELECT COALESCE(max(tender_number),0)+1 INTO next_number FROM public.canonical_payment_tenders WHERE tenant_id=NEW.tenant_id AND payment_intent_id=NEW.payment_intent_id;
    IF NEW.tender_number<>next_number THEN RAISE EXCEPTION USING MESSAGE='tender sequence must be contiguous'; END IF;
    IF active_count>=maximum THEN RAISE EXCEPTION USING MESSAGE='intent maximum tender count exceeded'; END IF;
    IF NOT mixed AND (active_count<>0 OR NEW.tender_amount<>intent.requested_amount) THEN RAISE EXCEPTION USING MESSAGE='single tender must exactly equal intent amount'; END IF;
    IF active_total+NEW.tender_amount>intent.requested_amount THEN RAISE EXCEPTION USING MESSAGE='tender composition exceeds intent amount'; END IF;
    IF NEW.tender_state<>'pending' OR NEW.row_version<>1 OR NEW.terminal_at IS NOT NULL OR NEW.failure_code IS NOT NULL THEN RAISE EXCEPTION USING MESSAGE='tender must begin pending with version one'; END IF;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.xbos_capture_initial_payment_tender_transition() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO public.payment_tender_transitions(tenant_id,organization_unit_id,payment_tender_id,sequence_number,from_state,to_state,reason_code,failure_code,evidence_payload,occurred_at,business_date,calendar_policy_version,correlation_id,actor_user_id,actor_service,source_component,source_record_id,metadata)
    VALUES(NEW.tenant_id,NEW.organization_unit_id,NEW.id,1,NULL,'pending','tender_created',NULL,'{}'::jsonb,NEW.occurred_at,NEW.business_date,NEW.calendar_policy_version,NEW.correlation_id,NEW.actor_user_id,NEW.actor_service,'m44.initial_tender',NEW.public_id::text,NEW.metadata);
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_tender_transition() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE tender public.canonical_payment_tenders; rows_count INTEGER;
BEGIN
    SELECT * INTO tender FROM public.canonical_payment_tenders WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_tender_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION USING MESSAGE='tender transition target missing'; END IF;
    SELECT count(*) INTO rows_count FROM public.payment_tender_transitions WHERE tenant_id=NEW.tenant_id AND payment_tender_id=NEW.payment_tender_id;
    IF NEW.sequence_number<>rows_count+1 THEN RAISE EXCEPTION USING MESSAGE='tender transition sequence is not contiguous'; END IF;
    IF rows_count=0 THEN IF NEW.from_state IS NOT NULL OR NEW.to_state<>'pending' THEN RAISE EXCEPTION USING MESSAGE='initial tender transition is invalid'; END IF; RETURN NEW; END IF;
    IF NEW.from_state<>tender.tender_state THEN RAISE EXCEPTION USING MESSAGE='tender transition source differs from current state'; END IF;
    IF NOT ((NEW.from_state='pending' AND NEW.to_state IN('processing','succeeded','failed','cancelled')) OR (NEW.from_state='processing' AND NEW.to_state IN('partially_succeeded','succeeded','failed','cancelled')) OR (NEW.from_state='partially_succeeded' AND NEW.to_state IN('succeeded','failed','cancelled'))) THEN RAISE EXCEPTION USING MESSAGE='invalid tender state transition'; END IF;
    IF NEW.occurred_at<tender.occurred_at THEN RAISE EXCEPTION USING MESSAGE='tender transition precedes tender'; END IF;
    IF NEW.to_state IN('partially_succeeded','succeeded','failed') AND NEW.evidence_payload='{}'::jsonb THEN RAISE EXCEPTION USING MESSAGE='tender result requires evidence'; END IF;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.xbos_guard_payment_tender_update() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE latest public.payment_tender_transitions;
BEGIN
    IF NEW.tenant_id<>OLD.tenant_id OR NEW.organization_unit_id<>OLD.organization_unit_id OR NEW.payment_intent_id<>OLD.payment_intent_id OR NEW.tender_number<>OLD.tender_number OR NEW.tender_amount<>OLD.tender_amount OR NEW.currency_code<>OLD.currency_code OR NEW.payment_method_code<>OLD.payment_method_code OR NEW.instrument_reference IS DISTINCT FROM OLD.instrument_reference OR NEW.occurred_at<>OLD.occurred_at OR NEW.business_date<>OLD.business_date OR NEW.correlation_id<>OLD.correlation_id OR NEW.source_component<>OLD.source_component OR NEW.source_record_id<>OLD.source_record_id OR NEW.metadata<>OLD.metadata THEN RAISE EXCEPTION USING MESSAGE='immutable tender identity or amount cannot be updated'; END IF;
    IF NEW.row_version<>OLD.row_version+1 THEN RAISE EXCEPTION USING MESSAGE='tender row version must increment once'; END IF;
    SELECT * INTO latest FROM public.payment_tender_transitions WHERE tenant_id=OLD.tenant_id AND payment_tender_id=OLD.id ORDER BY sequence_number DESC LIMIT 1;
    IF latest.sequence_number<>NEW.row_version OR latest.from_state<>OLD.tender_state OR latest.to_state<>NEW.tender_state OR latest.failure_code IS DISTINCT FROM NEW.failure_code OR latest.evidence_payload<>NEW.evidence_payload THEN RAISE EXCEPTION USING MESSAGE='tender update lacks matching append-only transition evidence'; END IF;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_attempt_insert() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE prior public.canonical_payment_attempts; tender public.canonical_payment_tenders; intent public.canonical_payment_intents;
BEGIN
    SELECT * INTO intent FROM public.canonical_payment_intents WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_intent_id FOR SHARE;
    IF (intent.payment_method_policy->>'allow_mixed_tender')::boolean AND NEW.payment_tender_id IS NULL THEN RAISE EXCEPTION USING MESSAGE='mixed-tender attempt requires explicit tender authority'; END IF;
    IF NEW.payment_tender_id IS NOT NULL THEN
        SELECT * INTO tender FROM public.canonical_payment_tenders WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_tender_id FOR UPDATE;
        IF NOT FOUND OR tender.payment_intent_id<>NEW.payment_intent_id OR tender.organization_unit_id<>NEW.organization_unit_id OR tender.currency_code<>NEW.currency_code OR tender.payment_method_code<>NEW.payment_method_code OR tender.tender_state IN('succeeded','failed','cancelled') OR NEW.attempted_amount>tender.tender_amount THEN RAISE EXCEPTION USING MESSAGE='attempt does not match active tender authority'; END IF;
    END IF;
    IF NEW.retry_of_attempt_id IS NULL THEN RETURN NEW; END IF;
    SELECT * INTO prior FROM public.canonical_payment_attempts WHERE tenant_id=NEW.tenant_id AND id=NEW.retry_of_attempt_id FOR UPDATE;
    IF NOT FOUND OR prior.id=NEW.id OR prior.payment_intent_id<>NEW.payment_intent_id OR prior.payment_tender_id IS DISTINCT FROM NEW.payment_tender_id OR prior.organization_unit_id<>NEW.organization_unit_id OR prior.currency_code<>NEW.currency_code OR prior.attempt_state NOT IN('failed','cancelled','expired') THEN RAISE EXCEPTION USING MESSAGE='retry must follow terminal unsuccessful attempt for same tender and intent'; END IF;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_payment_pattern_settlement() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE intent public.canonical_payment_intents; tender public.canonical_payment_tenders; attempt public.canonical_payment_attempts; committed NUMERIC(24,8);
BEGIN
    SELECT * INTO intent FROM public.canonical_payment_intents WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_intent_id FOR SHARE;
    IF (intent.payment_method_policy->>'allow_mixed_tender')::boolean AND NEW.payment_tender_id IS NULL THEN RAISE EXCEPTION USING MESSAGE='mixed settlement requires explicit tender authority'; END IF;
    IF NEW.payment_tender_id IS NOT NULL THEN
        SELECT * INTO tender FROM public.canonical_payment_tenders WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_tender_id FOR UPDATE;
        IF NOT FOUND OR tender.payment_intent_id<>NEW.payment_intent_id OR tender.organization_unit_id<>NEW.organization_unit_id OR tender.currency_code<>NEW.currency_code OR tender.payment_method_code<>NEW.payment_method_code OR tender.tender_state IN('failed','cancelled') THEN RAISE EXCEPTION USING MESSAGE='settlement does not match active tender authority'; END IF;
        IF NEW.payment_attempt_id IS NOT NULL THEN
            SELECT * INTO attempt FROM public.canonical_payment_attempts WHERE tenant_id=NEW.tenant_id AND id=NEW.payment_attempt_id FOR SHARE;
            IF attempt.payment_tender_id IS DISTINCT FROM NEW.payment_tender_id THEN RAISE EXCEPTION USING MESSAGE='settlement attempt and tender authority differ'; END IF;
        END IF;
        SELECT COALESCE(sum(gross_amount),0) INTO committed FROM public.payment_settlements WHERE tenant_id=NEW.tenant_id AND payment_tender_id=NEW.payment_tender_id AND settlement_state NOT IN('failed','reversed');
        IF committed+NEW.gross_amount>tender.tender_amount THEN RAISE EXCEPTION USING MESSAGE='settlement exceeds tender capacity'; END IF;
    END IF;
    RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.xbos_guard_payment_pattern_settlement_update() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.payment_tender_id IS DISTINCT FROM OLD.payment_tender_id THEN RAISE EXCEPTION USING MESSAGE='settlement tender authority is immutable'; END IF;
    RETURN NEW;
END; $$;

CREATE TRIGGER trg_payment_tender_validate_insert BEFORE INSERT ON public.canonical_payment_tenders FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_tender_insert();
CREATE TRIGGER trg_payment_tender_initial_transition AFTER INSERT ON public.canonical_payment_tenders FOR EACH ROW EXECUTE FUNCTION public.xbos_capture_initial_payment_tender_transition();
CREATE TRIGGER trg_payment_tender_transition_validate BEFORE INSERT ON public.payment_tender_transitions FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_tender_transition();
CREATE TRIGGER trg_payment_tender_transition_immutable BEFORE UPDATE OR DELETE ON public.payment_tender_transitions FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();
CREATE TRIGGER trg_payment_tender_guard_update BEFORE UPDATE ON public.canonical_payment_tenders FOR EACH ROW EXECUTE FUNCTION public.xbos_guard_payment_tender_update();
CREATE TRIGGER trg_payment_tender_reject_delete BEFORE DELETE ON public.canonical_payment_tenders FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_payment_evidence();
CREATE TRIGGER trg_payment_pattern_settlement_validate BEFORE INSERT ON public.payment_settlements FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_payment_pattern_settlement();
CREATE TRIGGER trg_payment_pattern_settlement_guard BEFORE UPDATE ON public.payment_settlements FOR EACH ROW EXECUTE FUNCTION public.xbos_guard_payment_pattern_settlement_update();
