CREATE TABLE public.provider_settlement_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    payment_settlement_id BIGINT NOT NULL,
    provider_account_id BIGINT NOT NULL,
    operational_account_id BIGINT NOT NULL,
    original_component_id BIGINT NULL,
    component_type VARCHAR(32) NOT NULL,
    classification_code VARCHAR(80) NOT NULL,
    amount NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    provider_event_reference VARCHAR(255) NOT NULL,
    value_date DATE NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_provider_settlement_components_public_id UNIQUE (public_id),
    CONSTRAINT uq_provider_settlement_components_tenant_id_id UNIQUE (tenant_id,id),
    CONSTRAINT uq_provider_settlement_components_idempotency
        UNIQUE (tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_provider_settlement_components_source
        UNIQUE (tenant_id,source_component,source_record_id),
    CONSTRAINT uq_provider_settlement_components_provider_event
        UNIQUE (tenant_id,provider_account_id,provider_event_reference),
    CONSTRAINT fk_provider_settlement_components_settlement FOREIGN KEY
        (tenant_id,organization_unit_id,payment_settlement_id)
        REFERENCES public.payment_settlements(tenant_id,organization_unit_id,id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_provider_settlement_components_provider FOREIGN KEY
        (tenant_id,provider_account_id)
        REFERENCES public.payment_provider_accounts(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_settlement_components_operational FOREIGN KEY
        (tenant_id,operational_account_id,currency_code)
        REFERENCES public.operational_financial_accounts(tenant_id,id,currency_code)
        ON DELETE RESTRICT,
    CONSTRAINT fk_provider_settlement_components_original FOREIGN KEY
        (tenant_id,original_component_id)
        REFERENCES public.provider_settlement_components(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_provider_settlement_components_actor FOREIGN KEY
        (tenant_id,actor_user_id) REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_provider_settlement_components_type CHECK (
        component_type IN ('provider_fee','reserve_hold','reserve_release','chargeback_loss')
    ),
    CONSTRAINT ck_provider_settlement_components_original CHECK (
        (component_type='reserve_release' AND original_component_id IS NOT NULL)
        OR (component_type<>'reserve_release' AND original_component_id IS NULL)
    ),
    CONSTRAINT ck_provider_settlement_components_amount CHECK (amount>0),
    CONSTRAINT ck_provider_settlement_components_classification CHECK (
        classification_code=lower(btrim(classification_code)) AND length(classification_code)>0
    ),
    CONSTRAINT ck_provider_settlement_components_reference CHECK (
        provider_event_reference=btrim(provider_event_reference) AND length(provider_event_reference)>0
    ),
    CONSTRAINT ck_provider_settlement_components_hash CHECK (evidence_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_provider_settlement_components_evidence CHECK (jsonb_typeof(evidence_payload)='object'),
    CONSTRAINT ck_provider_settlement_components_actor CHECK (
        actor_user_id IS NOT NULL OR (actor_service IS NOT NULL AND length(btrim(actor_service))>0)
    ),
    CONSTRAINT ck_provider_settlement_components_calendar CHECK (calendar_policy_version>0),
    CONSTRAINT ck_provider_settlement_components_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_provider_settlement_components_metadata CHECK (jsonb_typeof(metadata)='object')
);

CREATE INDEX ix_provider_settlement_components_position
    ON public.provider_settlement_components
    (tenant_id,payment_settlement_id,component_type,occurred_at,id);
CREATE INDEX ix_provider_settlement_components_original
    ON public.provider_settlement_components
    (tenant_id,original_component_id) WHERE original_component_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.xbos_validate_provider_settlement_component()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    settlement_gross NUMERIC(24,8);
    settlement_currency VARCHAR(12);
    settlement_org BIGINT;
    settlement_account BIGINT;
    attempt_provider BIGINT;
    provider_active BOOLEAN;
    original_type VARCHAR(32);
    original_amount NUMERIC(24,8);
    original_settlement BIGINT;
    original_provider BIGINT;
    released_amount NUMERIC(24,8);
    position_effect NUMERIC(24,8);
    new_effect NUMERIC(24,8);
BEGIN
    IF current_setting('xbos.m46_component_authorized',true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'provider settlement components require governed M4.6 engine';
    END IF;

    SELECT s.gross_amount,s.currency_code,s.organization_unit_id,s.operational_account_id,
           a.provider_account_id
      INTO settlement_gross,settlement_currency,settlement_org,settlement_account,attempt_provider
      FROM public.payment_settlements s
      JOIN public.canonical_payment_attempts a ON a.id=s.payment_attempt_id AND a.tenant_id=s.tenant_id
     WHERE s.tenant_id=NEW.tenant_id AND s.id=NEW.payment_settlement_id
       AND s.settlement_state='confirmed'
     FOR UPDATE OF s;
    IF NOT FOUND THEN RAISE EXCEPTION 'confirmed external settlement authority required'; END IF;

    SELECT active INTO provider_active FROM public.payment_provider_accounts
     WHERE tenant_id=NEW.tenant_id AND id=NEW.provider_account_id FOR SHARE;
    IF provider_active IS DISTINCT FROM TRUE THEN RAISE EXCEPTION 'active provider account required'; END IF;
    IF settlement_org<>NEW.organization_unit_id OR settlement_currency<>NEW.currency_code
       OR settlement_account<>NEW.operational_account_id OR attempt_provider<>NEW.provider_account_id THEN
        RAISE EXCEPTION 'provider component scope differs from settlement authority';
    END IF;

    IF NEW.component_type='reserve_release' THEN
        SELECT component_type,amount,payment_settlement_id,provider_account_id
          INTO original_type,original_amount,original_settlement,original_provider
          FROM public.provider_settlement_components
         WHERE tenant_id=NEW.tenant_id AND id=NEW.original_component_id FOR UPDATE;
        IF original_type IS DISTINCT FROM 'reserve_hold' OR original_settlement<>NEW.payment_settlement_id
           OR original_provider<>NEW.provider_account_id THEN
            RAISE EXCEPTION 'reserve release must link matching original hold';
        END IF;
        SELECT COALESCE(sum(amount),0) INTO released_amount
          FROM public.provider_settlement_components
         WHERE tenant_id=NEW.tenant_id AND original_component_id=NEW.original_component_id
           AND component_type='reserve_release';
        IF released_amount+NEW.amount>original_amount THEN
            RAISE EXCEPTION 'reserve release exceeds original hold capacity';
        END IF;
    END IF;

    SELECT COALESCE(sum(CASE WHEN component_type='reserve_release' THEN -amount ELSE amount END),0)
      INTO position_effect FROM public.provider_settlement_components
     WHERE tenant_id=NEW.tenant_id AND payment_settlement_id=NEW.payment_settlement_id;
    new_effect=CASE WHEN NEW.component_type='reserve_release' THEN -NEW.amount ELSE NEW.amount END;
    IF position_effect+new_effect<0 OR position_effect+new_effect>settlement_gross THEN
        RAISE EXCEPTION 'provider components exceed gross settlement capacity';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_provider_settlement_component_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'provider settlement components are append-only';
END $$;

CREATE TRIGGER trg_provider_settlement_component_validate
    BEFORE INSERT ON public.provider_settlement_components
    FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_provider_settlement_component();
CREATE TRIGGER trg_provider_settlement_component_immutable
    BEFORE UPDATE OR DELETE ON public.provider_settlement_components
    FOR EACH ROW EXECUTE FUNCTION public.xbos_provider_settlement_component_immutable();
