CREATE TABLE public.operational_account_authorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    operational_account_id BIGINT NOT NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_operational_account_authorities_public UNIQUE (public_id),
    CONSTRAINT uq_operational_account_authorities_account UNIQUE (tenant_id, operational_account_id),
    CONSTRAINT uq_operational_account_authorities_idempotency UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT fk_operational_account_authorities_account FOREIGN KEY (tenant_id, operational_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_account_authorities_org FOREIGN KEY (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_account_authorities_actor FOREIGN KEY (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_operational_account_authorities_actor CHECK (
        actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service), '') IS NOT NULL
    ),
    CONSTRAINT ck_operational_account_authorities_identity CHECK (
        length(btrim(source_component)) > 0 AND length(btrim(source_record_id)) > 0
        AND length(btrim(idempotency_scope)) > 0 AND length(btrim(idempotency_key)) > 0
    ),
    CONSTRAINT ck_operational_account_authorities_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_operational_account_authorities_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE public.operational_account_balance_anchors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    operational_account_id BIGINT NOT NULL,
    anchor_balance NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    anchor_at TIMESTAMPTZ NOT NULL,
    provenance VARCHAR(32) NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_operational_account_balance_anchors_public UNIQUE (public_id),
    CONSTRAINT uq_operational_account_balance_anchors_account UNIQUE (tenant_id, operational_account_id),
    CONSTRAINT uq_operational_account_balance_anchors_idempotency UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT fk_operational_account_balance_anchors_account FOREIGN KEY (tenant_id, operational_account_id, currency_code)
        REFERENCES public.operational_financial_accounts(tenant_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_account_balance_anchors_org FOREIGN KEY (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_account_balance_anchors_actor FOREIGN KEY (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_operational_account_balance_anchors_provenance CHECK (
        provenance IN ('opening_import','operator_confirmed','external_confirmed')
    ),
    CONSTRAINT ck_operational_account_balance_anchors_amount CHECK (
        anchor_balance > -10000000000000000 AND anchor_balance < 10000000000000000
    ),
    CONSTRAINT ck_operational_account_balance_anchors_actor CHECK (
        actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service), '') IS NOT NULL
    ),
    CONSTRAINT ck_operational_account_balance_anchors_evidence CHECK (
        evidence_hash ~ '^[0-9a-f]{64}$' AND jsonb_typeof(evidence_payload) = 'object' AND evidence_payload <> '{}'::jsonb
    ),
    CONSTRAINT ck_operational_account_balance_anchors_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_operational_account_balance_anchors_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_operational_account_balance_anchors_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE public.operational_account_balance_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    operational_account_id BIGINT NOT NULL,
    actual_balance NUMERIC(24,8) NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    provenance VARCHAR(32) NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_operational_account_balance_observations_public UNIQUE (public_id),
    CONSTRAINT uq_operational_account_balance_observations_time UNIQUE (tenant_id, operational_account_id, observed_at),
    CONSTRAINT uq_operational_account_balance_observations_idempotency UNIQUE (tenant_id, idempotency_scope, idempotency_key),
    CONSTRAINT fk_operational_account_balance_observations_account FOREIGN KEY (tenant_id, operational_account_id, currency_code)
        REFERENCES public.operational_financial_accounts(tenant_id, id, currency_code) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_account_balance_observations_org FOREIGN KEY (tenant_id, organization_unit_id)
        REFERENCES public.organization_units(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_operational_account_balance_observations_actor FOREIGN KEY (tenant_id, actor_user_id)
        REFERENCES public.users(tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_operational_account_balance_observations_provenance CHECK (
        provenance IN ('operator_counted','external_statement','provider_confirmed')
    ),
    CONSTRAINT ck_operational_account_balance_observations_amount CHECK (
        actual_balance > -10000000000000000 AND actual_balance < 10000000000000000
    ),
    CONSTRAINT ck_operational_account_balance_observations_actor CHECK (
        actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service), '') IS NOT NULL
    ),
    CONSTRAINT ck_operational_account_balance_observations_evidence CHECK (
        evidence_hash ~ '^[0-9a-f]{64}$' AND jsonb_typeof(evidence_payload) = 'object' AND evidence_payload <> '{}'::jsonb
    ),
    CONSTRAINT ck_operational_account_balance_observations_calendar CHECK (calendar_policy_version > 0),
    CONSTRAINT ck_operational_account_balance_observations_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_operational_account_balance_observations_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_operational_balance_anchors_as_of
    ON public.operational_account_balance_anchors (tenant_id, operational_account_id, anchor_at DESC);
CREATE INDEX ix_operational_balance_observations_as_of
    ON public.operational_account_balance_observations (tenant_id, operational_account_id, observed_at DESC, id DESC);

CREATE OR REPLACE FUNCTION public.xbos_validate_operational_account_hierarchy()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE parent_row public.operational_financial_accounts%ROWTYPE;
BEGIN
    IF NEW.parent_account_id IS NOT NULL THEN
        SELECT * INTO parent_row FROM public.operational_financial_accounts
        WHERE tenant_id=NEW.tenant_id AND id=NEW.parent_account_id;
        IF NOT FOUND OR parent_row.organization_unit_id<>NEW.organization_unit_id
           OR parent_row.currency_code<>NEW.currency_code
           OR parent_row.aggregation_role<>'parent_aggregate' THEN
            RAISE EXCEPTION 'operational account parent scope, currency, or aggregation role differs'
                USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_protect_operational_account_identity()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION 'operational financial account is durable; deactivate it instead' USING ERRCODE='55000';
    END IF;
    IF ROW(NEW.public_id,NEW.tenant_id,NEW.organization_unit_id,NEW.parent_account_id,
           NEW.account_class,NEW.account_type,NEW.code,NEW.currency_code,NEW.aggregation_role,NEW.opened_at)
       IS DISTINCT FROM
       ROW(OLD.public_id,OLD.tenant_id,OLD.organization_unit_id,OLD.parent_account_id,
           OLD.account_class,OLD.account_type,OLD.code,OLD.currency_code,OLD.aggregation_role,OLD.opened_at) THEN
        RAISE EXCEPTION 'operational account identity, scope, hierarchy, currency, and opening are immutable'
            USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_operational_balance_fact()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE account_row public.operational_financial_accounts%ROWTYPE;
DECLARE fact_at TIMESTAMPTZ;
BEGIN
    SELECT * INTO account_row FROM public.operational_financial_accounts
    WHERE tenant_id=NEW.tenant_id AND id=NEW.operational_account_id FOR SHARE;
    IF TG_TABLE_NAME='operational_account_balance_anchors' THEN
        fact_at := NEW.anchor_at;
    ELSIF TG_TABLE_NAME='operational_account_balance_observations' THEN
        fact_at := NEW.observed_at;
    ELSE
        RAISE EXCEPTION 'unexpected operational balance fact trigger table: %', TG_TABLE_NAME
            USING ERRCODE='55000';
    END IF;
    IF NOT FOUND OR account_row.organization_unit_id<>NEW.organization_unit_id
       OR account_row.currency_code<>NEW.currency_code OR account_row.aggregation_role<>'leaf' THEN
        RAISE EXCEPTION 'balance fact account scope, currency, or aggregation role differs' USING ERRCODE='23514';
    END IF;
    IF fact_at<account_row.opened_at OR (account_row.closed_at IS NOT NULL AND fact_at>account_row.closed_at) THEN
        RAISE EXCEPTION 'balance fact falls outside operational account lifetime' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_operational_account_hierarchy
BEFORE INSERT OR UPDATE ON public.operational_financial_accounts
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_operational_account_hierarchy();
CREATE TRIGGER trg_operational_account_identity
BEFORE UPDATE OR DELETE ON public.operational_financial_accounts
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_operational_account_identity();
CREATE TRIGGER trg_operational_balance_anchor_validate
BEFORE INSERT ON public.operational_account_balance_anchors
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_operational_balance_fact();
CREATE TRIGGER trg_operational_balance_observation_validate
BEFORE INSERT ON public.operational_account_balance_observations
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_operational_balance_fact();
CREATE TRIGGER trg_operational_account_authority_immutable
BEFORE UPDATE OR DELETE ON public.operational_account_authorities
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_financial_mutation();
CREATE TRIGGER trg_operational_balance_anchor_immutable
BEFORE UPDATE OR DELETE ON public.operational_account_balance_anchors
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_financial_mutation();
CREATE TRIGGER trg_operational_balance_observation_immutable
BEFORE UPDATE OR DELETE ON public.operational_account_balance_observations
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_immutable_financial_mutation();
