CREATE TABLE public.reconciliation_calendar_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    policy_code VARCHAR(80) NOT NULL,
    policy_version INTEGER NOT NULL,
    timezone_name VARCHAR(80) NOT NULL,
    business_day_boundary TIME NOT NULL,
    shift_definitions JSONB NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_calendar_policy_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_calendar_policy_version UNIQUE(tenant_id,organization_unit_id,policy_code,policy_version),
    CONSTRAINT uq_reconciliation_calendar_policy_idempotency UNIQUE(tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_reconciliation_calendar_policy_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_calendar_policy_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_calendar_policy_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_calendar_policy_values CHECK(
        policy_version>0 AND calendar_policy_version>0
        AND length(btrim(policy_code))>0 AND length(btrim(timezone_name))>0
        AND jsonb_typeof(shift_definitions)='array' AND jsonb_array_length(shift_definitions)>0
        AND request_fingerprint~'^[0-9a-f]{64}$' AND jsonb_typeof(metadata)='object'
        AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
        AND length(btrim(source_component))>0 AND length(btrim(source_record_id))>0
        AND length(btrim(idempotency_scope))>0 AND length(btrim(idempotency_key))>0
    )
);

CREATE TABLE public.reconciliation_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    operational_account_id BIGINT NOT NULL,
    calendar_policy_id BIGINT NOT NULL,
    series_code VARCHAR(80) NOT NULL,
    currency_code VARCHAR(12) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_series_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_series_account UNIQUE(tenant_id,operational_account_id),
    CONSTRAINT uq_reconciliation_series_code UNIQUE(tenant_id,organization_unit_id,series_code),
    CONSTRAINT uq_reconciliation_series_idempotency UNIQUE(tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_reconciliation_series_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_series_account FOREIGN KEY(tenant_id,operational_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_series_policy FOREIGN KEY(tenant_id,calendar_policy_id)
        REFERENCES public.reconciliation_calendar_policies(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_series_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_series_currency FOREIGN KEY(currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_series_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_series_values CHECK(
        calendar_policy_version>0 AND length(btrim(series_code))>0
        AND currency_code~'^[A-Z][A-Z0-9_]{2,11}$' AND request_fingerprint~'^[0-9a-f]{64}$'
        AND jsonb_typeof(metadata)='object' AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
        AND length(btrim(source_component))>0 AND length(btrim(source_record_id))>0
        AND length(btrim(idempotency_scope))>0 AND length(btrim(idempotency_key))>0
    )
);

CREATE TABLE public.reconciliation_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    reconciliation_series_id BIGINT NOT NULL,
    predecessor_window_id BIGINT NULL,
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    business_date DATE NOT NULL,
    shift_code VARCHAR(40) NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_window_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_window_range UNIQUE(tenant_id,reconciliation_series_id,window_start,window_end),
    CONSTRAINT uq_reconciliation_window_predecessor UNIQUE(predecessor_window_id),
    CONSTRAINT uq_reconciliation_window_idempotency UNIQUE(tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_reconciliation_window_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_window_series FOREIGN KEY(tenant_id,reconciliation_series_id)
        REFERENCES public.reconciliation_series(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_predecessor FOREIGN KEY(tenant_id,predecessor_window_id)
        REFERENCES public.reconciliation_windows(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_window_values CHECK(
        window_end>window_start AND calendar_policy_version>0 AND length(btrim(shift_code))>0
        AND evidence_hash~'^[0-9a-f]{64}$' AND jsonb_typeof(evidence_payload)='object' AND evidence_payload<>'{}'::jsonb
        AND request_fingerprint~'^[0-9a-f]{64}$' AND jsonb_typeof(metadata)='object'
        AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
        AND length(btrim(source_component))>0 AND length(btrim(source_record_id))>0
        AND length(btrim(idempotency_scope))>0 AND length(btrim(idempotency_key))>0
    )
);

CREATE TABLE public.reconciliation_cascade_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    reconciliation_series_id BIGINT NOT NULL,
    changed_from_at TIMESTAMPTZ NOT NULL,
    cascade_reason VARCHAR(40) NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_cascade_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_cascade_idempotency UNIQUE(tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_reconciliation_cascade_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_cascade_series FOREIGN KEY(tenant_id,reconciliation_series_id)
        REFERENCES public.reconciliation_series(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_cascade_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_cascade_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_cascade_values CHECK(
        cascade_reason IN('financial_fact_appended','balance_observation_appended','authorized_recalculation')
        AND calendar_policy_version>0 AND evidence_hash~'^[0-9a-f]{64}$'
        AND jsonb_typeof(evidence_payload)='object' AND evidence_payload<>'{}'::jsonb
        AND request_fingerprint~'^[0-9a-f]{64}$' AND jsonb_typeof(metadata)='object'
        AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
        AND length(btrim(source_component))>0 AND length(btrim(source_record_id))>0
        AND length(btrim(idempotency_scope))>0 AND length(btrim(idempotency_key))>0
    )
);

CREATE TABLE public.reconciliation_window_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    reconciliation_window_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    revision_reason VARCHAR(40) NOT NULL,
    opening_expected NUMERIC(24,8) NOT NULL,
    closing_expected NUMERIC(24,8) NOT NULL,
    actual_closing NUMERIC(24,8) NULL,
    variance NUMERIC(24,8) NULL,
    readiness_condition VARCHAR(24) NOT NULL,
    actual_observation_id BIGINT NULL,
    supersedes_revision_id BIGINT NULL,
    cascade_run_id BIGINT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_window_revision_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_window_revision_number UNIQUE(tenant_id,reconciliation_window_id,revision_number),
    CONSTRAINT uq_reconciliation_window_revision_supersedes UNIQUE(supersedes_revision_id),
    CONSTRAINT uq_reconciliation_window_revision_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_window_revision_window FOREIGN KEY(tenant_id,reconciliation_window_id)
        REFERENCES public.reconciliation_windows(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_revision_actual FOREIGN KEY(actual_observation_id)
        REFERENCES public.operational_account_balance_observations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_revision_supersedes FOREIGN KEY(tenant_id,supersedes_revision_id)
        REFERENCES public.reconciliation_window_revisions(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_revision_cascade FOREIGN KEY(tenant_id,cascade_run_id)
        REFERENCES public.reconciliation_cascade_runs(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_revision_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_window_revision_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_window_revision_values CHECK(
        revision_number>0 AND revision_reason IN('initial','correction_cascade')
        AND readiness_condition IN('awaiting_actual','ready')
        AND ((actual_closing IS NULL AND variance IS NULL AND actual_observation_id IS NULL AND readiness_condition='awaiting_actual')
          OR (actual_closing IS NOT NULL AND variance=actual_closing-closing_expected AND actual_observation_id IS NOT NULL AND readiness_condition='ready'))
        AND ((revision_number=1 AND supersedes_revision_id IS NULL AND cascade_run_id IS NULL AND revision_reason='initial')
          OR (revision_number>1 AND supersedes_revision_id IS NOT NULL AND cascade_run_id IS NOT NULL AND revision_reason='correction_cascade'))
        AND jsonb_typeof(metadata)='object' AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
        AND length(btrim(source_component))>0 AND length(btrim(source_record_id))>0
    )
);

CREATE INDEX ix_reconciliation_windows_series_end ON public.reconciliation_windows(tenant_id,reconciliation_series_id,window_end,id);
CREATE INDEX ix_reconciliation_revisions_window ON public.reconciliation_window_revisions(tenant_id,reconciliation_window_id,revision_number DESC,id DESC);
CREATE INDEX ix_reconciliation_cascades_series_changed ON public.reconciliation_cascade_runs(tenant_id,reconciliation_series_id,changed_from_at,id);

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_calendar_policy()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_boundary TEXT;
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_timezone_names WHERE name=NEW.timezone_name) THEN
        RAISE EXCEPTION 'reconciliation calendar timezone is unknown' USING ERRCODE='23514';
    END IF;
    IF EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.shift_definitions) item
              WHERE NULLIF(btrim(item->>'code'),'') IS NULL
                 OR NOT COALESCE((item->>'starts_at')~'^([01][0-9]|2[0-3]):[0-5][0-9]$',FALSE)) THEN
        RAISE EXCEPTION 'reconciliation shift definitions are invalid' USING ERRCODE='23514';
    END IF;
    IF (SELECT count(*) FROM jsonb_array_elements(NEW.shift_definitions))
       <> (SELECT count(DISTINCT item->>'code') FROM jsonb_array_elements(NEW.shift_definitions) item)
       OR (SELECT count(*) FROM jsonb_array_elements(NEW.shift_definitions))
       <> (SELECT count(DISTINCT item->>'starts_at') FROM jsonb_array_elements(NEW.shift_definitions) item) THEN
        RAISE EXCEPTION 'reconciliation shift codes and boundaries must be unique' USING ERRCODE='23514';
    END IF;
    selected_boundary := to_char(NEW.business_day_boundary,'HH24:MI');
    IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.shift_definitions) item
                  WHERE item->>'starts_at'=selected_boundary) THEN
        RAISE EXCEPTION 'business-day boundary must begin a reconciliation shift' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_series()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_account public.operational_financial_accounts%ROWTYPE;
DECLARE selected_policy public.reconciliation_calendar_policies%ROWTYPE;
DECLARE local_start TEXT;
BEGIN
    SELECT * INTO selected_account FROM public.operational_financial_accounts
    WHERE tenant_id=NEW.tenant_id AND id=NEW.operational_account_id FOR SHARE;
    SELECT * INTO selected_policy FROM public.reconciliation_calendar_policies
    WHERE tenant_id=NEW.tenant_id AND id=NEW.calendar_policy_id FOR SHARE;
    IF selected_account.id IS NULL OR selected_policy.id IS NULL
       OR selected_account.organization_unit_id<>NEW.organization_unit_id
       OR selected_policy.organization_unit_id<>NEW.organization_unit_id
       OR selected_account.currency_code<>NEW.currency_code
       OR selected_policy.policy_version<>NEW.calendar_policy_version
       OR NOT selected_account.active OR NOT selected_account.reconciliation_enabled
       OR selected_account.aggregation_role<>'leaf' THEN
        RAISE EXCEPTION 'reconciliation series account, policy, scope, or currency is invalid' USING ERRCODE='23514';
    END IF;
    local_start := to_char(NEW.starts_at AT TIME ZONE selected_policy.timezone_name,'HH24:MI');
    IF NEW.starts_at<selected_account.opened_at OR NEW.starts_at<selected_policy.effective_from
       OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(selected_policy.shift_definitions) item
                     WHERE item->>'starts_at'=local_start) THEN
        RAISE EXCEPTION 'reconciliation series start is outside authority or not shift-aligned' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_window_continuity()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_series public.reconciliation_series%ROWTYPE;
DECLARE latest public.reconciliation_windows%ROWTYPE;
DECLARE selected_policy public.reconciliation_calendar_policies%ROWTYPE;
DECLARE local_start TIMESTAMP;
DECLARE local_clock TEXT;
DECLARE selected_shift TEXT;
DECLARE next_clock TIME;
DECLARE next_day INTEGER;
DECLARE expected_end TIMESTAMPTZ;
DECLARE expected_business_date DATE;
BEGIN
    SELECT * INTO selected_series FROM public.reconciliation_series
    WHERE tenant_id=NEW.tenant_id AND id=NEW.reconciliation_series_id FOR UPDATE;
    IF NOT FOUND OR selected_series.organization_unit_id<>NEW.organization_unit_id THEN
        RAISE EXCEPTION 'reconciliation window series is missing or cross-scope' USING ERRCODE='23514';
    END IF;
    SELECT * INTO selected_policy FROM public.reconciliation_calendar_policies
    WHERE tenant_id=NEW.tenant_id AND id=selected_series.calendar_policy_id;
    IF selected_policy.policy_version<>NEW.calendar_policy_version THEN
        RAISE EXCEPTION 'reconciliation window calendar version differs from series policy' USING ERRCODE='23514';
    END IF;
    local_start := NEW.window_start AT TIME ZONE selected_policy.timezone_name;
    local_clock := to_char(local_start,'HH24:MI');
    SELECT item->>'code' INTO selected_shift FROM jsonb_array_elements(selected_policy.shift_definitions) item
    WHERE item->>'starts_at'=local_clock;
    IF selected_shift IS NULL THEN
        RAISE EXCEPTION 'reconciliation window start is not a configured shift boundary' USING ERRCODE='23514';
    END IF;
    SELECT min((item->>'starts_at')::TIME) INTO next_clock
    FROM jsonb_array_elements(selected_policy.shift_definitions) item
    WHERE (item->>'starts_at')::TIME>local_clock::TIME;
    next_day := 0;
    IF next_clock IS NULL THEN
        SELECT min((item->>'starts_at')::TIME) INTO next_clock FROM jsonb_array_elements(selected_policy.shift_definitions) item;
        next_day := 1;
    END IF;
    expected_end := ((local_start::DATE+next_day)+next_clock) AT TIME ZONE selected_policy.timezone_name;
    expected_business_date := local_start::DATE;
    IF local_clock::TIME<selected_policy.business_day_boundary THEN
        expected_business_date := expected_business_date-1;
    END IF;
    IF NEW.window_end<>expected_end OR NEW.shift_code<>selected_shift OR NEW.business_date<>expected_business_date THEN
        RAISE EXCEPTION 'reconciliation window end, shift, or business date conflicts with calendar authority' USING ERRCODE='23514';
    END IF;
    SELECT * INTO latest FROM public.reconciliation_windows
    WHERE tenant_id=NEW.tenant_id AND reconciliation_series_id=NEW.reconciliation_series_id
    ORDER BY window_start DESC,id DESC LIMIT 1 FOR UPDATE;
    IF NOT FOUND THEN
        IF NEW.predecessor_window_id IS NOT NULL OR NEW.window_start<>selected_series.starts_at THEN
            RAISE EXCEPTION 'first reconciliation window must start the series without a predecessor' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.predecessor_window_id IS DISTINCT FROM latest.id OR NEW.window_start<>latest.window_end THEN
        RAISE EXCEPTION 'reconciliation windows must be contiguous and name the latest predecessor' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_cascade()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_series public.reconciliation_series%ROWTYPE;
DECLARE selected_policy public.reconciliation_calendar_policies%ROWTYPE;
BEGIN
    SELECT * INTO selected_series FROM public.reconciliation_series
    WHERE tenant_id=NEW.tenant_id AND id=NEW.reconciliation_series_id FOR UPDATE;
    IF NOT FOUND OR selected_series.organization_unit_id<>NEW.organization_unit_id THEN
        RAISE EXCEPTION 'reconciliation cascade series is missing or cross-scope' USING ERRCODE='23514';
    END IF;
    SELECT * INTO selected_policy FROM public.reconciliation_calendar_policies
    WHERE tenant_id=NEW.tenant_id AND id=selected_series.calendar_policy_id;
    IF selected_policy.policy_version<>NEW.calendar_policy_version THEN
        RAISE EXCEPTION 'reconciliation cascade calendar version differs from series policy' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_revision_sequence()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_window public.reconciliation_windows%ROWTYPE;
DECLARE latest public.reconciliation_window_revisions%ROWTYPE;
DECLARE selected_series public.reconciliation_series%ROWTYPE;
DECLARE selected_observation public.operational_account_balance_observations%ROWTYPE;
DECLARE selected_cascade public.reconciliation_cascade_runs%ROWTYPE;
BEGIN
    SELECT * INTO selected_window FROM public.reconciliation_windows
    WHERE tenant_id=NEW.tenant_id AND id=NEW.reconciliation_window_id FOR UPDATE;
    IF NOT FOUND OR selected_window.organization_unit_id<>NEW.organization_unit_id THEN
        RAISE EXCEPTION 'reconciliation revision window is missing or cross-scope' USING ERRCODE='23514';
    END IF;
    SELECT * INTO selected_series FROM public.reconciliation_series
    WHERE tenant_id=NEW.tenant_id AND id=selected_window.reconciliation_series_id;
    IF NEW.actual_observation_id IS NOT NULL THEN
        SELECT * INTO selected_observation FROM public.operational_account_balance_observations
        WHERE id=NEW.actual_observation_id;
        IF NOT FOUND OR selected_observation.tenant_id<>NEW.tenant_id
           OR selected_observation.operational_account_id<>selected_series.operational_account_id
           OR selected_observation.observed_at<=selected_window.window_start
           OR selected_observation.observed_at>selected_window.window_end THEN
            RAISE EXCEPTION 'reconciliation actual observation is outside the window account scope' USING ERRCODE='23514';
        END IF;
    END IF;
    IF NEW.cascade_run_id IS NOT NULL THEN
        SELECT * INTO selected_cascade FROM public.reconciliation_cascade_runs
        WHERE tenant_id=NEW.tenant_id AND id=NEW.cascade_run_id;
        IF NOT FOUND OR selected_cascade.reconciliation_series_id<>selected_window.reconciliation_series_id THEN
            RAISE EXCEPTION 'reconciliation revision cascade run belongs to another series' USING ERRCODE='23514';
        END IF;
    END IF;
    SELECT * INTO latest FROM public.reconciliation_window_revisions
    WHERE tenant_id=NEW.tenant_id AND reconciliation_window_id=NEW.reconciliation_window_id
    ORDER BY revision_number DESC,id DESC LIMIT 1 FOR UPDATE;
    IF NOT FOUND THEN
        IF NEW.revision_number<>1 OR NEW.supersedes_revision_id IS NOT NULL OR NEW.cascade_run_id IS NOT NULL THEN
            RAISE EXCEPTION 'first reconciliation revision must be revision one' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.revision_number<>latest.revision_number+1 OR NEW.supersedes_revision_id IS DISTINCT FROM latest.id
          OR NEW.cascade_run_id IS NULL THEN
        RAISE EXCEPTION 'reconciliation revisions must append in order and supersede the latest revision' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_reject_reconciliation_fact_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accepted reconciliation control facts are immutable' USING ERRCODE='23514';
END $$;

CREATE TRIGGER tr_reconciliation_window_continuity BEFORE INSERT ON public.reconciliation_windows
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_window_continuity();
CREATE TRIGGER tr_reconciliation_revision_sequence BEFORE INSERT ON public.reconciliation_window_revisions
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_revision_sequence();
CREATE TRIGGER tr_reconciliation_calendar_validate BEFORE INSERT ON public.reconciliation_calendar_policies
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_calendar_policy();
CREATE TRIGGER tr_reconciliation_series_validate BEFORE INSERT ON public.reconciliation_series
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_series();
CREATE TRIGGER tr_reconciliation_cascade_validate BEFORE INSERT ON public.reconciliation_cascade_runs
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_cascade();

CREATE TRIGGER tr_reconciliation_calendar_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_calendar_policies
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_fact_mutation();
CREATE TRIGGER tr_reconciliation_series_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_series
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_fact_mutation();
CREATE TRIGGER tr_reconciliation_windows_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_windows
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_fact_mutation();
CREATE TRIGGER tr_reconciliation_cascades_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_cascade_runs
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_fact_mutation();
CREATE TRIGGER tr_reconciliation_revisions_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_window_revisions
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_fact_mutation();

CREATE VIEW public.current_reconciliation_window_revisions AS
SELECT DISTINCT ON (r.tenant_id,r.reconciliation_window_id)
       r.*,w.reconciliation_series_id,w.predecessor_window_id,w.window_start,w.window_end,w.business_date,w.shift_code,
       o.observed_at AS actual_observed_at,o.provenance AS actual_provenance,o.evidence_hash AS actual_evidence_hash
FROM public.reconciliation_window_revisions r
JOIN public.reconciliation_windows w ON w.tenant_id=r.tenant_id AND w.id=r.reconciliation_window_id
LEFT JOIN public.operational_account_balance_observations o ON o.id=r.actual_observation_id
ORDER BY r.tenant_id,r.reconciliation_window_id,r.revision_number DESC,r.id DESC;
