DROP VIEW IF EXISTS public.current_reconciliation_window_revisions;
DROP TRIGGER IF EXISTS tr_reconciliation_revisions_immutable ON public.reconciliation_window_revisions;
DROP TRIGGER IF EXISTS tr_reconciliation_cascades_immutable ON public.reconciliation_cascade_runs;
DROP TRIGGER IF EXISTS tr_reconciliation_windows_immutable ON public.reconciliation_windows;
DROP TRIGGER IF EXISTS tr_reconciliation_series_immutable ON public.reconciliation_series;
DROP TRIGGER IF EXISTS tr_reconciliation_calendar_immutable ON public.reconciliation_calendar_policies;
DROP TRIGGER IF EXISTS tr_reconciliation_revision_sequence ON public.reconciliation_window_revisions;
DROP TRIGGER IF EXISTS tr_reconciliation_window_continuity ON public.reconciliation_windows;
DROP TRIGGER IF EXISTS tr_reconciliation_series_validate ON public.reconciliation_series;
DROP TRIGGER IF EXISTS tr_reconciliation_calendar_validate ON public.reconciliation_calendar_policies;
DROP TRIGGER IF EXISTS tr_reconciliation_cascade_validate ON public.reconciliation_cascade_runs;
DROP FUNCTION IF EXISTS public.xbos_reject_reconciliation_fact_mutation();
DROP FUNCTION IF EXISTS public.xbos_validate_reconciliation_revision_sequence();
DROP FUNCTION IF EXISTS public.xbos_validate_reconciliation_window_continuity();
DROP FUNCTION IF EXISTS public.xbos_validate_reconciliation_cascade();
DROP FUNCTION IF EXISTS public.xbos_validate_reconciliation_series();
DROP FUNCTION IF EXISTS public.xbos_validate_reconciliation_calendar_policy();
DROP TABLE IF EXISTS public.reconciliation_window_revisions;
DROP TABLE IF EXISTS public.reconciliation_cascade_runs;
DROP TABLE IF EXISTS public.reconciliation_windows;
DROP TABLE IF EXISTS public.reconciliation_series;
DROP TABLE IF EXISTS public.reconciliation_calendar_policies;
