CREATE TABLE public.reconciliation_window_governance_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    reconciliation_window_id BIGINT NOT NULL,
    transition_type VARCHAR(16) NOT NULL,
    prior_event_id BIGINT NULL,
    governed_revision_id BIGINT NOT NULL,
    governed_revision_number INTEGER NOT NULL,
    accounting_period_id BIGINT NOT NULL,
    accounting_period_code VARCHAR(32) NOT NULL,
    accounting_period_state VARCHAR(16) NOT NULL,
    close_disposition VARCHAR(32) NULL,
    transition_reason VARCHAR(191) NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_payload JSONB NOT NULL,
    approved_by_user_id INTEGER NULL,
    approved_at TIMESTAMPTZ NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_governance_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_governance_idempotency UNIQUE(tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_reconciliation_governance_prior UNIQUE(prior_event_id),
    CONSTRAINT uq_reconciliation_governance_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_governance_window FOREIGN KEY(tenant_id,reconciliation_window_id)
        REFERENCES public.reconciliation_windows(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_governance_prior FOREIGN KEY(tenant_id,prior_event_id)
        REFERENCES public.reconciliation_window_governance_events(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_governance_revision FOREIGN KEY(tenant_id,governed_revision_id)
        REFERENCES public.reconciliation_window_revisions(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_governance_period FOREIGN KEY(tenant_id,accounting_period_id)
        REFERENCES public.accounting_periods(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_governance_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_governance_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_governance_approver FOREIGN KEY(tenant_id,approved_by_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_governance_values CHECK(
        transition_type IN('close','reopen') AND governed_revision_number>0
        AND accounting_period_state IN('open','reopened')
        AND length(btrim(accounting_period_code))>0 AND length(btrim(transition_reason))>0
        AND evidence_hash~'^[0-9a-f]{64}$' AND jsonb_typeof(evidence_payload)='object'
        AND evidence_payload<>'{}'::jsonb AND calendar_policy_version>0
        AND request_fingerprint~'^[0-9a-f]{64}$' AND jsonb_typeof(metadata)='object'
        AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
        AND length(btrim(source_component))>0 AND length(btrim(source_record_id))>0
        AND length(btrim(idempotency_scope))>0 AND length(btrim(idempotency_key))>0
        AND ((transition_type='close' AND close_disposition IN('balanced','explained_variance','approved_exception')
              AND approved_by_user_id IS NULL AND approved_at IS NULL)
          OR (transition_type='reopen' AND close_disposition IS NULL
              AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL))
    )
);

CREATE INDEX ix_reconciliation_governance_window
    ON public.reconciliation_window_governance_events(tenant_id,reconciliation_window_id,id DESC);
CREATE INDEX ix_reconciliation_governance_period
    ON public.reconciliation_window_governance_events(tenant_id,accounting_period_id,id DESC);

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_governance_transition()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_window public.reconciliation_windows%ROWTYPE;
DECLARE selected_revision public.reconciliation_window_revisions%ROWTYPE;
DECLARE latest_revision public.reconciliation_window_revisions%ROWTYPE;
DECLARE selected_period public.accounting_periods%ROWTYPE;
DECLARE latest_event public.reconciliation_window_governance_events%ROWTYPE;
DECLARE predecessor_event public.reconciliation_window_governance_events%ROWTYPE;
DECLARE selected_approver INTEGER;
BEGIN
    SELECT * INTO selected_window FROM public.reconciliation_windows
    WHERE tenant_id=NEW.tenant_id AND id=NEW.reconciliation_window_id FOR UPDATE;
    IF NOT FOUND OR selected_window.organization_unit_id<>NEW.organization_unit_id
       OR selected_window.business_date<>NEW.business_date
       OR selected_window.calendar_policy_version<>NEW.calendar_policy_version THEN
        RAISE EXCEPTION 'reconciliation governance window scope is invalid' USING ERRCODE='23514';
    END IF;

    SELECT * INTO selected_revision FROM public.reconciliation_window_revisions
    WHERE tenant_id=NEW.tenant_id AND id=NEW.governed_revision_id;
    SELECT * INTO latest_revision FROM public.reconciliation_window_revisions
    WHERE tenant_id=NEW.tenant_id AND reconciliation_window_id=NEW.reconciliation_window_id
    ORDER BY revision_number DESC,id DESC LIMIT 1 FOR UPDATE;
    IF selected_revision.id IS NULL OR latest_revision.id IS NULL
       OR selected_revision.reconciliation_window_id<>NEW.reconciliation_window_id
       OR selected_revision.id<>latest_revision.id
       OR selected_revision.revision_number<>NEW.governed_revision_number THEN
        RAISE EXCEPTION 'governance transition must target the current reconciliation revision' USING ERRCODE='23514';
    END IF;

    SELECT * INTO selected_period FROM public.accounting_periods
    WHERE tenant_id=NEW.tenant_id AND id=NEW.accounting_period_id FOR SHARE;
    IF NOT FOUND OR selected_period.legal_entity_unit_id<>NEW.organization_unit_id
       OR selected_window.business_date<selected_period.period_start
       OR selected_window.business_date>selected_period.period_end
       OR selected_period.period_code<>NEW.accounting_period_code
       OR selected_period.period_state<>NEW.accounting_period_state
       OR selected_period.period_state NOT IN('open','reopened') THEN
        RAISE EXCEPTION 'accounting period is missing, closed, or outside window authority' USING ERRCODE='23514';
    END IF;

    SELECT * INTO latest_event FROM public.reconciliation_window_governance_events
    WHERE tenant_id=NEW.tenant_id AND reconciliation_window_id=NEW.reconciliation_window_id
    ORDER BY id DESC LIMIT 1 FOR UPDATE;
    IF NOT FOUND THEN
        IF NEW.transition_type<>'close' OR NEW.prior_event_id IS NOT NULL THEN
            RAISE EXCEPTION 'first reconciliation governance transition must be close' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.prior_event_id IS DISTINCT FROM latest_event.id
       OR (latest_event.transition_type='close' AND NEW.transition_type<>'reopen')
       OR (latest_event.transition_type='reopen' AND NEW.transition_type<>'close') THEN
        RAISE EXCEPTION 'reconciliation close and reopen transitions must alternate from the latest event' USING ERRCODE='23514';
    END IF;

    IF NEW.transition_type='close' THEN
        IF selected_revision.readiness_condition<>'ready' THEN
            RAISE EXCEPTION 'reconciliation window is not ready for formal close' USING ERRCODE='23514';
        END IF;
        IF (COALESCE(selected_revision.variance,0)=0 AND NEW.close_disposition<>'balanced')
           OR (COALESCE(selected_revision.variance,0)<>0 AND NEW.close_disposition='balanced') THEN
            RAISE EXCEPTION 'close disposition conflicts with the current variance' USING ERRCODE='23514';
        END IF;
        IF selected_window.predecessor_window_id IS NOT NULL THEN
            SELECT * INTO predecessor_event FROM public.reconciliation_window_governance_events
            WHERE tenant_id=NEW.tenant_id AND reconciliation_window_id=selected_window.predecessor_window_id
            ORDER BY id DESC LIMIT 1;
            IF NOT FOUND OR predecessor_event.transition_type<>'close' THEN
                RAISE EXCEPTION 'required predecessor window is not formally closed' USING ERRCODE='23514';
            END IF;
        END IF;
    ELSE
        SELECT id INTO selected_approver FROM public.users
        WHERE tenant_id=NEW.tenant_id AND id=NEW.approved_by_user_id;
        IF selected_approver IS NULL OR NEW.approved_at>NEW.occurred_at THEN
            RAISE EXCEPTION 'reopen approval is invalid or cross-tenant' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_reject_reconciliation_governance_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accepted reconciliation close and reopen history is immutable' USING ERRCODE='23514';
END $$;

CREATE OR REPLACE FUNCTION public.xbos_assert_reconciliation_window_open(
    selected_tenant INTEGER, selected_account BIGINT, selected_at TIMESTAMPTZ
) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF selected_account IS NULL OR selected_at IS NULL THEN RETURN; END IF;
    IF EXISTS(
        SELECT 1
        FROM public.reconciliation_windows w
        JOIN public.reconciliation_series s
          ON s.tenant_id=w.tenant_id AND s.id=w.reconciliation_series_id
        JOIN LATERAL (
            SELECT transition_type FROM public.reconciliation_window_governance_events g
            WHERE g.tenant_id=w.tenant_id AND g.reconciliation_window_id=w.id
            ORDER BY g.id DESC LIMIT 1
        ) state ON TRUE
        WHERE w.tenant_id=selected_tenant AND s.operational_account_id=selected_account
          AND selected_at>=w.window_start AND selected_at<=w.window_end
          AND state.transition_type='close'
    ) THEN
        RAISE EXCEPTION 'operational fact falls within a formally closed reconciliation window' USING ERRCODE='23514';
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_protect_closed_reconciliation_window_fact()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME='operational_account_balance_anchors' THEN
        PERFORM public.xbos_assert_reconciliation_window_open(NEW.tenant_id,NEW.operational_account_id,NEW.anchor_at);
    ELSIF TG_TABLE_NAME='operational_account_balance_observations' THEN
        PERFORM public.xbos_assert_reconciliation_window_open(NEW.tenant_id,NEW.operational_account_id,NEW.observed_at);
    ELSIF TG_TABLE_NAME='financial_events' THEN
        PERFORM public.xbos_assert_reconciliation_window_open(NEW.tenant_id,NEW.source_operational_account_id,NEW.occurred_at);
        PERFORM public.xbos_assert_reconciliation_window_open(NEW.tenant_id,NEW.target_operational_account_id,NEW.occurred_at);
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_protect_closed_reconciliation_cascade()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS(
        SELECT 1 FROM public.reconciliation_windows w
        JOIN LATERAL (
            SELECT transition_type FROM public.reconciliation_window_governance_events g
            WHERE g.tenant_id=w.tenant_id AND g.reconciliation_window_id=w.id
            ORDER BY g.id DESC LIMIT 1
        ) state ON TRUE
        WHERE w.tenant_id=NEW.tenant_id AND w.reconciliation_series_id=NEW.reconciliation_series_id
          AND w.window_end>=NEW.changed_from_at AND state.transition_type='close'
    ) THEN
        RAISE EXCEPTION 'correction cascade intersects a formally closed reconciliation window' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_protect_closed_reconciliation_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS(
        SELECT 1 FROM public.reconciliation_window_governance_events g
        WHERE g.tenant_id=NEW.tenant_id AND g.reconciliation_window_id=NEW.reconciliation_window_id
          AND g.transition_type='close'
          AND g.id=(SELECT max(g2.id) FROM public.reconciliation_window_governance_events g2
                    WHERE g2.tenant_id=NEW.tenant_id AND g2.reconciliation_window_id=NEW.reconciliation_window_id)
    ) THEN
        RAISE EXCEPTION 'cannot append a revision to a formally closed reconciliation window' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER tr_reconciliation_governance_validate
BEFORE INSERT ON public.reconciliation_window_governance_events
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_governance_transition();
CREATE TRIGGER tr_reconciliation_governance_immutable
BEFORE UPDATE OR DELETE ON public.reconciliation_window_governance_events
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_governance_mutation();
CREATE TRIGGER tr_closed_window_anchor_protection
BEFORE INSERT ON public.operational_account_balance_anchors
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_closed_reconciliation_window_fact();
CREATE TRIGGER tr_closed_window_observation_protection
BEFORE INSERT ON public.operational_account_balance_observations
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_closed_reconciliation_window_fact();
CREATE TRIGGER tr_closed_window_financial_event_protection
BEFORE INSERT ON public.financial_events
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_closed_reconciliation_window_fact();
CREATE TRIGGER tr_closed_window_cascade_protection
BEFORE INSERT ON public.reconciliation_cascade_runs
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_closed_reconciliation_cascade();
CREATE TRIGGER tr_closed_window_revision_protection
BEFORE INSERT ON public.reconciliation_window_revisions
FOR EACH ROW EXECUTE FUNCTION public.xbos_protect_closed_reconciliation_revision();

CREATE VIEW public.current_reconciliation_window_governance AS
SELECT DISTINCT ON (g.tenant_id,g.reconciliation_window_id)
       g.*,CASE WHEN g.transition_type='close' THEN 'closed' ELSE 'reopened' END AS governance_state,
       w.reconciliation_series_id,w.predecessor_window_id,w.window_start,w.window_end,w.shift_code,
       r.opening_expected,r.closing_expected,r.actual_closing,r.variance,r.readiness_condition
FROM public.reconciliation_window_governance_events g
JOIN public.reconciliation_windows w
  ON w.tenant_id=g.tenant_id AND w.id=g.reconciliation_window_id
JOIN public.reconciliation_window_revisions r
  ON r.tenant_id=g.tenant_id AND r.id=g.governed_revision_id
ORDER BY g.tenant_id,g.reconciliation_window_id,g.id DESC;
