CREATE TABLE public.reconciliation_controls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    control_type VARCHAR(24) NOT NULL,
    operational_account_id BIGINT NULL,
    party_id UUID NULL,
    reconciliation_window_id BIGINT NULL,
    accounting_period_id BIGINT NULL,
    currency_code VARCHAR(12) NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    as_of TIMESTAMPTZ NOT NULL,
    canonical_opening NUMERIC(24,8) NOT NULL,
    canonical_increases NUMERIC(24,8) NOT NULL,
    canonical_decreases NUMERIC(24,8) NOT NULL,
    canonical_adjustments NUMERIC(24,8) NOT NULL,
    canonical_closing NUMERIC(24,8) NOT NULL,
    control_position NUMERIC(24,8) NOT NULL,
    explained_amount NUMERIC(24,8) NOT NULL,
    raw_variance NUMERIC(24,8) NOT NULL,
    unexplained_variance NUMERIC(24,8) NOT NULL,
    reconciliation_status VARCHAR(16) NOT NULL,
    revision_number INTEGER NOT NULL,
    supersedes_control_id BIGINT NULL,
    governed_window_revision_id BIGINT NULL,
    governed_window_revision_number INTEGER NULL,
    window_governance_state VARCHAR(16) NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_date DATE NOT NULL,
    calendar_policy_version INTEGER NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(191) NOT NULL,
    idempotency_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    semantic_fingerprint CHAR(64) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_reconciliation_controls_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_controls_idempotency UNIQUE(tenant_id,idempotency_scope,idempotency_key),
    CONSTRAINT uq_reconciliation_controls_supersedes UNIQUE(supersedes_control_id),
    CONSTRAINT uq_reconciliation_controls_tenant_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_reconciliation_controls_org FOREIGN KEY(tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_account FOREIGN KEY(tenant_id,operational_account_id)
        REFERENCES public.operational_financial_accounts(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_window FOREIGN KEY(tenant_id,reconciliation_window_id)
        REFERENCES public.reconciliation_windows(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_period FOREIGN KEY(tenant_id,accounting_period_id)
        REFERENCES public.accounting_periods(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_supersedes FOREIGN KEY(tenant_id,supersedes_control_id)
        REFERENCES public.reconciliation_controls(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_window_revision FOREIGN KEY(tenant_id,governed_window_revision_id)
        REFERENCES public.reconciliation_window_revisions(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_currency FOREIGN KEY(currency_code)
        REFERENCES public.currency_assets(code) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_controls_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_controls_scope CHECK(
        (control_type='bank' AND operational_account_id IS NOT NULL AND party_id IS NULL AND reconciliation_window_id IS NOT NULL)
        OR (control_type IN('accounts_receivable','accounts_payable') AND operational_account_id IS NULL AND party_id IS NOT NULL)
    ),
    CONSTRAINT ck_reconciliation_controls_values CHECK(
        period_end>period_start AND as_of>=period_start AND as_of<=period_end
        AND canonical_closing=canonical_opening+canonical_increases-canonical_decreases+canonical_adjustments
        AND raw_variance=control_position-canonical_closing
        AND unexplained_variance=raw_variance-explained_amount
        AND reconciliation_status=CASE WHEN raw_variance=0 THEN 'balanced'
             WHEN unexplained_variance=0 THEN 'explained' ELSE 'exception' END
        AND revision_number>0 AND calendar_policy_version>0
        AND ((revision_number=1 AND supersedes_control_id IS NULL) OR (revision_number>1 AND supersedes_control_id IS NOT NULL))
        AND ((control_type='bank' AND governed_window_revision_id IS NOT NULL AND governed_window_revision_number IS NOT NULL
              AND window_governance_state IN('open','closed','reopened'))
          OR (control_type<>'bank' AND governed_window_revision_id IS NULL AND governed_window_revision_number IS NULL
              AND window_governance_state IS NULL))
        AND request_fingerprint~'^[0-9a-f]{64}$' AND semantic_fingerprint~'^[0-9a-f]{64}$'
        AND jsonb_typeof(metadata)='object'
        AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL)
    )
);

CREATE TABLE public.reconciliation_control_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    reconciliation_control_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    item_type VARCHAR(40) NOT NULL,
    amount NUMERIC(24,8) NOT NULL,
    canonical_reference_type VARCHAR(40) NULL,
    canonical_reference_public_id UUID NULL,
    explanation VARCHAR(300) NOT NULL,
    evidence_reference VARCHAR(191) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_reconciliation_control_items_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_control_items_sequence UNIQUE(tenant_id,reconciliation_control_id,sequence_number),
    CONSTRAINT fk_reconciliation_control_items_control FOREIGN KEY(tenant_id,reconciliation_control_id)
        REFERENCES public.reconciliation_controls(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_control_items_values CHECK(sequence_number>0 AND amount<>0
        AND length(btrim(item_type))>0 AND length(btrim(explanation))>0 AND jsonb_typeof(metadata)='object')
);

CREATE TABLE public.reconciliation_evidence_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id INTEGER NOT NULL,
    reconciliation_control_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    evidence_type VARCHAR(48) NOT NULL,
    external_reference VARCHAR(191) NOT NULL,
    evidence_source VARCHAR(120) NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    actor_user_id INTEGER NULL,
    actor_service VARCHAR(120) NULL,
    source_component VARCHAR(120) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_reconciliation_evidence_public UNIQUE(public_id),
    CONSTRAINT uq_reconciliation_evidence_sequence UNIQUE(tenant_id,reconciliation_control_id,sequence_number),
    CONSTRAINT uq_reconciliation_evidence_identity UNIQUE(tenant_id,reconciliation_control_id,evidence_type,external_reference),
    CONSTRAINT fk_reconciliation_evidence_control FOREIGN KEY(tenant_id,reconciliation_control_id)
        REFERENCES public.reconciliation_controls(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_reconciliation_evidence_actor FOREIGN KEY(tenant_id,actor_user_id)
        REFERENCES public.users(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_reconciliation_evidence_values CHECK(length(btrim(evidence_type))>0
        AND length(btrim(external_reference))>0 AND length(btrim(evidence_source))>0
        AND evidence_hash~'^[0-9a-f]{64}$' AND sequence_number>0 AND jsonb_typeof(metadata)='object'
        AND (actor_user_id IS NOT NULL OR NULLIF(btrim(actor_service),'') IS NOT NULL))
);

CREATE INDEX ix_reconciliation_controls_scope ON public.reconciliation_controls
    (tenant_id,organization_unit_id,control_type,currency_code,period_end,id DESC);
CREATE INDEX ix_reconciliation_controls_account ON public.reconciliation_controls
    (tenant_id,operational_account_id,period_end,id DESC) WHERE operational_account_id IS NOT NULL;
CREATE INDEX ix_reconciliation_controls_party ON public.reconciliation_controls
    (tenant_id,party_id,control_type,period_end,id DESC) WHERE party_id IS NOT NULL;
CREATE UNIQUE INDEX uq_reconciliation_controls_revision ON public.reconciliation_controls
    (tenant_id,control_type,organization_unit_id,COALESCE(operational_account_id,0),
     COALESCE(party_id,'00000000-0000-0000-0000-000000000000'::uuid),currency_code,
     period_start,period_end,revision_number);

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_control()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE selected_account public.operational_financial_accounts%ROWTYPE;
DECLARE selected_window public.reconciliation_windows%ROWTYPE;
DECLARE selected_revision public.reconciliation_window_revisions%ROWTYPE;
DECLARE latest_control public.reconciliation_controls%ROWTYPE;
BEGIN
    IF NEW.control_type='bank' THEN
        SELECT * INTO selected_account FROM public.operational_financial_accounts
          WHERE tenant_id=NEW.tenant_id AND id=NEW.operational_account_id FOR SHARE;
        SELECT * INTO selected_window FROM public.reconciliation_windows
          WHERE tenant_id=NEW.tenant_id AND id=NEW.reconciliation_window_id FOR SHARE;
        SELECT * INTO selected_revision FROM public.reconciliation_window_revisions
          WHERE tenant_id=NEW.tenant_id AND id=NEW.governed_window_revision_id FOR SHARE;
        IF selected_account.id IS NULL OR selected_window.id IS NULL OR selected_revision.id IS NULL
           OR selected_account.organization_unit_id<>NEW.organization_unit_id
           OR selected_account.currency_code<>NEW.currency_code OR NOT selected_account.reconciliation_enabled
           OR selected_revision.reconciliation_window_id<>selected_window.id
           OR selected_revision.revision_number<>NEW.governed_window_revision_number
           OR selected_window.window_start<>NEW.period_start OR selected_window.window_end<>NEW.period_end
           OR NEW.as_of<>selected_window.window_end THEN
            RAISE EXCEPTION 'bank reconciliation scope or governed window revision is invalid' USING ERRCODE='23514';
        END IF;
    ELSE
        IF NOT EXISTS(SELECT 1 FROM public.financial_obligations o WHERE o.tenant_id=NEW.tenant_id
            AND o.organization_unit_id=NEW.organization_unit_id AND o.currency_code=NEW.currency_code
            AND ((NEW.control_type='accounts_receivable' AND o.debtor_party_id=NEW.party_id
                  AND o.obligation_type IN('trade_receivable','customer_receivable'))
              OR (NEW.control_type='accounts_payable' AND o.creditor_party_id=NEW.party_id
                  AND o.obligation_type IN('trade_payable','supplier_payable','expense_payable')))) THEN
            RAISE EXCEPTION 'party reconciliation scope has no canonical obligation authority' USING ERRCODE='23514';
        END IF;
    END IF;
    SELECT * INTO latest_control FROM public.reconciliation_controls c
      WHERE c.tenant_id=NEW.tenant_id AND c.control_type=NEW.control_type
        AND c.organization_unit_id=NEW.organization_unit_id
        AND COALESCE(c.operational_account_id,0)=COALESCE(NEW.operational_account_id,0)
        AND COALESCE(c.party_id,'00000000-0000-0000-0000-000000000000'::uuid)=COALESCE(NEW.party_id,'00000000-0000-0000-0000-000000000000'::uuid)
        AND c.currency_code=NEW.currency_code AND c.period_start=NEW.period_start AND c.period_end=NEW.period_end
      ORDER BY c.revision_number DESC LIMIT 1 FOR UPDATE;
    IF (latest_control.id IS NULL AND (NEW.revision_number<>1 OR NEW.supersedes_control_id IS NOT NULL))
       OR (latest_control.id IS NOT NULL AND (NEW.revision_number<>latest_control.revision_number+1
           OR NEW.supersedes_control_id<>latest_control.id)) THEN
        RAISE EXCEPTION 'reconciliation control revision chain is invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_validate_reconciliation_control_child()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public.reconciliation_controls c
        WHERE c.tenant_id=NEW.tenant_id AND c.id=NEW.reconciliation_control_id) THEN
        RAISE EXCEPTION 'reconciliation control child is cross-tenant or missing' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.xbos_reject_reconciliation_control_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
    RAISE EXCEPTION 'accepted reconciliation control history is immutable' USING ERRCODE='55000';
END $$;

CREATE TRIGGER trg_reconciliation_controls_validate BEFORE INSERT ON public.reconciliation_controls
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_control();
CREATE TRIGGER trg_reconciliation_control_items_validate BEFORE INSERT ON public.reconciliation_control_items
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_control_child();
CREATE TRIGGER trg_reconciliation_evidence_validate BEFORE INSERT ON public.reconciliation_evidence_references
FOR EACH ROW EXECUTE FUNCTION public.xbos_validate_reconciliation_control_child();
CREATE TRIGGER trg_reconciliation_controls_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_controls
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_control_mutation();
CREATE TRIGGER trg_reconciliation_control_items_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_control_items
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_control_mutation();
CREATE TRIGGER trg_reconciliation_evidence_immutable BEFORE UPDATE OR DELETE ON public.reconciliation_evidence_references
FOR EACH ROW EXECUTE FUNCTION public.xbos_reject_reconciliation_control_mutation();

CREATE VIEW public.current_reconciliation_controls AS
SELECT c.* FROM public.reconciliation_controls c
WHERE NOT EXISTS(SELECT 1 FROM public.reconciliation_controls n
                 WHERE n.tenant_id=c.tenant_id AND n.supersedes_control_id=c.id);
