CREATE TABLE public.pa_commands(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 scope_key VARCHAR(160) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 request_fingerprint VARCHAR(64) NOT NULL,
 command_type VARCHAR(80) NOT NULL,
 result_table VARCHAR(120) NULL,
 result_id BIGINT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 completed_at TIMESTAMPTZ NULL,
 CONSTRAINT uq_pa_commands_scope UNIQUE(scope_key,command_key),
 CONSTRAINT ck_pa_command_fingerprint CHECK(length(request_fingerprint)=64)
);

CREATE TABLE public.pa_merchants(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 administration_state VARCHAR(24) NOT NULL,
 external_reference VARCHAR(240) NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_merchant_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_merchant_public UNIQUE(public_id),
 CONSTRAINT uq_pa_merchant_tenant UNIQUE(tenant_id),
 CONSTRAINT uq_pa_merchant_tenant_id_id UNIQUE(tenant_id,id),
 CONSTRAINT ck_pa_merchant_state CHECK(administration_state IN ('registered','onboarding','ready','operational','offboarding','closed')),
 CONSTRAINT ck_pa_merchant_version CHECK(row_version>0)
);

CREATE TABLE public.pa_merchant_history(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 merchant_id BIGINT NOT NULL,
 sequence INTEGER NOT NULL,
 from_state VARCHAR(24) NULL,
 to_state VARCHAR(24) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 reason VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_merchant_history FOREIGN KEY(tenant_id,merchant_id) REFERENCES public.pa_merchants(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_merchant_history_sequence UNIQUE(tenant_id,merchant_id,sequence)
);

CREATE TABLE public.pa_plans(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 plan_code VARCHAR(120) NOT NULL,
 owner_code VARCHAR(120) NOT NULL,
 lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT uq_pa_plan_public UNIQUE(public_id),
 CONSTRAINT uq_pa_plan_code UNIQUE(plan_code),
 CONSTRAINT ck_pa_plan_code CHECK(plan_code=lower(btrim(plan_code))),
 CONSTRAINT ck_pa_plan_lifecycle CHECK(lifecycle IN ('active','deprecated','retired'))
);

CREATE TABLE public.pa_plan_versions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 plan_id BIGINT NOT NULL,
 plan_version VARCHAR(64) NOT NULL,
 plan_json JSONB NOT NULL,
 plan_sha256 VARCHAR(64) NOT NULL,
 entitlement_codes TEXT[] NOT NULL DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_plan_version_plan FOREIGN KEY(plan_id) REFERENCES public.pa_plans(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_plan_version_public UNIQUE(public_id),
 CONSTRAINT uq_pa_plan_version_identity UNIQUE(plan_id,plan_version),
 CONSTRAINT ck_pa_plan_version_sha CHECK(length(plan_sha256)=64)
);

CREATE TABLE public.pa_plan_quotas(
 plan_version_id BIGINT NOT NULL,
 meter_code VARCHAR(120) NOT NULL,
 quota_limit NUMERIC(30,8) NOT NULL,
 PRIMARY KEY(plan_version_id,meter_code),
 CONSTRAINT fk_pa_plan_quota_version FOREIGN KEY(plan_version_id) REFERENCES public.pa_plan_versions(id) ON DELETE RESTRICT,
 CONSTRAINT ck_pa_plan_quota_meter CHECK(meter_code=lower(btrim(meter_code))),
 CONSTRAINT ck_pa_plan_quota_limit CHECK(quota_limit>0)
);

CREATE TABLE public.pa_subscriptions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 plan_version_id BIGINT NOT NULL,
 status VARCHAR(16) NOT NULL,
 starts_at TIMESTAMPTZ NOT NULL,
 ends_at TIMESTAMPTZ NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_subscription_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pa_subscription_plan FOREIGN KEY(plan_version_id) REFERENCES public.pa_plan_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_subscription_public UNIQUE(public_id),
 CONSTRAINT uq_pa_subscription_tenant UNIQUE(tenant_id),
 CONSTRAINT uq_pa_subscription_tenant_id_id UNIQUE(tenant_id,id),
 CONSTRAINT ck_pa_subscription_status CHECK(status IN ('pending','active','paused','ended')),
 CONSTRAINT ck_pa_subscription_period CHECK(ends_at IS NULL OR ends_at>starts_at),
 CONSTRAINT ck_pa_subscription_version CHECK(row_version>0)
);

CREATE TABLE public.pa_subscription_history(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 subscription_id BIGINT NOT NULL,
 sequence INTEGER NOT NULL,
 from_status VARCHAR(16) NULL,
 to_status VARCHAR(16) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 reason VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_subscription_history FOREIGN KEY(tenant_id,subscription_id) REFERENCES public.pa_subscriptions(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_subscription_history_sequence UNIQUE(tenant_id,subscription_id,sequence)
);

CREATE TABLE public.pa_usage_events(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 event_key VARCHAR(240) NOT NULL,
 meter_code VARCHAR(120) NOT NULL,
 quantity NUMERIC(30,8) NOT NULL,
 period_key VARCHAR(80) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL,
 source_reference VARCHAR(300) NOT NULL,
 metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 request_fingerprint VARCHAR(64) NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_usage_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_usage_public UNIQUE(public_id),
 CONSTRAINT uq_pa_usage_event UNIQUE(tenant_id,event_key),
 CONSTRAINT ck_pa_usage_quantity CHECK(quantity>0),
 CONSTRAINT ck_pa_usage_fingerprint CHECK(length(request_fingerprint)=64)
);

CREATE TABLE public.pa_onboarding_runs(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 template_code VARCHAR(120) NOT NULL,
 template_version VARCHAR(64) NOT NULL,
 plan_version_id BIGINT NOT NULL,
 status VARCHAR(16) NOT NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 readiness_sha256 VARCHAR(64) NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 completed_at TIMESTAMPTZ NULL,
 CONSTRAINT fk_pa_onboarding_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pa_onboarding_plan FOREIGN KEY(plan_version_id) REFERENCES public.pa_plan_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_onboarding_public UNIQUE(public_id),
 CONSTRAINT uq_pa_onboarding_tenant UNIQUE(tenant_id),
 CONSTRAINT uq_pa_onboarding_tenant_id_id UNIQUE(tenant_id,id),
 CONSTRAINT ck_pa_onboarding_status CHECK(status IN ('in_progress','ready','completed','blocked')),
 CONSTRAINT ck_pa_onboarding_version CHECK(row_version>0),
 CONSTRAINT ck_pa_onboarding_readiness_sha CHECK(readiness_sha256 IS NULL OR length(readiness_sha256)=64)
);

CREATE TABLE public.pa_onboarding_checks(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 onboarding_id BIGINT NOT NULL,
 snapshot_sequence INTEGER NOT NULL,
 check_code VARCHAR(120) NOT NULL,
 status VARCHAR(8) NOT NULL,
 evidence_reference VARCHAR(500) NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_onboarding_check FOREIGN KEY(tenant_id,onboarding_id) REFERENCES public.pa_onboarding_runs(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_onboarding_check UNIQUE(tenant_id,onboarding_id,snapshot_sequence,check_code),
 CONSTRAINT ck_pa_onboarding_check_status CHECK(status IN ('pass','fail'))
);

CREATE OR REPLACE FUNCTION public.pa_reject_append_only_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'pa_append_only_record_immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER trg_pa_merchant_history_immutable BEFORE UPDATE OR DELETE ON public.pa_merchant_history FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_plan_version_immutable BEFORE UPDATE OR DELETE ON public.pa_plan_versions FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_plan_quota_immutable BEFORE UPDATE OR DELETE ON public.pa_plan_quotas FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_subscription_history_immutable BEFORE UPDATE OR DELETE ON public.pa_subscription_history FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_usage_immutable BEFORE UPDATE OR DELETE ON public.pa_usage_events FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_onboarding_checks_immutable BEFORE UPDATE OR DELETE ON public.pa_onboarding_checks FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();

CREATE INDEX ix_pa_merchant_state ON public.pa_merchants(administration_state,tenant_id);
CREATE INDEX ix_pa_subscription_status ON public.pa_subscriptions(status,tenant_id);
CREATE INDEX ix_pa_usage_meter_period ON public.pa_usage_events(tenant_id,meter_code,period_key,occurred_at);
CREATE INDEX ix_pa_onboarding_status ON public.pa_onboarding_runs(status,tenant_id);
