CREATE TABLE public.pa_support_sessions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 actor_identity_public_id UUID NOT NULL,
 access_mode VARCHAR(16) NOT NULL,
 scopes TEXT[] NOT NULL DEFAULT '{}',
 reason VARCHAR(1000) NOT NULL,
 state VARCHAR(16) NOT NULL,
 starts_at TIMESTAMPTZ NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 authorization_reference VARCHAR(500) NOT NULL,
 step_up_reference VARCHAR(500) NULL,
 break_glass_evidence_reference VARCHAR(500) NULL,
 metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 row_version INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_support_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_support_public UNIQUE(public_id),
 CONSTRAINT uq_pa_support_tenant_id_id UNIQUE(tenant_id,id),
 CONSTRAINT ck_pa_support_mode CHECK(access_mode IN ('delegated','break_glass')),
 CONSTRAINT ck_pa_support_state CHECK(state IN ('active','closed','revoked')),
 CONSTRAINT ck_pa_support_period CHECK(expires_at>starts_at),
 CONSTRAINT ck_pa_support_scope CHECK(cardinality(scopes)>0),
 CONSTRAINT ck_pa_support_version CHECK(row_version>0)
);

CREATE TABLE public.pa_support_session_history(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 support_session_id BIGINT NOT NULL,
 sequence INTEGER NOT NULL,
 from_state VARCHAR(16) NULL,
 to_state VARCHAR(16) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_support_history FOREIGN KEY(tenant_id,support_session_id) REFERENCES public.pa_support_sessions(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_support_history_sequence UNIQUE(tenant_id,support_session_id,sequence)
);

CREATE TABLE public.pa_support_actions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 support_session_id BIGINT NOT NULL,
 action_code VARCHAR(120) NOT NULL,
 target_reference VARCHAR(500) NOT NULL,
 evidence_reference VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL,
 metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 request_fingerprint VARCHAR(64) NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_support_action FOREIGN KEY(tenant_id,support_session_id) REFERENCES public.pa_support_sessions(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_support_action_public UNIQUE(public_id),
 CONSTRAINT ck_pa_support_action_fingerprint CHECK(length(request_fingerprint)=64)
);

CREATE TABLE public.pa_recovery_cases(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 case_key VARCHAR(240) NOT NULL,
 problem_code VARCHAR(120) NOT NULL,
 subject_reference VARCHAR(500) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 opened_by_identity_public_id UUID NOT NULL,
 evidence_reference VARCHAR(500) NOT NULL,
 state VARCHAR(16) NOT NULL,
 request_fingerprint VARCHAR(64) NOT NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_recovery_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_recovery_public UNIQUE(public_id),
 CONSTRAINT uq_pa_recovery_case_key UNIQUE(tenant_id,case_key),
 CONSTRAINT uq_pa_recovery_tenant_id_id UNIQUE(tenant_id,id),
 CONSTRAINT ck_pa_recovery_state CHECK(state IN ('open','resolved','abandoned')),
 CONSTRAINT ck_pa_recovery_fingerprint CHECK(length(request_fingerprint)=64),
 CONSTRAINT ck_pa_recovery_version CHECK(row_version>0)
);

CREATE TABLE public.pa_recovery_case_history(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 recovery_case_id BIGINT NOT NULL,
 sequence INTEGER NOT NULL,
 from_state VARCHAR(16) NULL,
 to_state VARCHAR(16) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 evidence_reference VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_recovery_history FOREIGN KEY(tenant_id,recovery_case_id) REFERENCES public.pa_recovery_cases(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_recovery_history_sequence UNIQUE(tenant_id,recovery_case_id,sequence)
);

CREATE TABLE public.pa_recovery_actions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 recovery_case_id BIGINT NOT NULL,
 support_session_id BIGINT NULL,
 action_code VARCHAR(120) NOT NULL,
 outcome VARCHAR(16) NOT NULL,
 evidence_reference VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL,
 metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 request_fingerprint VARCHAR(64) NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_recovery_action_case FOREIGN KEY(tenant_id,recovery_case_id) REFERENCES public.pa_recovery_cases(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT fk_pa_recovery_action_support FOREIGN KEY(tenant_id,support_session_id) REFERENCES public.pa_support_sessions(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_recovery_action_public UNIQUE(public_id),
 CONSTRAINT ck_pa_recovery_action_outcome CHECK(outcome IN ('recorded','succeeded','failed','inconclusive')),
 CONSTRAINT ck_pa_recovery_action_fingerprint CHECK(length(request_fingerprint)=64)
);

CREATE TABLE public.pa_health_snapshots(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 scope_type VARCHAR(16) NOT NULL,
 tenant_id INTEGER NULL,
 status VARCHAR(16) NOT NULL,
 snapshot_sha256 VARCHAR(64) NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pa_health_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_health_public UNIQUE(public_id),
 CONSTRAINT ck_pa_health_scope CHECK(scope_type IN ('merchant','platform')),
 CONSTRAINT ck_pa_health_status CHECK(status IN ('healthy','degraded','blocked','unknown')),
 CONSTRAINT ck_pa_health_sha CHECK(length(snapshot_sha256)=64),
 CONSTRAINT ck_pa_health_scope_tenant CHECK((scope_type='merchant' AND tenant_id IS NOT NULL) OR (scope_type='platform' AND tenant_id IS NULL))
);

CREATE TABLE public.pa_health_checks(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 health_snapshot_id BIGINT NOT NULL,
 check_code VARCHAR(120) NOT NULL,
 status VARCHAR(16) NOT NULL,
 evidence_reference VARCHAR(500) NOT NULL,
 observed_at TIMESTAMPTZ NOT NULL,
 CONSTRAINT fk_pa_health_check_snapshot FOREIGN KEY(health_snapshot_id) REFERENCES public.pa_health_snapshots(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pa_health_check UNIQUE(health_snapshot_id,check_code),
 CONSTRAINT ck_pa_health_check_status CHECK(status IN ('healthy','degraded','blocked','unknown'))
);

CREATE TRIGGER trg_pa_support_history_immutable BEFORE UPDATE OR DELETE ON public.pa_support_session_history FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_support_actions_immutable BEFORE UPDATE OR DELETE ON public.pa_support_actions FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_recovery_history_immutable BEFORE UPDATE OR DELETE ON public.pa_recovery_case_history FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_recovery_actions_immutable BEFORE UPDATE OR DELETE ON public.pa_recovery_actions FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_health_snapshots_immutable BEFORE UPDATE OR DELETE ON public.pa_health_snapshots FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();
CREATE TRIGGER trg_pa_health_checks_immutable BEFORE UPDATE OR DELETE ON public.pa_health_checks FOR EACH ROW EXECUTE FUNCTION public.pa_reject_append_only_mutation();

CREATE INDEX ix_pa_support_tenant_state ON public.pa_support_sessions(tenant_id,state,expires_at);
CREATE INDEX ix_pa_support_actor ON public.pa_support_sessions(actor_identity_public_id,state,expires_at);
CREATE INDEX ix_pa_support_actions_tenant_time ON public.pa_support_actions(tenant_id,occurred_at);
CREATE INDEX ix_pa_recovery_tenant_state ON public.pa_recovery_cases(tenant_id,state,updated_at);
CREATE INDEX ix_pa_recovery_actions_tenant_time ON public.pa_recovery_actions(tenant_id,occurred_at);
CREATE INDEX ix_pa_health_merchant_latest ON public.pa_health_snapshots(tenant_id,recorded_at DESC) WHERE scope_type='merchant';
CREATE INDEX ix_pa_health_platform_latest ON public.pa_health_snapshots(recorded_at DESC) WHERE scope_type='platform';
