ALTER TABLE public.tenants
    ADD COLUMN lifecycle_state VARCHAR(16) NOT NULL DEFAULT 'active',
    ADD COLUMN suspended_at TIMESTAMPTZ NULL,
    ADD COLUMN retired_at TIMESTAMPTZ NULL,
    ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1,
    ADD CONSTRAINT ck_tenants_pc1_lifecycle CHECK (lifecycle_state IN ('provisioned','active','suspended','retired')),
    ADD CONSTRAINT ck_tenants_pc1_lifecycle_dates CHECK (
        (lifecycle_state <> 'suspended' OR suspended_at IS NOT NULL) AND
        (lifecycle_state <> 'retired' OR retired_at IS NOT NULL)
    ),
    ADD CONSTRAINT ck_tenants_pc1_row_version CHECK (row_version >= 1);

CREATE TABLE public.legal_entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    code VARCHAR(64) NOT NULL,
    legal_name VARCHAR(200) NOT NULL,
    jurisdiction_code VARCHAR(16) NULL,
    registration_reference VARCHAR(120) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_legal_entities_public_id UNIQUE (public_id),
    CONSTRAINT uq_legal_entities_tenant_id_id UNIQUE (tenant_id,id),
    CONSTRAINT uq_legal_entities_tenant_code UNIQUE (tenant_id,code),
    CONSTRAINT fk_legal_entities_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_legal_entities_code CHECK (code=btrim(code) AND length(code)>0),
    CONSTRAINT ck_legal_entities_name CHECK (length(btrim(legal_name))>0),
    CONSTRAINT ck_legal_entities_version CHECK (row_version>=1)
);

ALTER TABLE public.organization_units ADD COLUMN legal_entity_id BIGINT NULL;
ALTER TABLE public.organization_units ADD CONSTRAINT fk_organization_units_legal_entity
    FOREIGN KEY (tenant_id,legal_entity_id) REFERENCES public.legal_entities(tenant_id,id) ON DELETE RESTRICT;

CREATE TABLE public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    legal_entity_id BIGINT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    location_kind VARCHAR(16) NOT NULL,
    timezone_name VARCHAR(64) NULL,
    address JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_locations_public_id UNIQUE (public_id),
    CONSTRAINT uq_locations_tenant_id_id UNIQUE (tenant_id,id),
    CONSTRAINT uq_locations_tenant_code UNIQUE (tenant_id,code),
    CONSTRAINT fk_locations_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_locations_legal_entity FOREIGN KEY (tenant_id,legal_entity_id)
        REFERENCES public.legal_entities(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_locations_kind CHECK (location_kind IN ('physical','virtual')),
    CONSTRAINT ck_locations_code CHECK (code=btrim(code) AND length(code)>0),
    CONSTRAINT ck_locations_name CHECK (length(btrim(name))>0),
    CONSTRAINT ck_locations_address CHECK (jsonb_typeof(address)='object'),
    CONSTRAINT ck_locations_version CHECK (row_version>=1)
);

ALTER TABLE public.branches ADD CONSTRAINT uq_branches_tenant_id_id UNIQUE (tenant_id,id);

CREATE TABLE public.legacy_branch_structural_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    branch_id INTEGER NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    mapped_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    retirement_owner VARCHAR(80) NOT NULL DEFAULT 'PC1',
    retirement_milestone VARCHAR(40) NOT NULL DEFAULT 'PC1.10 compatibility exit',
    CONSTRAINT uq_legacy_branch_mapping_branch UNIQUE (tenant_id,branch_id),
    CONSTRAINT uq_legacy_branch_mapping_org UNIQUE (tenant_id,organization_unit_id),
    CONSTRAINT uq_legacy_branch_mapping_location UNIQUE (tenant_id,location_id),
    CONSTRAINT fk_legacy_branch_mapping_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_legacy_branch_mapping_branch FOREIGN KEY (tenant_id,branch_id)
        REFERENCES public.branches(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_legacy_branch_mapping_org FOREIGN KEY (tenant_id,organization_unit_id)
        REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_legacy_branch_mapping_location FOREIGN KEY (tenant_id,location_id)
        REFERENCES public.locations(tenant_id,id) ON DELETE RESTRICT
);

CREATE TABLE public.tenant_provisioning_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_key VARCHAR(160) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    tenant_id INTEGER NULL,
    result_context JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_tenant_provisioning_command UNIQUE (command_key),
    CONSTRAINT fk_tenant_provisioning_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tenant_provisioning_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_tenant_provisioning_result CHECK (result_context IS NULL OR jsonb_typeof(result_context)='object')
);

CREATE OR REPLACE FUNCTION public.pc1_reject_organization_cycle() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.parent_id IS NULL THEN RETURN NEW; END IF;
    IF EXISTS (
        WITH RECURSIVE ancestors(id,parent_id) AS (
            SELECT id,parent_id FROM public.organization_units WHERE tenant_id=NEW.tenant_id AND id=NEW.parent_id
            UNION ALL
            SELECT parent.id,parent.parent_id FROM public.organization_units parent
            JOIN ancestors child ON parent.id=child.parent_id
            WHERE parent.tenant_id=NEW.tenant_id
        ) SELECT 1 FROM ancestors WHERE id=NEW.id
    ) THEN RAISE EXCEPTION 'organization_cycle' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_pc1_reject_organization_cycle
    BEFORE INSERT OR UPDATE OF tenant_id,parent_id ON public.organization_units
    FOR EACH ROW EXECUTE FUNCTION public.pc1_reject_organization_cycle();

INSERT INTO public.legal_entities (public_id,tenant_id,code,legal_name,active)
SELECT (substr(md5('pc1-legal-entity:'||ou.tenant_id||':'||ou.id),1,8)||'-'||substr(md5('pc1-legal-entity:'||ou.tenant_id||':'||ou.id),9,4)||'-4'||substr(md5('pc1-legal-entity:'||ou.tenant_id||':'||ou.id),14,3)||'-a'||substr(md5('pc1-legal-entity:'||ou.tenant_id||':'||ou.id),18,3)||'-'||substr(md5('pc1-legal-entity:'||ou.tenant_id||':'||ou.id),21,12))::uuid,
       ou.tenant_id, ou.code, ou.name, ou.active
FROM public.organization_units ou
WHERE lower(ou.unit_type) IN ('legal_entity','legal-entity','legal entity')
ON CONFLICT (tenant_id,code) DO NOTHING;
UPDATE public.organization_units ou SET legal_entity_id=le.id
FROM public.legal_entities le
WHERE le.tenant_id=ou.tenant_id AND le.code=ou.code
  AND lower(ou.unit_type) IN ('legal_entity','legal-entity','legal entity');

INSERT INTO public.organization_units (public_id,tenant_id,parent_id,unit_type,code,name,timezone_name,active)
SELECT (substr(md5('pc1-branch-org:'||b.tenant_id||':'||b.id),1,8)||'-'||substr(md5('pc1-branch-org:'||b.tenant_id||':'||b.id),9,4)||'-4'||substr(md5('pc1-branch-org:'||b.tenant_id||':'||b.id),14,3)||'-a'||substr(md5('pc1-branch-org:'||b.tenant_id||':'||b.id),18,3)||'-'||substr(md5('pc1-branch-org:'||b.tenant_id||':'||b.id),21,12))::uuid,
       b.tenant_id,NULL,'operating_unit','legacy-branch-'||b.id,b.name,t.timezone,b.is_active
FROM public.branches b JOIN public.tenants t ON t.id=b.tenant_id
ON CONFLICT (tenant_id,code) DO NOTHING;

INSERT INTO public.locations (public_id,tenant_id,code,name,location_kind,timezone_name,address,active)
SELECT (substr(md5('pc1-branch-location:'||b.tenant_id||':'||b.id),1,8)||'-'||substr(md5('pc1-branch-location:'||b.tenant_id||':'||b.id),9,4)||'-4'||substr(md5('pc1-branch-location:'||b.tenant_id||':'||b.id),14,3)||'-a'||substr(md5('pc1-branch-location:'||b.tenant_id||':'||b.id),18,3)||'-'||substr(md5('pc1-branch-location:'||b.tenant_id||':'||b.id),21,12))::uuid,
       b.tenant_id,'legacy-branch-'||b.id,b.name,'physical',t.timezone,
       jsonb_strip_nulls(jsonb_build_object('city',b.city,'address',b.address)),b.is_active
FROM public.branches b JOIN public.tenants t ON t.id=b.tenant_id
ON CONFLICT (tenant_id,code) DO NOTHING;

INSERT INTO public.legacy_branch_structural_mappings (tenant_id,branch_id,organization_unit_id,location_id)
SELECT b.tenant_id,b.id,ou.id,l.id FROM public.branches b
JOIN public.organization_units ou ON ou.tenant_id=b.tenant_id AND ou.code='legacy-branch-'||b.id
JOIN public.locations l ON l.tenant_id=b.tenant_id AND l.code='legacy-branch-'||b.id
ON CONFLICT (tenant_id,branch_id) DO NOTHING;
