CREATE TABLE public.parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    party_kind VARCHAR(16) NOT NULL,
    display_name VARCHAR(240) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_parties_public_id UNIQUE(public_id),
    CONSTRAINT uq_parties_tenant_id_id UNIQUE(tenant_id,id),
    CONSTRAINT fk_parties_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_parties_kind CHECK(party_kind IN ('person','organization')),
    CONSTRAINT ck_parties_status CHECK(status IN ('active','inactive','retired')),
    CONSTRAINT ck_parties_display_name CHECK(length(btrim(display_name))>0),
    CONSTRAINT ck_parties_version CHECK(row_version>=1)
);
CREATE INDEX ix_parties_tenant_name ON public.parties(tenant_id,lower(display_name),public_id);

CREATE TABLE public.persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    given_name VARCHAR(120) NOT NULL,
    family_name VARCHAR(120) NOT NULL,
    middle_name VARCHAR(120) NULL,
    CONSTRAINT uq_persons_party UNIQUE(tenant_id,party_id),
    CONSTRAINT fk_persons_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_persons_names CHECK(length(btrim(given_name))>0 AND length(btrim(family_name))>0)
);

CREATE TABLE public.organization_parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    legal_name VARCHAR(240) NOT NULL,
    registration_reference VARCHAR(160) NULL,
    CONSTRAINT uq_organization_parties_party UNIQUE(tenant_id,party_id),
    CONSTRAINT fk_organization_parties_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_organization_parties_name CHECK(length(btrim(legal_name))>0)
);

CREATE OR REPLACE FUNCTION public.pc2_enforce_party_subtype() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE expected_kind VARCHAR(16);
BEGIN
    expected_kind := CASE TG_TABLE_NAME WHEN 'persons' THEN 'person' ELSE 'organization' END;
    IF NOT EXISTS(SELECT 1 FROM public.parties p WHERE p.tenant_id=NEW.tenant_id AND p.id=NEW.party_id AND p.party_kind=expected_kind)
    THEN RAISE EXCEPTION 'party_subtype_mismatch' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_pc2_person_subtype BEFORE INSERT OR UPDATE ON public.persons FOR EACH ROW EXECUTE FUNCTION public.pc2_enforce_party_subtype();
CREATE TRIGGER trg_pc2_organization_subtype BEFORE INSERT OR UPDATE ON public.organization_parties FOR EACH ROW EXECUTE FUNCTION public.pc2_enforce_party_subtype();

CREATE TABLE public.party_identifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    scheme VARCHAR(64) NOT NULL,
    identifier_value VARCHAR(240) NOT NULL,
    normalized_value VARCHAR(240) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    valid_from DATE NOT NULL DEFAULT CURRENT_DATE,
    valid_to DATE NULL,
    CONSTRAINT fk_party_identifiers_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT uq_party_identifier_reference UNIQUE(tenant_id,scheme,normalized_value),
    CONSTRAINT ck_party_identifier_values CHECK(length(btrim(scheme))>0 AND length(btrim(identifier_value))>0 AND length(btrim(normalized_value))>0),
    CONSTRAINT ck_party_identifier_period CHECK(valid_to IS NULL OR valid_to>=valid_from)
);
CREATE UNIQUE INDEX uq_party_identifier_primary ON public.party_identifiers(tenant_id,party_id,scheme) WHERE is_primary AND valid_to IS NULL;

CREATE TABLE public.party_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    contact_type VARCHAR(32) NOT NULL,
    contact_value VARCHAR(320) NOT NULL,
    normalized_value VARCHAR(320) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    valid_from DATE NOT NULL DEFAULT CURRENT_DATE,
    valid_to DATE NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_party_contacts_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_party_contact_type CHECK(contact_type IN ('email','phone','postal_address','other')),
    CONSTRAINT ck_party_contact_value CHECK(length(btrim(contact_value))>0 AND length(btrim(normalized_value))>0),
    CONSTRAINT ck_party_contact_period CHECK(valid_to IS NULL OR valid_to>=valid_from),
    CONSTRAINT ck_party_contact_metadata CHECK(jsonb_typeof(metadata)='object')
);
CREATE UNIQUE INDEX uq_party_contact_primary ON public.party_contacts(tenant_id,party_id,contact_type) WHERE is_primary AND valid_to IS NULL;
CREATE INDEX ix_party_contact_lookup ON public.party_contacts(tenant_id,contact_type,normalized_value);

CREATE TABLE public.party_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    role_code VARCHAR(64) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    legal_entity_id BIGINT NULL,
    organization_unit_id BIGINT NULL,
    location_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_party_roles_public_id UNIQUE(public_id),
    CONSTRAINT fk_party_roles_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_party_roles_legal FOREIGN KEY(tenant_id,legal_entity_id) REFERENCES public.legal_entities(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_party_roles_organization FOREIGN KEY(tenant_id,organization_unit_id) REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_party_roles_location FOREIGN KEY(tenant_id,location_id) REFERENCES public.locations(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_party_roles_code CHECK(length(btrim(role_code))>0),
    CONSTRAINT ck_party_roles_period CHECK(valid_to IS NULL OR valid_to>=valid_from)
);
CREATE UNIQUE INDEX uq_party_role_effective ON public.party_roles
    (tenant_id,party_id,role_code,valid_from,COALESCE(legal_entity_id,0),COALESCE(organization_unit_id,0),COALESCE(location_id,0));

CREATE TABLE public.party_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    source_party_id BIGINT NOT NULL,
    target_party_id BIGINT NOT NULL,
    relationship_code VARCHAR(64) NOT NULL,
    directed BOOLEAN NOT NULL DEFAULT true,
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_party_relationships_public_id UNIQUE(public_id),
    CONSTRAINT uq_party_relationship_effective UNIQUE(tenant_id,source_party_id,target_party_id,relationship_code,directed,valid_from),
    CONSTRAINT fk_party_relationship_source FOREIGN KEY(tenant_id,source_party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_party_relationship_target FOREIGN KEY(tenant_id,target_party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_party_relationship_code CHECK(length(btrim(relationship_code))>0),
    CONSTRAINT ck_party_relationship_distinct CHECK(source_party_id<>target_party_id),
    CONSTRAINT ck_party_relationship_period CHECK(valid_to IS NULL OR valid_to>=valid_from)
);

CREATE TABLE public.legal_entity_party_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    legal_entity_id BIGINT NOT NULL,
    organization_party_id BIGINT NOT NULL,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_legal_entity_party_legal UNIQUE(tenant_id,legal_entity_id),
    CONSTRAINT uq_legal_entity_party_party UNIQUE(tenant_id,organization_party_id),
    CONSTRAINT fk_legal_entity_party_legal FOREIGN KEY(tenant_id,legal_entity_id) REFERENCES public.legal_entities(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_legal_entity_party_party FOREIGN KEY(tenant_id,organization_party_id) REFERENCES public.organization_parties(tenant_id,party_id) ON DELETE RESTRICT
);

CREATE TABLE public.party_compatibility_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    source_authority VARCHAR(64) NOT NULL,
    source_record_id VARCHAR(160) NOT NULL,
    party_id BIGINT NOT NULL,
    mapping_basis VARCHAR(64) NOT NULL,
    mapped_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_party_compatibility_source UNIQUE(tenant_id,source_authority,source_record_id),
    CONSTRAINT fk_party_compatibility_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_party_mapping_basis CHECK(mapping_basis IN ('explicit','external_identifier','operator_approved'))
);

CREATE TABLE public.party_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_key VARCHAR(160) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    command_type VARCHAR(40) NOT NULL,
    result_table VARCHAR(40) NULL,
    result_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_party_commands_key UNIQUE(command_key),
    CONSTRAINT ck_party_commands_fingerprint CHECK(request_fingerprint~'^[0-9a-f]{64}$'),
    CONSTRAINT ck_party_commands_type CHECK(command_type IN ('create_person','create_organization','assign_role','create_relationship','add_identifier','add_contact','link_legal_entity')),
    CONSTRAINT ck_party_commands_result CHECK((result_table IS NULL AND result_id IS NULL AND completed_at IS NULL) OR (result_table IS NOT NULL AND result_id IS NOT NULL AND completed_at IS NOT NULL))
);

COMMENT ON COLUMN public.financial_counterparties.party_id IS
    'Compatibility reference candidate to PC2 parties.id; Finance snapshots and semantics remain authoritative until explicit mapping.';
