CREATE TABLE public.semantic_namespaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    namespace_code VARCHAR(120) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    owner_code VARCHAR(120) NOT NULL,
    tenant_id INTEGER NULL,
    lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_semantic_namespaces_public_id UNIQUE(public_id),
    CONSTRAINT uq_semantic_namespaces_code UNIQUE(namespace_code),
    CONSTRAINT fk_semantic_namespaces_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_namespaces_scope CHECK(scope IN ('kernel','finance','pack','tenant','external')),
    CONSTRAINT ck_semantic_namespaces_owner CHECK(length(btrim(owner_code))>0),
    CONSTRAINT ck_semantic_namespaces_lifecycle CHECK(lifecycle IN ('active','deprecated','retired')),
    CONSTRAINT ck_semantic_namespaces_tenant_scope CHECK((scope='tenant' AND tenant_id IS NOT NULL) OR (scope<>'tenant' AND tenant_id IS NULL))
);
CREATE TABLE public.semantic_concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), namespace_id BIGINT NOT NULL,
    code VARCHAR(120) NOT NULL, lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
    superseded_by_concept_id BIGINT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_semantic_concepts_public_id UNIQUE(public_id),
    CONSTRAINT uq_semantic_concepts_namespace_code UNIQUE(namespace_id,code),
    CONSTRAINT fk_semantic_concepts_namespace FOREIGN KEY(namespace_id) REFERENCES public.semantic_namespaces(id) ON DELETE RESTRICT,
    CONSTRAINT fk_semantic_concepts_superseded FOREIGN KEY(superseded_by_concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_concepts_code CHECK(code=lower(btrim(code)) AND length(code)>0),
    CONSTRAINT ck_semantic_concepts_lifecycle CHECK(lifecycle IN ('active','deprecated','retired')),
    CONSTRAINT ck_semantic_concepts_superseded CHECK(superseded_by_concept_id IS NULL OR superseded_by_concept_id<>id)
);
CREATE TABLE public.semantic_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), concept_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, effective_from DATE NOT NULL, effective_to DATE NULL,
    canonical_label VARCHAR(240) NOT NULL, definition TEXT NOT NULL,
    definition_fingerprint CHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_semantic_versions_public_id UNIQUE(public_id),
    CONSTRAINT uq_semantic_versions_number UNIQUE(concept_id,version_number),
    CONSTRAINT uq_semantic_versions_start UNIQUE(concept_id,effective_from),
    CONSTRAINT fk_semantic_versions_concept FOREIGN KEY(concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_versions_number CHECK(version_number>=1),
    CONSTRAINT ck_semantic_versions_period CHECK(effective_to IS NULL OR effective_to>=effective_from),
    CONSTRAINT ck_semantic_versions_label CHECK(length(btrim(canonical_label))>0),
    CONSTRAINT ck_semantic_versions_definition CHECK(length(btrim(definition))>0),
    CONSTRAINT ck_semantic_versions_fingerprint CHECK(definition_fingerprint~'^[0-9a-f]{64}$')
);
CREATE INDEX ix_semantic_versions_effective ON public.semantic_versions(concept_id,effective_from,effective_to);
CREATE OR REPLACE FUNCTION public.pc3_reject_overlapping_semantic_versions() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM public.semantic_versions v WHERE v.concept_id=NEW.concept_id AND v.id<>COALESCE(NEW.id,0)
  AND daterange(v.effective_from,COALESCE(v.effective_to,'infinity'::date),'[]') && daterange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'::date),'[]'))
 THEN RAISE EXCEPTION 'overlapping_semantic_version' USING ERRCODE='23514'; END IF; RETURN NEW;
END $$;
CREATE TRIGGER trg_pc3_semantic_version_overlap BEFORE INSERT OR UPDATE ON public.semantic_versions FOR EACH ROW EXECUTE FUNCTION public.pc3_reject_overlapping_semantic_versions();
CREATE TABLE public.semantic_labels (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, semantic_version_id BIGINT NOT NULL,
 locale_code VARCHAR(32) NOT NULL, label VARCHAR(240) NOT NULL, description TEXT NULL,
 CONSTRAINT uq_semantic_labels_locale UNIQUE(semantic_version_id,locale_code),
 CONSTRAINT fk_semantic_labels_version FOREIGN KEY(semantic_version_id) REFERENCES public.semantic_versions(id) ON DELETE RESTRICT,
 CONSTRAINT ck_semantic_labels_values CHECK(length(btrim(locale_code))>0 AND length(btrim(label))>0)
);
CREATE TABLE public.taxonomy_systems (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 system_code VARCHAR(120) NOT NULL, owner_code VARCHAR(120) NOT NULL, tenant_id INTEGER NULL,
 namespace_id BIGINT NULL, lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
 CONSTRAINT uq_taxonomy_systems_public_id UNIQUE(public_id), CONSTRAINT uq_taxonomy_systems_code UNIQUE(system_code),
 CONSTRAINT fk_taxonomy_systems_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_taxonomy_systems_namespace FOREIGN KEY(namespace_id) REFERENCES public.semantic_namespaces(id) ON DELETE RESTRICT,
 CONSTRAINT ck_taxonomy_systems_lifecycle CHECK(lifecycle IN ('active','deprecated','retired'))
);
ALTER TABLE public.taxonomy_nodes
 ADD COLUMN public_id UUID NULL DEFAULT gen_random_uuid(), ADD COLUMN taxonomy_system_id BIGINT NULL,
 ADD COLUMN semantic_concept_id BIGINT NULL, ADD COLUMN effective_from DATE NULL, ADD COLUMN effective_to DATE NULL,
 ADD COLUMN semantic_row_version INTEGER NOT NULL DEFAULT 1,
 ADD CONSTRAINT uq_taxonomy_nodes_public_id UNIQUE(public_id),
 ADD CONSTRAINT fk_taxonomy_nodes_system FOREIGN KEY(taxonomy_system_id) REFERENCES public.taxonomy_systems(id) ON DELETE RESTRICT,
 ADD CONSTRAINT fk_taxonomy_nodes_concept FOREIGN KEY(semantic_concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
 ADD CONSTRAINT fk_taxonomy_nodes_parent_tenant FOREIGN KEY(tenant_id,parent_id) REFERENCES public.taxonomy_nodes(tenant_id,id) ON DELETE RESTRICT,
 ADD CONSTRAINT ck_taxonomy_nodes_effective CHECK(effective_to IS NULL OR effective_from IS NULL OR effective_to>=effective_from),
 ADD CONSTRAINT ck_taxonomy_nodes_semantic_version CHECK(semantic_row_version>=1);
CREATE OR REPLACE FUNCTION public.pc3_reject_taxonomy_cycle() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN IF NEW.parent_id IS NULL THEN RETURN NEW; END IF;
 IF EXISTS(WITH RECURSIVE ancestors(id,parent_id) AS (
  SELECT id,parent_id FROM public.taxonomy_nodes WHERE tenant_id=NEW.tenant_id AND id=NEW.parent_id
  UNION ALL SELECT p.id,p.parent_id FROM public.taxonomy_nodes p JOIN ancestors c ON p.id=c.parent_id WHERE p.tenant_id=NEW.tenant_id
 ) SELECT 1 FROM ancestors WHERE id=NEW.id)
 THEN RAISE EXCEPTION 'taxonomy_cycle' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_pc3_taxonomy_cycle BEFORE INSERT OR UPDATE OF tenant_id,parent_id ON public.taxonomy_nodes FOR EACH ROW EXECUTE FUNCTION public.pc3_reject_taxonomy_cycle();
CREATE TABLE public.semantic_mapping_sets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 mapping_set_code VARCHAR(120) NOT NULL, owner_code VARCHAR(120) NOT NULL, lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
 CONSTRAINT uq_semantic_mapping_sets_public_id UNIQUE(public_id), CONSTRAINT uq_semantic_mapping_sets_code UNIQUE(mapping_set_code),
 CONSTRAINT ck_semantic_mapping_sets_lifecycle CHECK(lifecycle IN ('active','deprecated','retired'))
);
CREATE TABLE public.semantic_mappings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 mapping_set_id BIGINT NOT NULL, source_concept_id BIGINT NOT NULL, target_concept_id BIGINT NOT NULL,
 mapping_type VARCHAR(24) NOT NULL, effective_from DATE NOT NULL, effective_to DATE NULL,
 provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
 CONSTRAINT uq_semantic_mappings_public_id UNIQUE(public_id),
 CONSTRAINT uq_semantic_mapping_effective UNIQUE(mapping_set_id,source_concept_id,target_concept_id,mapping_type,effective_from),
 CONSTRAINT fk_semantic_mappings_set FOREIGN KEY(mapping_set_id) REFERENCES public.semantic_mapping_sets(id) ON DELETE RESTRICT,
 CONSTRAINT fk_semantic_mappings_source FOREIGN KEY(source_concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
 CONSTRAINT fk_semantic_mappings_target FOREIGN KEY(target_concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
 CONSTRAINT ck_semantic_mappings_distinct CHECK(source_concept_id<>target_concept_id),
 CONSTRAINT ck_semantic_mappings_type CHECK(mapping_type IN ('exact','broader','narrower','related','legacy_replacement')),
 CONSTRAINT ck_semantic_mappings_period CHECK(effective_to IS NULL OR effective_to>=effective_from),
 CONSTRAINT ck_semantic_mappings_provenance CHECK(jsonb_typeof(provenance)='object')
);
CREATE TABLE public.classification_assignments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL, subject_type VARCHAR(64) NOT NULL, subject_key VARCHAR(160) NOT NULL,
 concept_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, taxonomy_node_id INTEGER NULL,
 classified_on DATE NOT NULL, concept_qualified_code_snapshot VARCHAR(260) NOT NULL,
 concept_version_snapshot INTEGER NOT NULL, definition_fingerprint_snapshot CHAR(64) NOT NULL,
 assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT uq_classification_assignments_public_id UNIQUE(public_id),
 CONSTRAINT uq_classification_assignment UNIQUE(tenant_id,subject_type,subject_key,concept_id,classified_on),
 CONSTRAINT fk_classification_assignments_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_classification_assignments_concept FOREIGN KEY(concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
 CONSTRAINT fk_classification_assignments_version FOREIGN KEY(concept_version_id) REFERENCES public.semantic_versions(id) ON DELETE RESTRICT,
 CONSTRAINT fk_classification_assignments_node FOREIGN KEY(tenant_id,taxonomy_node_id) REFERENCES public.taxonomy_nodes(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT ck_classification_assignment_values CHECK(length(btrim(subject_type))>0 AND length(btrim(subject_key))>0),
 CONSTRAINT ck_classification_assignment_fingerprint CHECK(definition_fingerprint_snapshot~'^[0-9a-f]{64}$')
);
CREATE TABLE public.semantic_commands (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, command_key VARCHAR(160) NOT NULL,
 request_fingerprint CHAR(64) NOT NULL, command_type VARCHAR(40) NOT NULL,
 result_table VARCHAR(40) NULL, result_id BIGINT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ NULL,
 CONSTRAINT uq_semantic_commands_key UNIQUE(command_key),
 CONSTRAINT ck_semantic_commands_fingerprint CHECK(request_fingerprint~'^[0-9a-f]{64}$'),
 CONSTRAINT ck_semantic_commands_type CHECK(command_type IN ('create_namespace','create_concept','create_version','create_mapping','assign_classification')),
 CONSTRAINT ck_semantic_commands_result CHECK((result_table IS NULL AND result_id IS NULL AND completed_at IS NULL) OR (result_table IS NOT NULL AND result_id IS NOT NULL AND completed_at IS NOT NULL))
);
COMMENT ON COLUMN public.taxonomy_nodes.semantic_level IS 'Legacy navigation/grouping hint; not canonical semantic identity.';
COMMENT ON COLUMN public.taxonomy_nodes.taxonomy_type IS 'Legacy taxonomy-system hint; bridge only until explicitly mapped.';
COMMENT ON TABLE public.atomic_unit_taxonomy IS 'SO0 Atomic Unit to legacy PC3 taxonomy-node compatibility classification; Atomic Units remain SO0-owned.';
