CREATE TABLE public.configuration_definitions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(), config_key VARCHAR(120) NOT NULL,
 value_type VARCHAR(16) NOT NULL, owner_code VARCHAR(120) NOT NULL, allowed_scopes TEXT[] NOT NULL, resolution_order TEXT[] NOT NULL,
 required BOOLEAN NOT NULL DEFAULT false, secret BOOLEAN NOT NULL DEFAULT false, tenant_overridable BOOLEAN NOT NULL DEFAULT true,
 validation_constraints JSONB NOT NULL DEFAULT '{}'::jsonb, default_value JSONB NULL, lifecycle VARCHAR(16) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT uq_configuration_definitions_public UNIQUE(public_id), CONSTRAINT uq_configuration_definitions_key UNIQUE(config_key),
 CONSTRAINT ck_configuration_definition_key CHECK(config_key=lower(btrim(config_key)) AND length(config_key)>1),
 CONSTRAINT ck_configuration_definition_type CHECK(value_type IN ('boolean','integer','decimal','string','code','date','time','duration','json')),
 CONSTRAINT ck_configuration_definition_scopes CHECK(cardinality(allowed_scopes)>0 AND allowed_scopes<@ARRAY['platform','tenant','legal_entity','organization_unit','location']::text[] AND resolution_order<@allowed_scopes AND cardinality(resolution_order)=cardinality(allowed_scopes)),
 CONSTRAINT ck_configuration_definition_secret CHECK(NOT secret OR default_value IS NULL), CONSTRAINT ck_configuration_definition_lifecycle CHECK(lifecycle IN ('active','deprecated','retired'))
);
CREATE TABLE public.configuration_values(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(), definition_id BIGINT NOT NULL,
 tenant_id INTEGER NULL, scope_type VARCHAR(24) NOT NULL, scope_id INTEGER NULL, effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL,
 row_version INTEGER NOT NULL DEFAULT 1, boolean_value BOOLEAN NULL, integer_value BIGINT NULL, decimal_value NUMERIC NULL, string_value TEXT NULL,
 date_value DATE NULL, time_value TIME NULL, duration_seconds NUMERIC NULL, json_value JSONB NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT uq_configuration_values_public UNIQUE(public_id), CONSTRAINT fk_configuration_values_definition FOREIGN KEY(definition_id) REFERENCES public.configuration_definitions(id) ON DELETE RESTRICT,
 CONSTRAINT fk_configuration_values_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT ck_configuration_value_period CHECK(effective_to IS NULL OR effective_to>effective_from),
 CONSTRAINT ck_configuration_value_scope CHECK((scope_type='platform' AND tenant_id IS NULL AND scope_id IS NULL) OR (scope_type='tenant' AND tenant_id IS NOT NULL AND scope_id=tenant_id) OR (scope_type IN ('legal_entity','organization_unit','location') AND tenant_id IS NOT NULL AND scope_id IS NOT NULL)),
 CONSTRAINT ck_configuration_value_version CHECK(row_version>0)
);
CREATE INDEX ix_configuration_values_resolution ON public.configuration_values(definition_id,tenant_id,scope_type,scope_id,effective_from,effective_to);
CREATE OR REPLACE FUNCTION public.pc4_validate_configuration_value() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE d public.configuration_definitions%ROWTYPE; present integer;
BEGIN SELECT * INTO STRICT d FROM public.configuration_definitions WHERE id=NEW.definition_id;
 IF d.secret THEN RAISE EXCEPTION 'secret_material_forbidden' USING ERRCODE='23514'; END IF;
 IF NOT NEW.scope_type=ANY(d.allowed_scopes) THEN RAISE EXCEPTION 'unsupported_configuration_scope' USING ERRCODE='23514'; END IF;
 present:=num_nonnulls(NEW.boolean_value,NEW.integer_value,NEW.decimal_value,NEW.string_value,NEW.date_value,NEW.time_value,NEW.duration_seconds,NEW.json_value);
 IF present<>1 OR NOT (CASE d.value_type WHEN 'boolean' THEN NEW.boolean_value IS NOT NULL WHEN 'integer' THEN NEW.integer_value IS NOT NULL WHEN 'decimal' THEN NEW.decimal_value IS NOT NULL WHEN 'string' THEN NEW.string_value IS NOT NULL WHEN 'code' THEN NEW.string_value IS NOT NULL WHEN 'date' THEN NEW.date_value IS NOT NULL WHEN 'time' THEN NEW.time_value IS NOT NULL WHEN 'duration' THEN NEW.duration_seconds IS NOT NULL WHEN 'json' THEN NEW.json_value IS NOT NULL ELSE false END) THEN RAISE EXCEPTION 'typed_configuration_value_mismatch' USING ERRCODE='23514'; END IF;
 IF EXISTS(SELECT 1 FROM public.configuration_values v WHERE v.definition_id=NEW.definition_id AND v.tenant_id IS NOT DISTINCT FROM NEW.tenant_id AND v.scope_type=NEW.scope_type AND v.scope_id IS NOT DISTINCT FROM NEW.scope_id AND v.id<>COALESCE(NEW.id,0) AND tstzrange(v.effective_from,COALESCE(v.effective_to,'infinity'),'[)') && tstzrange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'),'[)')) THEN RAISE EXCEPTION 'overlapping_configuration_value' USING ERRCODE='23514'; END IF;
 IF NEW.scope_type='legal_entity' AND NOT EXISTS(SELECT 1 FROM public.legal_entities WHERE tenant_id=NEW.tenant_id AND id=NEW.scope_id) THEN RAISE EXCEPTION 'cross_tenant_legal_entity_configuration' USING ERRCODE='23514'; END IF;
 IF NEW.scope_type='organization_unit' AND NOT EXISTS(SELECT 1 FROM public.organization_units WHERE tenant_id=NEW.tenant_id AND id=NEW.scope_id) THEN RAISE EXCEPTION 'cross_tenant_organization_configuration' USING ERRCODE='23514'; END IF;
 IF NEW.scope_type='location' AND NOT EXISTS(SELECT 1 FROM public.locations WHERE tenant_id=NEW.tenant_id AND id=NEW.scope_id) THEN RAISE EXCEPTION 'cross_tenant_location_configuration' USING ERRCODE='23514'; END IF;
 RETURN NEW; END $$;
CREATE TRIGGER trg_pc4_configuration_value BEFORE INSERT OR UPDATE ON public.configuration_values FOR EACH ROW EXECUTE FUNCTION public.pc4_validate_configuration_value();
CREATE TABLE public.secret_references(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, definition_id BIGINT NOT NULL, tenant_id INTEGER NULL, scope_type VARCHAR(24) NOT NULL, scope_id INTEGER NULL,
 reference_key VARCHAR(160) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT uq_secret_reference UNIQUE(definition_id,tenant_id,scope_type,scope_id),
 CONSTRAINT fk_secret_reference_definition FOREIGN KEY(definition_id) REFERENCES public.configuration_definitions(id) ON DELETE RESTRICT,
 CONSTRAINT fk_secret_reference_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
  CONSTRAINT ck_secret_reference_key CHECK(reference_key=lower(btrim(reference_key)) AND length(reference_key)>1)
);
CREATE OR REPLACE FUNCTION public.pc4_validate_secret_reference() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE d public.configuration_definitions%ROWTYPE;
BEGIN SELECT * INTO STRICT d FROM public.configuration_definitions WHERE id=NEW.definition_id;
 IF NOT d.secret THEN RAISE EXCEPTION 'secret_definition_required' USING ERRCODE='23514'; END IF;
 IF NOT NEW.scope_type=ANY(d.allowed_scopes) THEN RAISE EXCEPTION 'unsupported_secret_scope' USING ERRCODE='23514'; END IF;
 IF NOT ((NEW.scope_type='platform' AND NEW.tenant_id IS NULL AND NEW.scope_id IS NULL) OR (NEW.scope_type='tenant' AND NEW.tenant_id IS NOT NULL AND NEW.scope_id=NEW.tenant_id) OR (NEW.scope_type IN ('legal_entity','organization_unit','location') AND NEW.tenant_id IS NOT NULL AND NEW.scope_id IS NOT NULL)) THEN RAISE EXCEPTION 'invalid_secret_scope' USING ERRCODE='23514'; END IF;
 RETURN NEW; END $$;
CREATE TRIGGER trg_pc4_secret_reference BEFORE INSERT OR UPDATE ON public.secret_references FOR EACH ROW EXECUTE FUNCTION public.pc4_validate_secret_reference();
CREATE TABLE public.core_modules(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(), module_code VARCHAR(120) NOT NULL,
 owner_code VARCHAR(120) NOT NULL, module_version VARCHAR(64) NOT NULL, capabilities TEXT[] NOT NULL DEFAULT '{}', status VARCHAR(16) NOT NULL DEFAULT 'available',
 CONSTRAINT uq_core_modules_public UNIQUE(public_id), CONSTRAINT uq_core_modules_code UNIQUE(module_code),
 CONSTRAINT ck_core_modules_code CHECK(module_code=lower(btrim(module_code))), CONSTRAINT ck_core_modules_status CHECK(status IN ('available','deprecated','retired'))
);
CREATE TABLE public.core_module_dependencies(
 module_id BIGINT NOT NULL, depends_on_module_id BIGINT NOT NULL, PRIMARY KEY(module_id,depends_on_module_id),
 CONSTRAINT fk_core_module_dependencies_module FOREIGN KEY(module_id) REFERENCES public.core_modules(id) ON DELETE RESTRICT,
 CONSTRAINT fk_core_module_dependencies_target FOREIGN KEY(depends_on_module_id) REFERENCES public.core_modules(id) ON DELETE RESTRICT,
 CONSTRAINT ck_core_module_dependencies_distinct CHECK(module_id<>depends_on_module_id)
);
CREATE TABLE public.tenant_module_enablements(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, module_code VARCHAR(120) NOT NULL, enabled BOOLEAN NOT NULL,
 effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, CONSTRAINT fk_tenant_module_enablements_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_tenant_module_enablements_module FOREIGN KEY(module_code) REFERENCES public.core_modules(module_code) ON DELETE RESTRICT,
 CONSTRAINT uq_tenant_module_enablement UNIQUE(tenant_id,module_code,effective_from), CONSTRAINT ck_tenant_module_period CHECK(effective_to IS NULL OR effective_to>effective_from)
);
CREATE TABLE public.tenant_entitlements(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, capability_code VARCHAR(120) NOT NULL,
 effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, CONSTRAINT fk_tenant_entitlements_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_tenant_entitlement UNIQUE(tenant_id,capability_code,effective_from), CONSTRAINT ck_tenant_entitlement_period CHECK(effective_to IS NULL OR effective_to>effective_from)
);
CREATE TABLE public.feature_flags(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NULL, flag_code VARCHAR(120) NOT NULL, enabled BOOLEAN NOT NULL,
 effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, row_version INTEGER NOT NULL DEFAULT 1,
 CONSTRAINT fk_feature_flags_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_feature_flag UNIQUE(tenant_id,flag_code,effective_from), CONSTRAINT ck_feature_flag_period CHECK(effective_to IS NULL OR effective_to>effective_from)
);
CREATE TABLE public.business_calendars(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(), tenant_id INTEGER NOT NULL,
 calendar_code VARCHAR(120) NOT NULL, calendar_version INTEGER NOT NULL, timezone_name VARCHAR(120) NOT NULL, business_day_boundary TIME NOT NULL,
 operating_weekdays SMALLINT[] NOT NULL, effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
 CONSTRAINT uq_business_calendars_public UNIQUE(public_id), CONSTRAINT uq_business_calendar_version UNIQUE(tenant_id,calendar_code,calendar_version),
 CONSTRAINT fk_business_calendars_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT ck_business_calendar_weekdays CHECK(operating_weekdays<@ARRAY[0,1,2,3,4,5,6]::smallint[]),
 CONSTRAINT ck_business_calendar_period CHECK(effective_to IS NULL OR effective_to>effective_from), CONSTRAINT ck_business_calendar_lifecycle CHECK(lifecycle IN ('active','deprecated','retired'))
);
CREATE TABLE public.business_calendar_exceptions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_calendar_id BIGINT NOT NULL, calendar_date DATE NOT NULL, exception_kind VARCHAR(8) NOT NULL,
 CONSTRAINT uq_business_calendar_exception UNIQUE(business_calendar_id,calendar_date), CONSTRAINT fk_business_calendar_exception FOREIGN KEY(business_calendar_id) REFERENCES public.business_calendars(id) ON DELETE RESTRICT,
 CONSTRAINT ck_business_calendar_exception CHECK(exception_kind IN ('open','closed'))
);
CREATE TABLE public.shift_definitions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid(), business_calendar_id BIGINT NOT NULL,
 shift_code VARCHAR(120) NOT NULL, display_name VARCHAR(240) NOT NULL, starts_at TIME NOT NULL, ends_at TIME NOT NULL,
 CONSTRAINT uq_shift_definitions_public UNIQUE(public_id), CONSTRAINT uq_shift_definition_code UNIQUE(business_calendar_id,shift_code),
 CONSTRAINT fk_shift_definition_calendar FOREIGN KEY(business_calendar_id) REFERENCES public.business_calendars(id) ON DELETE RESTRICT, CONSTRAINT ck_shift_definition_times CHECK(starts_at<>ends_at)
);
CREATE OR REPLACE FUNCTION public.pc4_reject_overlapping_calendars() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN IF EXISTS(SELECT 1 FROM public.business_calendars c WHERE c.tenant_id=NEW.tenant_id AND c.calendar_code=NEW.calendar_code AND c.id<>COALESCE(NEW.id,0) AND tstzrange(c.effective_from,COALESCE(c.effective_to,'infinity'),'[)') && tstzrange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'),'[)')) THEN RAISE EXCEPTION 'overlapping_business_calendar' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_pc4_calendar_overlap BEFORE INSERT OR UPDATE ON public.business_calendars FOR EACH ROW EXECUTE FUNCTION public.pc4_reject_overlapping_calendars();
CREATE TABLE public.localization_profiles(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INTEGER NOT NULL, locale_code VARCHAR(32) NOT NULL, timezone_name VARCHAR(120) NOT NULL,
 date_format VARCHAR(40) NOT NULL, decimal_separator VARCHAR(4) NOT NULL, currency_display VARCHAR(24) NOT NULL, business_display_name VARCHAR(240) NULL,
 branding_asset_reference VARCHAR(240) NULL, terminology JSONB NOT NULL DEFAULT '{}'::jsonb, effective_from TIMESTAMPTZ NOT NULL,
 CONSTRAINT fk_localization_profiles_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT uq_localization_profile UNIQUE(tenant_id,effective_from), CONSTRAINT ck_localization_terminology CHECK(jsonb_typeof(terminology)='object')
);
CREATE TABLE public.operating_context_commands(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, command_key VARCHAR(160) NOT NULL, request_fingerprint CHAR(64) NOT NULL,
 command_type VARCHAR(48) NOT NULL, result_table VARCHAR(48) NULL, result_id BIGINT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ NULL,
 CONSTRAINT uq_operating_context_command UNIQUE(command_key), CONSTRAINT ck_operating_context_fingerprint CHECK(request_fingerprint~'^[0-9a-f]{64}$'),
  CONSTRAINT ck_operating_context_completion CHECK((result_table IS NULL AND result_id IS NULL AND completed_at IS NULL) OR (result_table IS NOT NULL AND result_id IS NOT NULL AND completed_at IS NOT NULL))
);
COMMENT ON TABLE public.business_calendars IS 'PC4 prospective generic calendar authority; frozen Finance retains resolved historical financial time facts.';
COMMENT ON TABLE public.core_modules IS 'Registry metadata only; does not dynamically import or alter startup composition.';
COMMENT ON TABLE public.secret_references IS 'Secret locator metadata only; secret material is forbidden.';
