DROP TABLE IF EXISTS public.operating_context_commands;
DROP TABLE IF EXISTS public.localization_profiles;
DROP TRIGGER IF EXISTS trg_pc4_calendar_overlap ON public.business_calendars;
DROP FUNCTION IF EXISTS public.pc4_reject_overlapping_calendars();
DROP TABLE IF EXISTS public.shift_definitions;
DROP TABLE IF EXISTS public.business_calendar_exceptions;
DROP TABLE IF EXISTS public.business_calendars;
DROP TABLE IF EXISTS public.feature_flags;
DROP TABLE IF EXISTS public.tenant_entitlements;
DROP TABLE IF EXISTS public.tenant_module_enablements;
DROP TABLE IF EXISTS public.core_module_dependencies;
DROP TABLE IF EXISTS public.core_modules;
DROP TRIGGER IF EXISTS trg_pc4_secret_reference ON public.secret_references;
DROP FUNCTION IF EXISTS public.pc4_validate_secret_reference();
DROP TABLE IF EXISTS public.secret_references;
DROP TRIGGER IF EXISTS trg_pc4_configuration_value ON public.configuration_values;
DROP FUNCTION IF EXISTS public.pc4_validate_configuration_value();
DROP TABLE IF EXISTS public.configuration_values;
DROP TABLE IF EXISTS public.configuration_definitions;
