DROP TRIGGER IF EXISTS trg_pc5_audit_immutable ON public.audit_evidence;
DROP FUNCTION IF EXISTS public.pc5_guard_audit_immutability();
DROP TRIGGER IF EXISTS trg_pc5_assignment_principal ON public.scoped_role_assignments;
DROP TRIGGER IF EXISTS trg_pc5_session_principal ON public.authentication_sessions;
DROP FUNCTION IF EXISTS public.pc5_validate_security_principal();
DROP TABLE IF EXISTS public.audit_evidence;
DROP TABLE IF EXISTS public.support_access_grants;
DROP TABLE IF EXISTS public.approval_decisions;
DROP TABLE IF EXISTS public.protected_action_approvals;
DROP TABLE IF EXISTS public.authorization_policies;
DROP TABLE IF EXISTS public.scoped_role_assignments;
DROP TABLE IF EXISTS public.authorization_role_permissions;
DROP TABLE IF EXISTS public.authorization_roles;
DROP TABLE IF EXISTS public.permission_definitions;
DROP TABLE IF EXISTS public.step_up_grants;
DROP TABLE IF EXISTS public.authentication_sessions;
DROP TABLE IF EXISTS public.device_identities;
DROP TABLE IF EXISTS public.service_identities;
DROP TABLE IF EXISTS public.identity_compatibility_mappings;
DROP TABLE IF EXISTS public.identity_memberships;
DROP TABLE IF EXISTS public.identity_credential_references;
DROP TABLE IF EXISTS public.identities;
DROP TABLE IF EXISTS public.security_commands;
