CREATE TABLE public.security_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_key VARCHAR(180) NOT NULL UNIQUE,
    request_fingerprint CHAR(64) NOT NULL,
    command_type VARCHAR(80) NOT NULL,
    result_table VARCHAR(80), result_id BIGINT, completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    login_name VARCHAR(254) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    party_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_identities_login UNIQUE(login_name),
    CONSTRAINT ck_identities_status CHECK(status IN ('invited','active','suspended','revoked','retired'))
);

CREATE TABLE public.identity_credential_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id BIGINT NOT NULL REFERENCES public.identities(id) ON DELETE RESTRICT,
    mechanism VARCHAR(40) NOT NULL,
    credential_reference VARCHAR(180) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ,
    CONSTRAINT uq_identity_credential_reference UNIQUE(identity_id,mechanism,credential_reference),
    CONSTRAINT ck_identity_credential_reference_only CHECK(credential_reference !~* '(password|token=|secret=)')
);

CREATE TABLE public.identity_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    identity_id BIGINT NOT NULL REFERENCES public.identities(id) ON DELETE RESTRICT,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE RESTRICT,
    party_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    invitation_state VARCHAR(20) NOT NULL DEFAULT 'accepted',
    valid_from TIMESTAMPTZ NOT NULL, valid_to TIMESTAMPTZ, revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_identity_membership_period UNIQUE(identity_id,tenant_id,valid_from),
    CONSTRAINT fk_identity_membership_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_identity_membership_status CHECK(status IN ('invited','active','suspended','revoked','retired')),
    CONSTRAINT ck_identity_membership_period CHECK(valid_to IS NULL OR valid_to>valid_from)
);

CREATE TABLE public.identity_compatibility_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_authority VARCHAR(80) NOT NULL, source_record_id VARCHAR(180) NOT NULL,
    identity_id BIGINT NOT NULL REFERENCES public.identities(id) ON DELETE RESTRICT,
    membership_id BIGINT REFERENCES public.identity_memberships(id) ON DELETE RESTRICT,
    compatibility_path VARCHAR(40) NOT NULL DEFAULT 'bridge', retirement_milestone VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_identity_compatibility_source UNIQUE(source_authority,source_record_id)
);

CREATE TABLE public.service_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    service_code VARCHAR(160) NOT NULL, owner_module VARCHAR(80) NOT NULL,
    tenant_id INTEGER REFERENCES public.tenants(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'active', credential_reference VARCHAR(180) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ,
    CONSTRAINT uq_service_identity_scope UNIQUE(tenant_id,service_code),
    CONSTRAINT ck_service_credential_reference_only CHECK(credential_reference !~* '(password|token=|secret=)')
);

CREATE TABLE public.device_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    device_code VARCHAR(160) NOT NULL, tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE RESTRICT,
    location_id BIGINT, organization_unit_id BIGINT, status VARCHAR(20) NOT NULL DEFAULT 'active',
    assurance_level SMALLINT NOT NULL DEFAULT 1, enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ,
    last_observed_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_device_identity_scope UNIQUE(tenant_id,device_code),
    CONSTRAINT fk_device_location FOREIGN KEY(tenant_id,location_id) REFERENCES public.locations(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_organization FOREIGN KEY(tenant_id,organization_unit_id) REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_device_assurance CHECK(assurance_level BETWEEN 1 AND 4)
);

CREATE TABLE public.authentication_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    principal_id BIGINT NOT NULL,
    tenant_id INTEGER REFERENCES public.tenants(id) ON DELETE RESTRICT,
    actor_type VARCHAR(20) NOT NULL DEFAULT 'human', assurance_level SMALLINT NOT NULL DEFAULT 1,
    authenticated_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ, revocation_version INTEGER NOT NULL DEFAULT 0,
    device_identity_id BIGINT REFERENCES public.device_identities(id) ON DELETE RESTRICT,
    client_context JSONB NOT NULL DEFAULT '{}'::jsonb, correlation_id VARCHAR(180), last_security_activity_at TIMESTAMPTZ,
    CONSTRAINT ck_authentication_session_period CHECK(expires_at>authenticated_at),
    CONSTRAINT ck_authentication_session_assurance CHECK(assurance_level BETWEEN 1 AND 4),
    CONSTRAINT ck_authentication_session_actor CHECK(actor_type IN ('human','service','device','system'))
);

CREATE TABLE public.step_up_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.authentication_sessions(id) ON DELETE RESTRICT,
    assurance_level SMALLINT NOT NULL, scope_type VARCHAR(30), scope_id BIGINT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ,
    CONSTRAINT ck_step_up_assurance CHECK(assurance_level BETWEEN 2 AND 4),
    CONSTRAINT ck_step_up_period CHECK(expires_at>granted_at),
    CONSTRAINT ck_step_up_scope CHECK((scope_type IS NULL AND scope_id IS NULL) OR (scope_type IN ('tenant','legal_entity','organization_unit','location') AND scope_id IS NOT NULL))
);

CREATE TABLE public.permission_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(260) NOT NULL UNIQUE, owner_module VARCHAR(80) NOT NULL,
    resource_code VARCHAR(80) NOT NULL, action_code VARCHAR(80) NOT NULL, description TEXT,
    risk_class VARCHAR(30) NOT NULL DEFAULT 'ordinary', allowed_scopes TEXT[] NOT NULL,
    required_assurance SMALLINT NOT NULL DEFAULT 1, approval_profile VARCHAR(160), status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_permission_namespaced CHECK(permission_code ~ '^[a-z][a-z0-9_-]{1,63}(\.[a-z][a-z0-9_-]{0,63}){2,3}$'),
    CONSTRAINT ck_permission_assurance CHECK(required_assurance BETWEEN 1 AND 4),
    CONSTRAINT ck_permission_scopes CHECK(cardinality(allowed_scopes)>0 AND allowed_scopes <@ ARRAY['platform','tenant','legal_entity','organization_unit','location']::text[])
);

CREATE TABLE public.authorization_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    tenant_id INTEGER REFERENCES public.tenants(id) ON DELETE RESTRICT,
    role_code VARCHAR(160) NOT NULL, display_name VARCHAR(180), status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_authorization_role_scope UNIQUE NULLS NOT DISTINCT(tenant_id,role_code)
);

CREATE TABLE public.authorization_role_permissions (
    role_id BIGINT NOT NULL REFERENCES public.authorization_roles(id) ON DELETE RESTRICT,
    permission_id BIGINT NOT NULL REFERENCES public.permission_definitions(id) ON DELETE RESTRICT,
    effective_from TIMESTAMPTZ NOT NULL DEFAULT now(), effective_to TIMESTAMPTZ,
    PRIMARY KEY(role_id,permission_id,effective_from),
    CONSTRAINT ck_role_permission_period CHECK(effective_to IS NULL OR effective_to>effective_from)
);

CREATE TABLE public.scoped_role_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    principal_id BIGINT NOT NULL, actor_type VARCHAR(20) NOT NULL DEFAULT 'human',
    tenant_id INTEGER REFERENCES public.tenants(id) ON DELETE RESTRICT,
    role_id BIGINT NOT NULL REFERENCES public.authorization_roles(id) ON DELETE RESTRICT,
    scope_type VARCHAR(30) NOT NULL, scope_id BIGINT, status VARCHAR(20) NOT NULL DEFAULT 'active',
    valid_from TIMESTAMPTZ NOT NULL, valid_to TIMESTAMPTZ,
    CONSTRAINT uq_scoped_role_assignment UNIQUE NULLS NOT DISTINCT(principal_id,actor_type,tenant_id,role_id,scope_type,scope_id,valid_from),
    CONSTRAINT ck_role_assignment_actor CHECK(actor_type IN ('human','service','device')),
    CONSTRAINT ck_role_assignment_scope CHECK((scope_type='platform' AND tenant_id IS NULL AND scope_id IS NULL) OR (scope_type='tenant' AND tenant_id IS NOT NULL AND scope_id=tenant_id) OR (scope_type IN ('legal_entity','organization_unit','location') AND tenant_id IS NOT NULL AND scope_id IS NOT NULL)),
    CONSTRAINT ck_role_assignment_period CHECK(valid_to IS NULL OR valid_to>valid_from)
);

CREATE TABLE public.authorization_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER REFERENCES public.tenants(id) ON DELETE RESTRICT,
    policy_code VARCHAR(160) NOT NULL, permission_code VARCHAR(260) NOT NULL REFERENCES public.permission_definitions(permission_code) ON DELETE RESTRICT,
    required_assurance SMALLINT NOT NULL DEFAULT 1, approval_profile VARCHAR(160), amount_threshold NUMERIC(28,8),
    status VARCHAR(20) NOT NULL DEFAULT 'active', effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ,
    CONSTRAINT uq_authorization_policy_version UNIQUE NULLS NOT DISTINCT(tenant_id,policy_code,effective_from),
    CONSTRAINT ck_authorization_policy_period CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_authorization_policy_assurance CHECK(required_assurance BETWEEN 1 AND 4)
);

CREATE TABLE public.protected_action_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE, tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE RESTRICT,
    requester_identity_id BIGINT NOT NULL REFERENCES public.identities(id) ON DELETE RESTRICT,
    permission_code VARCHAR(260) NOT NULL REFERENCES public.permission_definitions(permission_code) ON DELETE RESTRICT,
    action_fingerprint CHAR(64) NOT NULL, scope_type VARCHAR(30) NOT NULL, scope_id BIGINT NOT NULL,
    required_approvals SMALLINT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, request_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending', requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_approval_count CHECK(required_approvals>0)
);

CREATE TABLE public.approval_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_id BIGINT NOT NULL REFERENCES public.protected_action_approvals(id) ON DELETE RESTRICT,
    approver_identity_id BIGINT NOT NULL REFERENCES public.identities(id) ON DELETE RESTRICT,
    approved BOOLEAN NOT NULL, reason TEXT NOT NULL, decided_at TIMESTAMPTZ NOT NULL, decision_fingerprint CHAR(64) NOT NULL,
    CONSTRAINT uq_approval_decision UNIQUE(approval_id,approver_identity_id)
);

CREATE TABLE public.support_access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    operator_identity_id BIGINT NOT NULL REFERENCES public.identities(id) ON DELETE RESTRICT,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE RESTRICT,
    permission_code VARCHAR(260) NOT NULL REFERENCES public.permission_definitions(permission_code) ON DELETE RESTRICT,
    scope_type VARCHAR(30) NOT NULL, scope_id BIGINT NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ,
    reason TEXT NOT NULL, approval_public_id UUID NOT NULL, break_glass BOOLEAN NOT NULL DEFAULT false,
    grant_fingerprint CHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_support_access_period CHECK(expires_at>effective_from AND expires_at<=effective_from+INTERVAL '8 hours'),
    CONSTRAINT ck_support_access_scope CHECK(scope_type IN ('tenant','legal_entity','organization_unit','location'))
);

CREATE TABLE public.audit_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE, tenant_id INTEGER REFERENCES public.tenants(id) ON DELETE RESTRICT,
    actor_identity_id BIGINT, actor_type VARCHAR(20) NOT NULL,
    action_code VARCHAR(180) NOT NULL, target_type VARCHAR(160) NOT NULL, target_id VARCHAR(260) NOT NULL,
    outcome VARCHAR(40) NOT NULL, reason TEXT, occurred_at TIMESTAMPTZ NOT NULL, correlation_id VARCHAR(180) NOT NULL,
    source_module VARCHAR(80) NOT NULL, session_public_id UUID, authorization_reference VARCHAR(180), approval_public_id UUID,
    scope_type VARCHAR(30), scope_id BIGINT, safe_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    prior_evidence_id UUID REFERENCES public.audit_evidence(public_id) ON DELETE RESTRICT, evidence_fingerprint CHAR(64) NOT NULL,
    delegation_public_id UUID REFERENCES public.support_access_grants(public_id) ON DELETE RESTRICT,
    accepted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_audit_actor CHECK(actor_type IN ('human','service','device','system')),
    CONSTRAINT ck_audit_safe_metadata CHECK(NOT (safe_metadata::text ~* '(password|password_hash|token|secret|credential|authorization)'))
);

CREATE INDEX ix_sessions_active ON public.authentication_sessions(principal_id,actor_type,tenant_id,expires_at) WHERE revoked_at IS NULL;
CREATE INDEX ix_role_assignments_active ON public.scoped_role_assignments(principal_id,actor_type,tenant_id,scope_type,scope_id) WHERE status='active';
CREATE INDEX ix_audit_tenant_time ON public.audit_evidence(tenant_id,occurred_at,public_id);
CREATE INDEX ix_audit_actor ON public.audit_evidence(tenant_id,actor_identity_id,occurred_at);
CREATE INDEX ix_audit_correlation ON public.audit_evidence(correlation_id);

CREATE FUNCTION public.pc5_validate_security_principal() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.actor_type='human' AND NOT EXISTS(SELECT 1 FROM public.identities WHERE id=NEW.principal_id AND status='active') THEN
        RAISE EXCEPTION 'human_identity_not_active' USING ERRCODE='23514';
    ELSIF NEW.actor_type='service' AND NOT EXISTS(SELECT 1 FROM public.service_identities WHERE id=NEW.principal_id AND status='active' AND tenant_id IS NOT DISTINCT FROM NEW.tenant_id) THEN
        RAISE EXCEPTION 'service_identity_not_active_or_cross_tenant' USING ERRCODE='23514';
    ELSIF NEW.actor_type='device' AND NOT EXISTS(SELECT 1 FROM public.device_identities WHERE id=NEW.principal_id AND status='active' AND tenant_id=NEW.tenant_id) THEN
        RAISE EXCEPTION 'device_identity_not_active_or_cross_tenant' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_pc5_session_principal BEFORE INSERT OR UPDATE ON public.authentication_sessions FOR EACH ROW EXECUTE FUNCTION public.pc5_validate_security_principal();
CREATE TRIGGER trg_pc5_assignment_principal BEFORE INSERT OR UPDATE ON public.scoped_role_assignments FOR EACH ROW EXECUTE FUNCTION public.pc5_validate_security_principal();

CREATE FUNCTION public.pc5_guard_audit_immutability() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_evidence_append_only' USING ERRCODE='55000';
END $$;
CREATE TRIGGER trg_pc5_audit_immutable BEFORE UPDATE OR DELETE ON public.audit_evidence
FOR EACH ROW EXECUTE FUNCTION public.pc5_guard_audit_immutability();

INSERT INTO public.permission_definitions(permission_code,owner_module,resource_code,action_code,risk_class,allowed_scopes,required_assurance)
VALUES
('pc5.audit.evidence.query','pc5','audit','query','high',ARRAY['platform','tenant','legal_entity','organization_unit','location'],2),
('pc5.identity.membership.manage','pc5','membership','manage','high',ARRAY['platform','tenant'],2),
('pc5.authorization.role.manage','pc5','role','manage','high',ARRAY['platform','tenant'],2);

COMMENT ON TABLE public.identities IS 'Global authentication principals; never Party or authorization role authority.';
COMMENT ON TABLE public.audit_evidence IS 'Append-only generic action evidence; never financial economic truth or delivery outbox.';
