CREATE TABLE public.pk_pack_commands(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 scope_key VARCHAR(160) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 request_fingerprint VARCHAR(64) NOT NULL,
 command_type VARCHAR(80) NOT NULL,
 result_table VARCHAR(120) NULL,
 result_id BIGINT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 completed_at TIMESTAMPTZ NULL,
 CONSTRAINT uq_pk_pack_commands_scope UNIQUE(scope_key,command_key),
 CONSTRAINT ck_pk_pack_command_fingerprint CHECK(length(request_fingerprint)=64)
);

CREATE TABLE public.pk_packs(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 pack_code VARCHAR(120) NOT NULL,
 owner_code VARCHAR(120) NOT NULL,
 pack_kind VARCHAR(40) NOT NULL,
 lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT uq_pk_packs_public UNIQUE(public_id),
 CONSTRAINT uq_pk_packs_code UNIQUE(pack_code),
 CONSTRAINT ck_pk_pack_code CHECK(pack_code=lower(btrim(pack_code))),
 CONSTRAINT ck_pk_pack_lifecycle CHECK(lifecycle IN ('active','deprecated','retired')),
 CONSTRAINT ck_pk_pack_kind CHECK(pack_kind IN ('capability','industry','country','tax','payment_connector','communication_connector','accounting_connector','integration_connector'))
);

CREATE TABLE public.pk_pack_versions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 pack_id BIGINT NOT NULL,
 pack_version VARCHAR(64) NOT NULL,
 kernel_min VARCHAR(64) NOT NULL,
 kernel_max VARCHAR(64) NULL,
 manifest_json JSONB NOT NULL,
 manifest_sha256 VARCHAR(64) NOT NULL,
 retention_required BOOLEAN NOT NULL DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pk_pack_version_pack FOREIGN KEY(pack_id) REFERENCES public.pk_packs(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_pack_versions_public UNIQUE(public_id),
 CONSTRAINT uq_pk_pack_versions_identity UNIQUE(pack_id,pack_version),
 CONSTRAINT uq_pk_pack_versions_pack_id_id UNIQUE(pack_id,id),
 CONSTRAINT ck_pk_pack_version_sha CHECK(length(manifest_sha256)=64)
);

CREATE OR REPLACE FUNCTION public.pk_reject_pack_version_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'pk_pack_version_immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER trg_pk_pack_version_immutable BEFORE UPDATE OR DELETE ON public.pk_pack_versions FOR EACH ROW EXECUTE FUNCTION public.pk_reject_pack_version_mutation();

CREATE TABLE public.pk_pack_dependencies(
 pack_version_id BIGINT NOT NULL,
 dependency_pack_code VARCHAR(120) NOT NULL,
 version_spec VARCHAR(120) NOT NULL,
 required BOOLEAN NOT NULL DEFAULT true,
 PRIMARY KEY(pack_version_id,dependency_pack_code),
 CONSTRAINT fk_pk_pack_dependency_version FOREIGN KEY(pack_version_id) REFERENCES public.pk_pack_versions(id) ON DELETE RESTRICT,
 CONSTRAINT ck_pk_pack_dependency_code CHECK(dependency_pack_code=lower(btrim(dependency_pack_code)))
);

CREATE TABLE public.pk_pack_extensions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 pack_version_id BIGINT NOT NULL,
 extension_code VARCHAR(120) NOT NULL,
 extension_kind VARCHAR(40) NOT NULL,
 target_authority VARCHAR(160) NOT NULL,
 public_interface VARCHAR(300) NOT NULL,
 declaration_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 CONSTRAINT fk_pk_pack_extension_version FOREIGN KEY(pack_version_id) REFERENCES public.pk_pack_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_pack_extension UNIQUE(pack_version_id,extension_code),
 CONSTRAINT ck_pk_pack_extension_kind CHECK(extension_kind IN ('configuration','semantics','navigation','workflow','document','report','connector','finance_conformance','localization')),
 CONSTRAINT ck_pk_pack_extension_interface CHECK(public_interface !~* '(sql_repository|private|table:|insert[[:space:]]|update[[:space:]]|delete[[:space:]]|drop[[:space:]]|alter[[:space:]])')
);

CREATE TABLE public.pk_connector_declarations(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 pack_version_id BIGINT NOT NULL,
 connector_code VARCHAR(120) NOT NULL,
 connector_kind VARCHAR(40) NOT NULL,
 provider_code VARCHAR(120) NOT NULL,
 capabilities TEXT[] NOT NULL DEFAULT '{}',
 provider_idempotency VARCHAR(32) NOT NULL,
 external_reference_lookup BOOLEAN NOT NULL,
 callback_identity_mode VARCHAR(120) NOT NULL,
 finality_policy JSONB NOT NULL,
 destination_kinds TEXT[] NOT NULL DEFAULT '{}',
 secret_reference_keys TEXT[] NOT NULL DEFAULT '{}',
 ambiguous_outcome_policy VARCHAR(120) NOT NULL,
 raw_payload_policy VARCHAR(80) NOT NULL,
 CONSTRAINT fk_pk_connector_version FOREIGN KEY(pack_version_id) REFERENCES public.pk_pack_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_connector UNIQUE(pack_version_id,connector_code),
 CONSTRAINT ck_pk_connector_kind CHECK(connector_kind IN ('payment_provider','communication_provider','accounting_provider','external_system')),
 CONSTRAINT ck_pk_provider_idempotency CHECK(provider_idempotency IN ('native','external_reference','unsupported')),
 CONSTRAINT ck_pk_raw_payload_policy CHECK(raw_payload_policy IN ('sanitized_only','sanitized_or_encrypted_only','encrypted_reference_only','forbidden'))
);

CREATE TABLE public.pk_tenant_pack_installations(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 pack_id BIGINT NOT NULL,
 pack_version_id BIGINT NOT NULL,
 lifecycle_status VARCHAR(16) NOT NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 retain_data BOOLEAN NOT NULL DEFAULT true,
 staged_at TIMESTAMPTZ NOT NULL,
 installed_at TIMESTAMPTZ NULL,
 activated_at TIMESTAMPTZ NULL,
 disabled_at TIMESTAMPTZ NULL,
 removed_at TIMESTAMPTZ NULL,
 CONSTRAINT fk_pk_install_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_install_pack FOREIGN KEY(pack_id) REFERENCES public.pk_packs(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_install_version FOREIGN KEY(pack_id,pack_version_id) REFERENCES public.pk_pack_versions(pack_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_install_public UNIQUE(public_id),
 CONSTRAINT uq_pk_install_tenant_id UNIQUE(tenant_id,id),
 CONSTRAINT uq_pk_install_tenant_pack UNIQUE(tenant_id,pack_id),
 CONSTRAINT ck_pk_install_status CHECK(lifecycle_status IN ('staged','installed','active','disabled','removed')),
 CONSTRAINT ck_pk_install_row_version CHECK(row_version>0)
);

CREATE TABLE public.pk_pack_installation_history(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 installation_id BIGINT NOT NULL,
 sequence INTEGER NOT NULL,
 from_status VARCHAR(16) NULL,
 to_status VARCHAR(16) NOT NULL,
 pack_version_id BIGINT NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 reason VARCHAR(500) NULL,
 CONSTRAINT fk_pk_history_install FOREIGN KEY(tenant_id,installation_id) REFERENCES public.pk_tenant_pack_installations(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_history_version FOREIGN KEY(pack_version_id) REFERENCES public.pk_pack_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_history_sequence UNIQUE(tenant_id,installation_id,sequence),
 CONSTRAINT ck_pk_history_from CHECK(from_status IS NULL OR from_status IN ('staged','installed','active','disabled','removed')),
 CONSTRAINT ck_pk_history_to CHECK(to_status IN ('staged','installed','active','disabled','removed'))
);
CREATE OR REPLACE FUNCTION public.pk_history_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'pk_pack_history_immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER trg_pk_pack_history_immutable BEFORE UPDATE OR DELETE ON public.pk_pack_installation_history FOR EACH ROW EXECUTE FUNCTION public.pk_history_immutable();

CREATE INDEX ix_pk_pack_dependencies_code ON public.pk_pack_dependencies(dependency_pack_code);
CREATE INDEX ix_pk_pack_extensions_authority ON public.pk_pack_extensions(target_authority,extension_kind);
CREATE INDEX ix_pk_connector_provider ON public.pk_connector_declarations(provider_code,connector_kind);
CREATE INDEX ix_pk_install_tenant_status ON public.pk_tenant_pack_installations(tenant_id,lifecycle_status);
