CREATE TABLE public.pk_pack_certifications(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 pack_version_id BIGINT NOT NULL,
 certification_code VARCHAR(120) NOT NULL,
 suite_version VARCHAR(64) NOT NULL,
 manifest_sha256 VARCHAR(64) NOT NULL,
 evidence_sha256 VARCHAR(64) NOT NULL,
 result VARCHAR(16) NOT NULL,
 checks_json JSONB NOT NULL,
 notes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 certified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pk_cert_pack_version FOREIGN KEY(pack_version_id) REFERENCES public.pk_pack_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_cert_public UNIQUE(public_id),
 CONSTRAINT uq_pk_cert_identity UNIQUE(pack_version_id,certification_code,suite_version,evidence_sha256),
 CONSTRAINT ck_pk_cert_manifest_sha CHECK(length(manifest_sha256)=64),
 CONSTRAINT ck_pk_cert_evidence_sha CHECK(length(evidence_sha256)=64),
 CONSTRAINT ck_pk_cert_result CHECK(result IN ('pass','fail'))
);
CREATE OR REPLACE FUNCTION public.pk_reject_certification_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'pk_pack_certification_immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER trg_pk_pack_certification_immutable BEFORE UPDATE OR DELETE ON public.pk_pack_certifications FOR EACH ROW EXECUTE FUNCTION public.pk_reject_certification_mutation();

CREATE TABLE public.pk_templates(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 template_code VARCHAR(120) NOT NULL,
 owner_code VARCHAR(120) NOT NULL,
 lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT uq_pk_templates_public UNIQUE(public_id),
 CONSTRAINT uq_pk_templates_code UNIQUE(template_code),
 CONSTRAINT ck_pk_template_code CHECK(template_code=lower(btrim(template_code))),
 CONSTRAINT ck_pk_template_lifecycle CHECK(lifecycle IN ('active','deprecated','retired'))
);

CREATE TABLE public.pk_template_versions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 template_id BIGINT NOT NULL,
 template_version VARCHAR(64) NOT NULL,
 industry_semantic_ref VARCHAR(240) NOT NULL,
 operating_model_semantic_ref VARCHAR(240) NOT NULL,
 template_json JSONB NOT NULL,
 template_sha256 VARCHAR(64) NOT NULL,
 allowed_override_paths TEXT[] NOT NULL DEFAULT '{}',
 configuration_defaults JSONB NOT NULL DEFAULT '{}'::jsonb,
 terminology_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 xa_json JSONB NOT NULL DEFAULT '{}'::jsonb,
 semantic_references TEXT[] NOT NULL DEFAULT '{}',
 finance_workspace_exposed BOOLEAN NOT NULL DEFAULT true,
 finance_kernel_required BOOLEAN NOT NULL DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pk_template_version_template FOREIGN KEY(template_id) REFERENCES public.pk_templates(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_template_version_public UNIQUE(public_id),
 CONSTRAINT uq_pk_template_version_identity UNIQUE(template_id,template_version),
 CONSTRAINT uq_pk_template_version_template_id_id UNIQUE(template_id,id),
 CONSTRAINT ck_pk_template_version_sha CHECK(length(template_sha256)=64),
 CONSTRAINT ck_pk_template_finance_kernel_required CHECK(finance_kernel_required=true)
);
CREATE OR REPLACE FUNCTION public.pk_reject_template_version_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'pk_template_version_immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER trg_pk_template_version_immutable BEFORE UPDATE OR DELETE ON public.pk_template_versions FOR EACH ROW EXECUTE FUNCTION public.pk_reject_template_version_mutation();

CREATE TABLE public.pk_template_pack_requirements(
 template_version_id BIGINT NOT NULL,
 pack_code VARCHAR(120) NOT NULL,
 pack_version VARCHAR(64) NOT NULL,
 requirement_kind VARCHAR(16) NOT NULL,
 PRIMARY KEY(template_version_id,pack_code,requirement_kind),
 CONSTRAINT fk_pk_template_requirement_version FOREIGN KEY(template_version_id) REFERENCES public.pk_template_versions(id) ON DELETE RESTRICT,
 CONSTRAINT ck_pk_template_requirement_code CHECK(pack_code=lower(btrim(pack_code))),
 CONSTRAINT ck_pk_template_requirement_kind CHECK(requirement_kind IN ('required','optional','incompatible'))
);

CREATE TABLE public.pk_tenant_template_bindings(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_id UUID NOT NULL DEFAULT gen_random_uuid(),
 tenant_id INTEGER NOT NULL,
 template_id BIGINT NOT NULL,
 template_version_id BIGINT NOT NULL,
 selected_optional_packs TEXT[] NOT NULL DEFAULT '{}',
 applied_plan_sha256 VARCHAR(64) NOT NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 upgraded_at TIMESTAMPTZ NULL,
 CONSTRAINT fk_pk_template_binding_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_template_binding_template FOREIGN KEY(template_id) REFERENCES public.pk_templates(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_template_binding_version FOREIGN KEY(template_id,template_version_id) REFERENCES public.pk_template_versions(template_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_template_binding_public UNIQUE(public_id),
 CONSTRAINT uq_pk_template_binding_tenant_id UNIQUE(tenant_id,id),
 CONSTRAINT uq_pk_template_binding_tenant_template UNIQUE(tenant_id,template_id),
 CONSTRAINT ck_pk_template_binding_plan_sha CHECK(length(applied_plan_sha256)=64),
 CONSTRAINT ck_pk_template_binding_row_version CHECK(row_version>0)
);

CREATE TABLE public.pk_tenant_template_overrides(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 binding_id BIGINT NOT NULL,
 override_path VARCHAR(160) NOT NULL,
 override_json JSONB NOT NULL,
 row_version INTEGER NOT NULL DEFAULT 1,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pk_template_override_binding FOREIGN KEY(tenant_id,binding_id) REFERENCES public.pk_tenant_template_bindings(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_template_override_path UNIQUE(tenant_id,binding_id,override_path),
 CONSTRAINT ck_pk_template_override_path CHECK(override_path=lower(btrim(override_path))),
 CONSTRAINT ck_pk_template_override_row_version CHECK(row_version>0)
);

CREATE TABLE public.pk_tenant_template_history(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id INTEGER NOT NULL,
 binding_id BIGINT NOT NULL,
 sequence INTEGER NOT NULL,
 action VARCHAR(16) NOT NULL,
 from_template_version_id BIGINT NULL,
 to_template_version_id BIGINT NOT NULL,
 plan_sha256 VARCHAR(64) NOT NULL,
 command_key VARCHAR(240) NOT NULL,
 reason VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CONSTRAINT fk_pk_template_history_binding FOREIGN KEY(tenant_id,binding_id) REFERENCES public.pk_tenant_template_bindings(tenant_id,id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_template_history_from FOREIGN KEY(from_template_version_id) REFERENCES public.pk_template_versions(id) ON DELETE RESTRICT,
 CONSTRAINT fk_pk_template_history_to FOREIGN KEY(to_template_version_id) REFERENCES public.pk_template_versions(id) ON DELETE RESTRICT,
 CONSTRAINT uq_pk_template_history_sequence UNIQUE(tenant_id,binding_id,sequence),
 CONSTRAINT ck_pk_template_history_action CHECK(action IN ('apply','upgrade')),
 CONSTRAINT ck_pk_template_history_plan_sha CHECK(length(plan_sha256)=64)
);
CREATE OR REPLACE FUNCTION public.pk_template_history_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'pk_template_history_immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER trg_pk_template_history_immutable BEFORE UPDATE OR DELETE ON public.pk_tenant_template_history FOR EACH ROW EXECUTE FUNCTION public.pk_template_history_immutable();

CREATE INDEX ix_pk_cert_pack_result ON public.pk_pack_certifications(pack_version_id,result);
CREATE INDEX ix_pk_template_requirement_pack ON public.pk_template_pack_requirements(pack_code,requirement_kind);
CREATE INDEX ix_pk_template_binding_tenant ON public.pk_tenant_template_bindings(tenant_id);
CREATE INDEX ix_pk_template_history_binding ON public.pk_tenant_template_history(tenant_id,binding_id,sequence);
