DROP TRIGGER IF EXISTS trg_r1_line_authority ON public.r1_restaurant_order_lines;
DROP FUNCTION IF EXISTS public.r1_validate_line_authorities();
DROP TRIGGER IF EXISTS trg_r1_order_staff_identity ON public.r1_restaurant_order_staff;
DROP TRIGGER IF EXISTS trg_r1_session_staff_identity ON public.r1_restaurant_session_staff;
DROP FUNCTION IF EXISTS public.r1_validate_staff_identity();
DROP TRIGGER IF EXISTS trg_r1_partition_lines_immutable ON public.r1_restaurant_tab_partition_lines;
DROP TRIGGER IF EXISTS trg_r1_partitions_immutable ON public.r1_restaurant_tab_partitions;
DROP TRIGGER IF EXISTS trg_r1_tab_history_immutable ON public.r1_restaurant_tab_history;
DROP TRIGGER IF EXISTS trg_r1_order_history_immutable ON public.r1_restaurant_order_history;
DROP TRIGGER IF EXISTS trg_r1_session_history_immutable ON public.r1_restaurant_session_history;
DROP FUNCTION IF EXISTS public.r1_restaurant_append_only();
DROP TABLE IF EXISTS public.r1_restaurant_tab_history;
DROP TABLE IF EXISTS public.r1_restaurant_order_history;
DROP TABLE IF EXISTS public.r1_restaurant_session_history;
DROP TABLE IF EXISTS public.r1_restaurant_tab_partition_lines;
DROP TABLE IF EXISTS public.r1_restaurant_tab_partitions;
DROP TABLE IF EXISTS public.r1_restaurant_tab_orders;
DROP TABLE IF EXISTS public.r1_restaurant_tabs;
DROP TABLE IF EXISTS public.r1_restaurant_order_lines;
DROP TABLE IF EXISTS public.r1_restaurant_order_staff;
DROP TABLE IF EXISTS public.r1_restaurant_orders;
DROP TABLE IF EXISTS public.r1_restaurant_session_staff;
DROP TABLE IF EXISTS public.r1_restaurant_session_resources;
DROP TABLE IF EXISTS public.r1_restaurant_service_sessions;
DROP TABLE IF EXISTS public.r1_restaurant_resource_profiles;
DROP TABLE IF EXISTS public.r1_restaurant_service_modes;
DROP TABLE IF EXISTS public.r1_restaurant_commands;
