DROP TRIGGER IF EXISTS trg_r2_prep_run_history_immutable ON public.r2_restaurant_preparation_run_history;
DROP TRIGGER IF EXISTS trg_r2_ticket_item_history_immutable ON public.r2_restaurant_ticket_item_history;
DROP TRIGGER IF EXISTS trg_r2_ticket_history_immutable ON public.r2_restaurant_ticket_history;
DROP TRIGGER IF EXISTS trg_r2_modifier_items_immutable ON public.r2_restaurant_order_line_modifier_items;
DROP TRIGGER IF EXISTS trg_r2_modifier_sets_immutable ON public.r2_restaurant_order_line_modifier_sets;
DROP FUNCTION IF EXISTS public.r2_append_only();
DROP TRIGGER IF EXISTS trg_r2_modifier_option_authority ON public.r2_restaurant_modifier_options;
DROP FUNCTION IF EXISTS public.r2_validate_modifier_option_authorities();
DROP TRIGGER IF EXISTS trg_r2_menu_modifier_entry_tenant ON public.r2_restaurant_menu_entry_modifier_groups;
DROP TRIGGER IF EXISTS trg_r2_menu_section_entry_tenant ON public.r2_restaurant_menu_section_entries;
DROP FUNCTION IF EXISTS public.r2_validate_catalog_entry_tenant();
DROP TABLE IF EXISTS public.r2_restaurant_preparation_run_history;
DROP TABLE IF EXISTS public.r2_restaurant_preparation_run_inputs;
DROP TABLE IF EXISTS public.r2_restaurant_preparation_runs;
DROP TABLE IF EXISTS public.r2_restaurant_ticket_item_history;
DROP TABLE IF EXISTS public.r2_restaurant_ticket_history;
DROP TABLE IF EXISTS public.r2_restaurant_ticket_item_dependencies;
DROP TABLE IF EXISTS public.r2_restaurant_preparation_ticket_items;
DROP TABLE IF EXISTS public.r2_restaurant_preparation_tickets;
DROP TABLE IF EXISTS public.r2_restaurant_preparation_components;
DROP TABLE IF EXISTS public.r2_restaurant_preparation_specs;
DROP TABLE IF EXISTS public.r2_restaurant_routing_rules;
DROP TABLE IF EXISTS public.r2_restaurant_station_profiles;
DROP TABLE IF EXISTS public.r2_restaurant_order_line_modifier_items;
DROP TABLE IF EXISTS public.r2_restaurant_order_line_modifier_sets;
DROP TABLE IF EXISTS public.r2_restaurant_menu_entry_modifier_groups;
DROP TABLE IF EXISTS public.r2_restaurant_modifier_options;
DROP TABLE IF EXISTS public.r2_restaurant_modifier_groups;
DROP TABLE IF EXISTS public.r2_restaurant_menu_section_entries;
DROP TABLE IF EXISTS public.r2_restaurant_menu_sections;
DROP TABLE IF EXISTS public.r2_restaurant_commands;
