CREATE TABLE public.semantic_classification_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NULL,
    command_key VARCHAR(160) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    result_table VARCHAR(64) NULL,
    result_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_semantic_classification_commands_tenant
        FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_classification_commands_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_semantic_classification_commands_type CHECK (command_type IN (
        'create_taxonomy_system',
        'create_taxonomy_node',
        'reparent_taxonomy_node',
        'set_tenant_taxonomy_overlay',
        'clear_tenant_taxonomy_overlay',
        'assign_semantic_classification',
        'end_semantic_classification'
    )),
    CONSTRAINT ck_semantic_classification_commands_result CHECK (
        (result_table IS NULL AND result_id IS NULL AND completed_at IS NULL)
        OR
        (result_table IS NOT NULL AND result_id IS NOT NULL AND completed_at IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_semantic_classification_commands_scope_key
    ON public.semantic_classification_commands(tenant_id, command_key) NULLS NOT DISTINCT;

CREATE TABLE public.semantic_taxonomy_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    taxonomy_system_id BIGINT NOT NULL,
    semantic_concept_id BIGINT NOT NULL,
    tenant_id INTEGER NULL,
    node_code VARCHAR(120) NOT NULL,
    lifecycle VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_semantic_taxonomy_nodes_public_id UNIQUE(public_id),
    CONSTRAINT fk_semantic_taxonomy_nodes_system
        FOREIGN KEY(taxonomy_system_id) REFERENCES public.taxonomy_systems(id) ON DELETE RESTRICT,
    CONSTRAINT fk_semantic_taxonomy_nodes_concept
        FOREIGN KEY(semantic_concept_id) REFERENCES public.semantic_concepts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_semantic_taxonomy_nodes_tenant
        FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_taxonomy_nodes_code
        CHECK(node_code=lower(btrim(node_code)) AND length(node_code)>0),
    CONSTRAINT ck_semantic_taxonomy_nodes_lifecycle
        CHECK(lifecycle IN ('active','deprecated','retired')),
    CONSTRAINT ck_semantic_taxonomy_nodes_row_version CHECK(row_version>=1)
);
CREATE UNIQUE INDEX uq_semantic_taxonomy_nodes_scope_code
    ON public.semantic_taxonomy_nodes(taxonomy_system_id, tenant_id, node_code) NULLS NOT DISTINCT;
CREATE INDEX ix_semantic_taxonomy_nodes_system
    ON public.semantic_taxonomy_nodes(taxonomy_system_id, lifecycle, node_code);
CREATE INDEX ix_semantic_taxonomy_nodes_concept
    ON public.semantic_taxonomy_nodes(semantic_concept_id);
CREATE INDEX ix_semantic_taxonomy_nodes_tenant
    ON public.semantic_taxonomy_nodes(tenant_id) WHERE tenant_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.sc41_validate_semantic_taxonomy_node_scope()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    system_tenant INTEGER;
    namespace_scope VARCHAR(16);
    namespace_tenant INTEGER;
BEGIN
    SELECT s.tenant_id INTO system_tenant
      FROM public.taxonomy_systems s WHERE s.id=NEW.taxonomy_system_id;
    SELECT ns.scope,ns.tenant_id INTO namespace_scope,namespace_tenant
      FROM public.semantic_concepts c
      JOIN public.semantic_namespaces ns ON ns.id=c.namespace_id
      WHERE c.id=NEW.semantic_concept_id;

    IF system_tenant IS NOT NULL AND NEW.tenant_id IS DISTINCT FROM system_tenant THEN
        RAISE EXCEPTION 'semantic_taxonomy_system_scope_mismatch' USING ERRCODE='23514';
    END IF;
    IF namespace_scope='tenant' THEN
        IF NEW.tenant_id IS DISTINCT FROM namespace_tenant THEN
            RAISE EXCEPTION 'tenant_semantic_concept_scope_mismatch' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.tenant_id IS NOT NULL THEN
        RAISE EXCEPTION 'non_tenant_concept_requires_global_taxonomy_node' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_semantic_taxonomy_node_scope
BEFORE INSERT OR UPDATE OF taxonomy_system_id,semantic_concept_id,tenant_id
ON public.semantic_taxonomy_nodes FOR EACH ROW
EXECUTE FUNCTION public.sc41_validate_semantic_taxonomy_node_scope();

CREATE TABLE public.semantic_taxonomy_placements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    semantic_taxonomy_node_id BIGINT NOT NULL,
    placement_version INTEGER NOT NULL,
    parent_node_id BIGINT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    source_type VARCHAR(16) NOT NULL,
    source_key VARCHAR(240) NOT NULL,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_semantic_taxonomy_placements_public_id UNIQUE(public_id),
    CONSTRAINT uq_semantic_taxonomy_placement_version UNIQUE(semantic_taxonomy_node_id, placement_version),
    CONSTRAINT uq_semantic_taxonomy_placement_start UNIQUE(semantic_taxonomy_node_id, effective_from),
    CONSTRAINT fk_semantic_taxonomy_placement_node
        FOREIGN KEY(semantic_taxonomy_node_id) REFERENCES public.semantic_taxonomy_nodes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_semantic_taxonomy_placement_parent
        FOREIGN KEY(parent_node_id) REFERENCES public.semantic_taxonomy_nodes(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_taxonomy_placement_version CHECK(placement_version>=1),
    CONSTRAINT ck_semantic_taxonomy_placement_parent CHECK(parent_node_id IS NULL OR parent_node_id<>semantic_taxonomy_node_id),
    CONSTRAINT ck_semantic_taxonomy_placement_period CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_semantic_taxonomy_placement_source CHECK(source_type IN ('kernel','finance','pack','tenant','external','migration')),
    CONSTRAINT ck_semantic_taxonomy_placement_source_key CHECK(length(btrim(source_key))>0),
    CONSTRAINT ck_semantic_taxonomy_placement_provenance CHECK(jsonb_typeof(provenance)='object')
);
CREATE INDEX ix_semantic_taxonomy_placement_effective
    ON public.semantic_taxonomy_placements(semantic_taxonomy_node_id,effective_from,effective_to);
CREATE INDEX ix_semantic_taxonomy_placement_parent
    ON public.semantic_taxonomy_placements(parent_node_id,effective_from,effective_to);

CREATE OR REPLACE FUNCTION public.sc41_validate_semantic_taxonomy_placement()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    child_system BIGINT;
    child_tenant INTEGER;
    parent_system BIGINT;
    parent_tenant INTEGER;
    candidate_range TSTZRANGE;
BEGIN
    SELECT taxonomy_system_id,tenant_id INTO child_system,child_tenant
      FROM public.semantic_taxonomy_nodes WHERE id=NEW.semantic_taxonomy_node_id;

    IF child_tenant IS NULL AND NEW.source_type='tenant' THEN
        RAISE EXCEPTION 'tenant_source_requires_tenant_taxonomy_node' USING ERRCODE='23514';
    END IF;
    IF child_tenant IS NOT NULL AND NEW.source_type NOT IN ('tenant','migration') THEN
        RAISE EXCEPTION 'tenant_taxonomy_node_requires_tenant_or_migration_source' USING ERRCODE='23514';
    END IF;

    IF EXISTS (
        SELECT 1 FROM public.semantic_taxonomy_placements p
        WHERE p.semantic_taxonomy_node_id=NEW.semantic_taxonomy_node_id
          AND p.id<>COALESCE(NEW.id,0)
          AND tstzrange(p.effective_from,COALESCE(p.effective_to,'infinity'::timestamptz),'[)')
              && tstzrange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'::timestamptz),'[)')
    ) THEN
        RAISE EXCEPTION 'overlapping_taxonomy_placement' USING ERRCODE='23514';
    END IF;

    IF NEW.parent_node_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT taxonomy_system_id,tenant_id INTO parent_system,parent_tenant
      FROM public.semantic_taxonomy_nodes WHERE id=NEW.parent_node_id;
    IF parent_system IS DISTINCT FROM child_system THEN
        RAISE EXCEPTION 'cross_taxonomy_system_parent_forbidden' USING ERRCODE='23514';
    END IF;
    IF child_tenant IS NULL AND parent_tenant IS NOT NULL THEN
        RAISE EXCEPTION 'global_taxonomy_node_cannot_inherit_tenant_parent' USING ERRCODE='23514';
    END IF;
    IF child_tenant IS NOT NULL AND parent_tenant IS NOT NULL AND parent_tenant<>child_tenant THEN
        RAISE EXCEPTION 'cross_tenant_taxonomy_parent_forbidden' USING ERRCODE='23514';
    END IF;

    candidate_range := tstzrange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'::timestamptz),'[)');
    IF EXISTS (
        WITH RECURSIVE ancestors(node_id,valid_range) AS (
            SELECT NEW.parent_node_id,candidate_range
            UNION ALL
            SELECT p.parent_node_id,
                   a.valid_range * tstzrange(p.effective_from,COALESCE(p.effective_to,'infinity'::timestamptz),'[)')
            FROM ancestors a
            JOIN public.semantic_taxonomy_placements p ON p.semantic_taxonomy_node_id=a.node_id
            WHERE p.parent_node_id IS NOT NULL
              AND a.valid_range && tstzrange(p.effective_from,COALESCE(p.effective_to,'infinity'::timestamptz),'[)')
        )
        SELECT 1 FROM ancestors WHERE node_id=NEW.semantic_taxonomy_node_id
    ) THEN
        RAISE EXCEPTION 'taxonomy_cycle' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_semantic_taxonomy_placement_validate
BEFORE INSERT ON public.semantic_taxonomy_placements
FOR EACH ROW EXECUTE FUNCTION public.sc41_validate_semantic_taxonomy_placement();

CREATE OR REPLACE FUNCTION public.sc41_assert_effective_taxonomy_acyclic(
    p_taxonomy_system_id BIGINT,
    p_tenant_id INTEGER,
    p_effective_from TIMESTAMPTZ,
    p_effective_to TIMESTAMPTZ
)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    check_at TIMESTAMPTZ;
    cycle_found BOOLEAN;
BEGIN
    FOR check_at IN
        SELECT DISTINCT boundary
        FROM (
            SELECT p_effective_from AS boundary
            UNION ALL
            SELECT p.effective_from
              FROM public.semantic_taxonomy_placements p
              JOIN public.semantic_taxonomy_nodes n ON n.id=p.semantic_taxonomy_node_id
             WHERE n.taxonomy_system_id=p_taxonomy_system_id
               AND p.effective_from>=p_effective_from
               AND (p_effective_to IS NULL OR p.effective_from<p_effective_to)
            UNION ALL
            SELECT p.effective_to
              FROM public.semantic_taxonomy_placements p
              JOIN public.semantic_taxonomy_nodes n ON n.id=p.semantic_taxonomy_node_id
             WHERE n.taxonomy_system_id=p_taxonomy_system_id
               AND p.effective_to IS NOT NULL
               AND p.effective_to>=p_effective_from
               AND (p_effective_to IS NULL OR p.effective_to<p_effective_to)
            UNION ALL
            SELECT o.effective_from
              FROM public.tenant_taxonomy_overlays o
              JOIN public.semantic_taxonomy_nodes n ON n.id=o.semantic_taxonomy_node_id
             WHERE p_tenant_id IS NOT NULL
               AND o.tenant_id=p_tenant_id
               AND n.taxonomy_system_id=p_taxonomy_system_id
               AND o.effective_from>=p_effective_from
               AND (p_effective_to IS NULL OR o.effective_from<p_effective_to)
            UNION ALL
            SELECT o.effective_to
              FROM public.tenant_taxonomy_overlays o
              JOIN public.semantic_taxonomy_nodes n ON n.id=o.semantic_taxonomy_node_id
             WHERE p_tenant_id IS NOT NULL
               AND o.tenant_id=p_tenant_id
               AND n.taxonomy_system_id=p_taxonomy_system_id
               AND o.effective_to IS NOT NULL
               AND o.effective_to>=p_effective_from
               AND (p_effective_to IS NULL OR o.effective_to<p_effective_to)
        ) boundaries
        WHERE boundary IS NOT NULL
        ORDER BY boundary
    LOOP
        WITH RECURSIVE visible_nodes AS (
            SELECT n.id
              FROM public.semantic_taxonomy_nodes n
             WHERE n.taxonomy_system_id=p_taxonomy_system_id
               AND (
                    (p_tenant_id IS NULL AND n.tenant_id IS NULL)
                    OR
                    (p_tenant_id IS NOT NULL AND (n.tenant_id IS NULL OR n.tenant_id=p_tenant_id))
               )
        ), active_placements AS (
            SELECT DISTINCT ON (p.semantic_taxonomy_node_id)
                   p.semantic_taxonomy_node_id AS child_id,
                   p.parent_node_id AS base_parent_id
              FROM public.semantic_taxonomy_placements p
              JOIN visible_nodes v ON v.id=p.semantic_taxonomy_node_id
             WHERE p.effective_from<=check_at
               AND (p.effective_to IS NULL OR check_at<p.effective_to)
             ORDER BY p.semantic_taxonomy_node_id,p.effective_from DESC,p.placement_version DESC
        ), active_overlays AS (
            SELECT DISTINCT ON (o.semantic_taxonomy_node_id)
                   o.semantic_taxonomy_node_id AS child_id,
                   o.parent_override_node_id,
                   o.has_parent_override
              FROM public.tenant_taxonomy_overlays o
              JOIN visible_nodes v ON v.id=o.semantic_taxonomy_node_id
             WHERE p_tenant_id IS NOT NULL
               AND o.tenant_id=p_tenant_id
               AND o.effective_from<=check_at
               AND (o.effective_to IS NULL OR check_at<o.effective_to)
             ORDER BY o.semantic_taxonomy_node_id,o.effective_from DESC,o.overlay_version DESC
        ), edges AS (
            SELECT p.child_id,
                   CASE WHEN o.has_parent_override
                        THEN o.parent_override_node_id ELSE p.base_parent_id END AS parent_id
              FROM active_placements p
              LEFT JOIN active_overlays o ON o.child_id=p.child_id
        ), walk(start_id,current_id,visited,cycle) AS (
            SELECT e.child_id,e.parent_id,ARRAY[e.child_id]::BIGINT[],
                   (e.parent_id=e.child_id)
              FROM edges e
             WHERE e.parent_id IS NOT NULL
            UNION ALL
            SELECT w.start_id,e.parent_id,w.visited||w.current_id,
                   (e.parent_id=ANY(w.visited||w.current_id))
              FROM walk w
              JOIN edges e ON e.child_id=w.current_id
             WHERE w.current_id IS NOT NULL AND NOT w.cycle
        )
        SELECT EXISTS(SELECT 1 FROM walk WHERE cycle) INTO cycle_found;

        IF cycle_found THEN
            RAISE EXCEPTION 'effective_taxonomy_cycle' USING ERRCODE='23514';
        END IF;
    END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.sc41_validate_effective_cycles_after_placement()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    system_id BIGINT;
    node_tenant INTEGER;
    overlay_tenant INTEGER;
BEGIN
    SELECT taxonomy_system_id,tenant_id INTO system_id,node_tenant
      FROM public.semantic_taxonomy_nodes WHERE id=NEW.semantic_taxonomy_node_id;

    IF node_tenant IS NULL THEN
        PERFORM public.sc41_assert_effective_taxonomy_acyclic(system_id,NULL,NEW.effective_from,NEW.effective_to);
        FOR overlay_tenant IN
            SELECT DISTINCT o.tenant_id
              FROM public.tenant_taxonomy_overlays o
              JOIN public.semantic_taxonomy_nodes n ON n.id=o.semantic_taxonomy_node_id
             WHERE n.taxonomy_system_id=system_id
               AND tstzrange(o.effective_from,COALESCE(o.effective_to,'infinity'::timestamptz),'[)')
                   && tstzrange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'::timestamptz),'[)')
        LOOP
            PERFORM public.sc41_assert_effective_taxonomy_acyclic(system_id,overlay_tenant,NEW.effective_from,NEW.effective_to);
        END LOOP;
    ELSE
        PERFORM public.sc41_assert_effective_taxonomy_acyclic(system_id,node_tenant,NEW.effective_from,NEW.effective_to);
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_semantic_taxonomy_placement_effective_cycle
AFTER INSERT ON public.semantic_taxonomy_placements
FOR EACH ROW EXECUTE FUNCTION public.sc41_validate_effective_cycles_after_placement();

CREATE OR REPLACE FUNCTION public.sc41_protect_semantic_taxonomy_placement()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION 'semantic_taxonomy_placement_is_historical' USING ERRCODE='23514';
    END IF;
    IF OLD.effective_to IS NOT NULL OR NEW.effective_to IS NULL OR NEW.effective_to<=OLD.effective_from THEN
        RAISE EXCEPTION 'invalid_taxonomy_placement_close' USING ERRCODE='23514';
    END IF;
    IF NEW.semantic_taxonomy_node_id<>OLD.semantic_taxonomy_node_id
       OR NEW.placement_version<>OLD.placement_version
       OR NEW.parent_node_id IS DISTINCT FROM OLD.parent_node_id
       OR NEW.sort_order<>OLD.sort_order
       OR NEW.effective_from<>OLD.effective_from
       OR NEW.source_type<>OLD.source_type
       OR NEW.source_key<>OLD.source_key
       OR NEW.provenance<>OLD.provenance
       OR NEW.public_id<>OLD.public_id THEN
        RAISE EXCEPTION 'semantic_taxonomy_placement_mutation_forbidden' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_semantic_taxonomy_placement_protect
BEFORE UPDATE OR DELETE ON public.semantic_taxonomy_placements
FOR EACH ROW EXECUTE FUNCTION public.sc41_protect_semantic_taxonomy_placement();

CREATE TABLE public.tenant_taxonomy_overlays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    semantic_taxonomy_node_id BIGINT NOT NULL,
    overlay_version INTEGER NOT NULL,
    local_label VARCHAR(240) NULL,
    local_sort_order INTEGER NULL,
    parent_override_node_id BIGINT NULL,
    has_parent_override BOOLEAN NOT NULL DEFAULT false,
    is_suppressed BOOLEAN NOT NULL DEFAULT false,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    source_type VARCHAR(16) NOT NULL,
    source_key VARCHAR(240) NOT NULL,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_taxonomy_overlays_public_id UNIQUE(public_id),
    CONSTRAINT uq_tenant_taxonomy_overlay_version UNIQUE(tenant_id,semantic_taxonomy_node_id,overlay_version),
    CONSTRAINT uq_tenant_taxonomy_overlay_start UNIQUE(tenant_id,semantic_taxonomy_node_id,effective_from),
    CONSTRAINT fk_tenant_taxonomy_overlays_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tenant_taxonomy_overlays_node FOREIGN KEY(semantic_taxonomy_node_id) REFERENCES public.semantic_taxonomy_nodes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tenant_taxonomy_overlays_parent FOREIGN KEY(parent_override_node_id) REFERENCES public.semantic_taxonomy_nodes(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tenant_taxonomy_overlay_version CHECK(overlay_version>=1),
    CONSTRAINT ck_tenant_taxonomy_overlay_label CHECK(local_label IS NULL OR length(btrim(local_label))>0),
    CONSTRAINT ck_tenant_taxonomy_overlay_parent CHECK(parent_override_node_id IS NULL OR parent_override_node_id<>semantic_taxonomy_node_id),
    CONSTRAINT ck_tenant_taxonomy_overlay_parent_flag CHECK(has_parent_override OR parent_override_node_id IS NULL),
    CONSTRAINT ck_tenant_taxonomy_overlay_period CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_tenant_taxonomy_overlay_source CHECK(source_type IN ('pack','tenant','template','migration')),
    CONSTRAINT ck_tenant_taxonomy_overlay_source_key CHECK(length(btrim(source_key))>0),
    CONSTRAINT ck_tenant_taxonomy_overlay_provenance CHECK(jsonb_typeof(provenance)='object')
);
CREATE INDEX ix_tenant_taxonomy_overlay_effective
    ON public.tenant_taxonomy_overlays(tenant_id,semantic_taxonomy_node_id,effective_from,effective_to);

CREATE OR REPLACE FUNCTION public.sc41_validate_tenant_taxonomy_overlay()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    node_system BIGINT;
    node_tenant INTEGER;
    parent_system BIGINT;
    parent_tenant INTEGER;
BEGIN
    SELECT taxonomy_system_id,tenant_id INTO node_system,node_tenant
      FROM public.semantic_taxonomy_nodes WHERE id=NEW.semantic_taxonomy_node_id;
    IF node_tenant IS NOT NULL AND node_tenant<>NEW.tenant_id THEN
        RAISE EXCEPTION 'cross_tenant_taxonomy_overlay_forbidden' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM public.tenant_taxonomy_overlays o
        WHERE o.tenant_id=NEW.tenant_id
          AND o.semantic_taxonomy_node_id=NEW.semantic_taxonomy_node_id
          AND o.id<>COALESCE(NEW.id,0)
          AND tstzrange(o.effective_from,COALESCE(o.effective_to,'infinity'::timestamptz),'[)')
              && tstzrange(NEW.effective_from,COALESCE(NEW.effective_to,'infinity'::timestamptz),'[)')
    ) THEN
        RAISE EXCEPTION 'overlapping_tenant_taxonomy_overlay' USING ERRCODE='23514';
    END IF;
    IF NEW.parent_override_node_id IS NOT NULL THEN
        SELECT taxonomy_system_id,tenant_id INTO parent_system,parent_tenant
          FROM public.semantic_taxonomy_nodes WHERE id=NEW.parent_override_node_id;
        IF parent_system IS DISTINCT FROM node_system THEN
            RAISE EXCEPTION 'cross_taxonomy_system_parent_override_forbidden' USING ERRCODE='23514';
        END IF;
        IF parent_tenant IS NOT NULL AND parent_tenant<>NEW.tenant_id THEN
            RAISE EXCEPTION 'cross_tenant_parent_override_forbidden' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_tenant_taxonomy_overlay_validate
BEFORE INSERT ON public.tenant_taxonomy_overlays
FOR EACH ROW EXECUTE FUNCTION public.sc41_validate_tenant_taxonomy_overlay();

CREATE OR REPLACE FUNCTION public.sc41_validate_effective_cycles_after_overlay()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    system_id BIGINT;
BEGIN
    SELECT taxonomy_system_id INTO system_id
      FROM public.semantic_taxonomy_nodes WHERE id=NEW.semantic_taxonomy_node_id;
    PERFORM public.sc41_assert_effective_taxonomy_acyclic(
        system_id,NEW.tenant_id,NEW.effective_from,NEW.effective_to
    );
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_tenant_taxonomy_overlay_effective_cycle
AFTER INSERT ON public.tenant_taxonomy_overlays
FOR EACH ROW EXECUTE FUNCTION public.sc41_validate_effective_cycles_after_overlay();

CREATE OR REPLACE FUNCTION public.sc41_protect_tenant_taxonomy_overlay()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION 'tenant_taxonomy_overlay_is_historical' USING ERRCODE='23514';
    END IF;
    IF OLD.effective_to IS NOT NULL OR NEW.effective_to IS NULL OR NEW.effective_to<=OLD.effective_from THEN
        RAISE EXCEPTION 'invalid_tenant_taxonomy_overlay_close' USING ERRCODE='23514';
    END IF;
    IF NEW.tenant_id<>OLD.tenant_id
       OR NEW.semantic_taxonomy_node_id<>OLD.semantic_taxonomy_node_id
       OR NEW.overlay_version<>OLD.overlay_version
       OR NEW.local_label IS DISTINCT FROM OLD.local_label
       OR NEW.local_sort_order IS DISTINCT FROM OLD.local_sort_order
       OR NEW.parent_override_node_id IS DISTINCT FROM OLD.parent_override_node_id
       OR NEW.has_parent_override<>OLD.has_parent_override
       OR NEW.is_suppressed<>OLD.is_suppressed
       OR NEW.effective_from<>OLD.effective_from
       OR NEW.source_type<>OLD.source_type
       OR NEW.source_key<>OLD.source_key
       OR NEW.provenance<>OLD.provenance
       OR NEW.public_id<>OLD.public_id THEN
        RAISE EXCEPTION 'tenant_taxonomy_overlay_mutation_forbidden' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_tenant_taxonomy_overlay_protect
BEFORE UPDATE OR DELETE ON public.tenant_taxonomy_overlays
FOR EACH ROW EXECUTE FUNCTION public.sc41_protect_tenant_taxonomy_overlay();

CREATE TABLE public.semantic_classification_governance (
    assignment_id BIGINT PRIMARY KEY,
    semantic_taxonomy_node_id BIGINT NULL,
    assignment_mode VARCHAR(16) NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    source_key VARCHAR(240) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_semantic_classification_governance_assignment
        FOREIGN KEY(assignment_id) REFERENCES public.classification_assignments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_semantic_classification_governance_node
        FOREIGN KEY(semantic_taxonomy_node_id) REFERENCES public.semantic_taxonomy_nodes(id) ON DELETE RESTRICT,
    CONSTRAINT ck_semantic_classification_governance_mode CHECK(assignment_mode IN ('explicit','inherited','derived','imported')),
    CONSTRAINT ck_semantic_classification_governance_source CHECK(source_type IN ('kernel','finance','pack','tenant','external','template','migration')),
    CONSTRAINT ck_semantic_classification_governance_source_key CHECK(length(btrim(source_key))>0),
    CONSTRAINT ck_semantic_classification_governance_period CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_semantic_classification_governance_provenance CHECK(jsonb_typeof(provenance)='object')
);
CREATE INDEX ix_semantic_classification_governance_node
    ON public.semantic_classification_governance(semantic_taxonomy_node_id,effective_from,effective_to);
CREATE INDEX ix_semantic_classification_governance_effective
    ON public.semantic_classification_governance(effective_from,effective_to);

CREATE OR REPLACE FUNCTION public.sc41_validate_semantic_classification_governance()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    assignment_concept BIGINT;
    assignment_tenant INTEGER;
    node_concept BIGINT;
    node_tenant INTEGER;
BEGIN
    SELECT concept_id,tenant_id INTO assignment_concept,assignment_tenant
      FROM public.classification_assignments WHERE id=NEW.assignment_id;
    IF NEW.semantic_taxonomy_node_id IS NOT NULL THEN
        SELECT semantic_concept_id,tenant_id INTO node_concept,node_tenant
          FROM public.semantic_taxonomy_nodes WHERE id=NEW.semantic_taxonomy_node_id;
        IF node_concept IS DISTINCT FROM assignment_concept THEN
            RAISE EXCEPTION 'classification_node_concept_mismatch' USING ERRCODE='23514';
        END IF;
        IF node_tenant IS NOT NULL AND node_tenant<>assignment_tenant THEN
            RAISE EXCEPTION 'cross_tenant_semantic_classification_forbidden' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_semantic_classification_governance_validate
BEFORE INSERT ON public.semantic_classification_governance
FOR EACH ROW EXECUTE FUNCTION public.sc41_validate_semantic_classification_governance();

CREATE OR REPLACE FUNCTION public.sc41_protect_semantic_classification_governance()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION 'semantic_classification_governance_is_historical' USING ERRCODE='23514';
    END IF;
    IF OLD.effective_to IS NOT NULL OR NEW.effective_to IS NULL OR NEW.effective_to<=OLD.effective_from THEN
        RAISE EXCEPTION 'invalid_semantic_classification_close' USING ERRCODE='23514';
    END IF;
    IF NEW.assignment_id<>OLD.assignment_id
       OR NEW.semantic_taxonomy_node_id IS DISTINCT FROM OLD.semantic_taxonomy_node_id
       OR NEW.assignment_mode<>OLD.assignment_mode
       OR NEW.source_type<>OLD.source_type
       OR NEW.source_key<>OLD.source_key
       OR NEW.effective_from<>OLD.effective_from
       OR NEW.provenance<>OLD.provenance THEN
        RAISE EXCEPTION 'semantic_classification_governance_mutation_forbidden' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_sc41_semantic_classification_governance_protect
BEFORE UPDATE OR DELETE ON public.semantic_classification_governance
FOR EACH ROW EXECUTE FUNCTION public.sc41_protect_semantic_classification_governance();

COMMENT ON TABLE public.semantic_taxonomy_nodes IS
'PC3 descendant global-capable stable taxonomy placement identities. Logical taxonomy tables are taxonomy_systems; hierarchy depth remains arbitrary.';
COMMENT ON TABLE public.semantic_taxonomy_placements IS
'Effective-dated historical parent/sort placement for semantic_taxonomy_nodes; single-parent tree/forest semantics, never DAG-by-default.';
COMMENT ON TABLE public.tenant_taxonomy_overlays IS
'Tenant delta/overlay over inherited global or pack taxonomy nodes; inherited trees are not copied per tenant.';
COMMENT ON TABLE public.semantic_classification_governance IS
'Governance sidecar for frozen PC3 classification_assignments: effective lifecycle, global taxonomy placement and provenance without acquiring target authority.';
COMMENT ON TABLE public.semantic_classification_commands IS
'Tenant-qualified idempotency ledger for descendant semantic-classification commands. Frozen PC3 semantic_commands remains historical compatibility.';
