-- Adopt existing atomic_units identity in place; no legacy ID or relationship is rewritten.
ALTER TABLE public.atomic_units ADD COLUMN public_id UUID NULL;
ALTER TABLE public.atomic_units ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE public.atomic_units ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE public.atomic_units ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
UPDATE public.atomic_units SET public_id = md5('so1:atomic-unit:' || tenant_id::text || ':' || id::text)::uuid WHERE public_id IS NULL;
ALTER TABLE public.atomic_units ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE public.atomic_units ADD CONSTRAINT uq_so1_atomic_units_public_id UNIQUE(public_id);
ALTER TABLE public.atomic_units ADD CONSTRAINT uq_so1_atomic_units_tenant_id_id UNIQUE(tenant_id,id);
ALTER TABLE public.atomic_units ADD CONSTRAINT ck_so1_atomic_units_version CHECK(row_version>=1);
ALTER TABLE public.atomic_units ADD CONSTRAINT ck_so1_atomic_units_sku CHECK(sku IS NULL OR (sku=btrim(sku) AND length(sku)>0));

CREATE TABLE public.so1_catalogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), tenant_id INTEGER NOT NULL,
    code VARCHAR(80) NOT NULL, name VARCHAR(200) NOT NULL,
    scope_type VARCHAR(24) NOT NULL, scope_id BIGINT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_so1_catalogs_public_id UNIQUE(public_id),
    CONSTRAINT uq_so1_catalogs_tenant_id_id UNIQUE(tenant_id,id),
    CONSTRAINT uq_so1_catalogs_tenant_code UNIQUE(tenant_id,code),
    CONSTRAINT fk_so1_catalogs_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_so1_catalogs_scope CHECK(scope_type IN ('tenant','legal_entity','organization_unit','location') AND ((scope_type='tenant' AND scope_id IS NULL) OR (scope_type<>'tenant' AND scope_id IS NOT NULL))),
    CONSTRAINT ck_so1_catalogs_window CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_so1_catalogs_code CHECK(code=btrim(code) AND length(code)>0),
    CONSTRAINT ck_so1_catalogs_name CHECK(length(btrim(name))>0),
    CONSTRAINT ck_so1_catalogs_version CHECK(row_version>=1)
);

CREATE TABLE public.so1_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), tenant_id INTEGER NOT NULL,
    code VARCHAR(80) NOT NULL, name VARCHAR(200) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_so1_offers_public_id UNIQUE(public_id),
    CONSTRAINT uq_so1_offers_tenant_id_id UNIQUE(tenant_id,id),
    CONSTRAINT uq_so1_offers_tenant_code UNIQUE(tenant_id,code),
    CONSTRAINT fk_so1_offers_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_so1_offers_code CHECK(code=btrim(code) AND length(code)>0),
    CONSTRAINT ck_so1_offers_name CHECK(length(btrim(name))>0),
    CONSTRAINT ck_so1_offers_metadata CHECK(jsonb_typeof(metadata)='object'),
    CONSTRAINT ck_so1_offers_version CHECK(row_version>=1)
);

CREATE TABLE public.so1_offer_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL, offer_id BIGINT NOT NULL, atomic_unit_id INTEGER NOT NULL,
    quantity NUMERIC(18,6) NOT NULL, component_rule VARCHAR(16) NOT NULL, sequence INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_so1_offer_components UNIQUE(tenant_id,offer_id,atomic_unit_id),
    CONSTRAINT fk_so1_offer_components_offer FOREIGN KEY(tenant_id,offer_id) REFERENCES public.so1_offers(tenant_id,id) ON DELETE CASCADE,
    CONSTRAINT fk_so1_offer_components_unit FOREIGN KEY(tenant_id,atomic_unit_id) REFERENCES public.atomic_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_so1_offer_components_quantity CHECK(quantity>0),
    CONSTRAINT ck_so1_offer_components_rule CHECK(component_rule IN ('required','optional'))
);

CREATE TABLE public.so1_catalog_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), tenant_id INTEGER NOT NULL, catalog_id BIGINT NOT NULL,
    target_type VARCHAR(16) NOT NULL, atomic_unit_id INTEGER NULL, offer_id BIGINT NULL,
    semantic_reference VARCHAR(240) NULL, sort_order INTEGER NOT NULL DEFAULT 0, enabled BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_so1_catalog_entries_public_id UNIQUE(public_id),
    CONSTRAINT fk_so1_catalog_entries_catalog FOREIGN KEY(tenant_id,catalog_id) REFERENCES public.so1_catalogs(tenant_id,id) ON DELETE CASCADE,
    CONSTRAINT fk_so1_catalog_entries_unit FOREIGN KEY(tenant_id,atomic_unit_id) REFERENCES public.atomic_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_so1_catalog_entries_offer FOREIGN KEY(tenant_id,offer_id) REFERENCES public.so1_offers(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_so1_catalog_entries_target CHECK((target_type='atomic_unit' AND atomic_unit_id IS NOT NULL AND offer_id IS NULL) OR (target_type='offer' AND offer_id IS NOT NULL AND atomic_unit_id IS NULL)),
    CONSTRAINT ck_so1_catalog_entries_window CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_so1_catalog_entries_version CHECK(row_version>=1)
);

CREATE TABLE public.so1_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), tenant_id INTEGER NOT NULL,
    target_type VARCHAR(16) NOT NULL, atomic_unit_id INTEGER NULL, offer_id BIGINT NULL,
    price_code VARCHAR(80) NOT NULL, amount NUMERIC(18,6) NOT NULL, currency CHAR(3) NOT NULL,
    scope_type VARCHAR(24) NOT NULL, scope_id BIGINT NULL, precedence INTEGER NOT NULL DEFAULT 0,
    effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), row_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_so1_prices_public_id UNIQUE(public_id),
    CONSTRAINT fk_so1_prices_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_so1_prices_unit FOREIGN KEY(tenant_id,atomic_unit_id) REFERENCES public.atomic_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_so1_prices_offer FOREIGN KEY(tenant_id,offer_id) REFERENCES public.so1_offers(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_so1_prices_target CHECK((target_type='atomic_unit' AND atomic_unit_id IS NOT NULL AND offer_id IS NULL) OR (target_type='offer' AND offer_id IS NOT NULL AND atomic_unit_id IS NULL)),
    CONSTRAINT ck_so1_prices_amount CHECK(amount>=0),
    CONSTRAINT ck_so1_prices_currency CHECK(currency=upper(currency) AND currency~'^[A-Z]{3}$'),
    CONSTRAINT ck_so1_prices_scope CHECK(scope_type IN ('tenant','legal_entity','organization_unit','location') AND ((scope_type='tenant' AND scope_id IS NULL) OR (scope_type<>'tenant' AND scope_id IS NOT NULL))),
    CONSTRAINT ck_so1_prices_window CHECK(effective_to IS NULL OR effective_to>effective_from),
    CONSTRAINT ck_so1_prices_code CHECK(price_code=btrim(price_code) AND length(price_code)>0),
    CONSTRAINT ck_so1_prices_version CHECK(row_version>=1)
);

CREATE INDEX ix_so1_catalogs_tenant_active ON public.so1_catalogs(tenant_id,active);
CREATE INDEX ix_so1_entries_catalog_active ON public.so1_catalog_entries(tenant_id,catalog_id,enabled,sort_order);
CREATE INDEX ix_so1_offers_tenant_active ON public.so1_offers(tenant_id,active);
CREATE INDEX ix_so1_prices_resolution ON public.so1_prices(tenant_id,target_type,price_code,currency,active,effective_from,effective_to,precedence);

COMMENT ON TABLE public.atomic_units IS 'SO1 canonical Atomic Unit operational identity adopted in place; taxonomy, offers, prices, inventory and Finance remain distinct authorities.';
COMMENT ON TABLE public.atomic_unit_taxonomy IS 'Legacy many-to-many compatibility bridge between SO1 Atomic Units and PC3 taxonomy nodes.';
COMMENT ON TABLE public.so1_catalogs IS 'SO1 governed discoverability; not taxonomy, inventory or frontend navigation.';
COMMENT ON TABLE public.so1_offers IS 'SO1 presentable composition identity distinct from Atomic Unit and price.';
COMMENT ON TABLE public.so1_prices IS 'SO1 operational commercial prices; never revenue or financial truth.';
