CREATE TABLE public.so2_operational_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    relationship_type_code VARCHAR(120) NOT NULL,
    lifecycle_status VARCHAR(16) NOT NULL,
    source_code VARCHAR(120) NULL,
    purpose VARCHAR(240) NULL,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    organization_unit_id INTEGER NULL,
    location_id BIGINT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NULL,
    row_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_so2_relationships_public_id UNIQUE(public_id),
    CONSTRAINT uq_so2_relationships_tenant_id_id UNIQUE(tenant_id,id),
    CONSTRAINT uq_so2_relationships_party_type UNIQUE(tenant_id,party_id,relationship_type_code),
    CONSTRAINT fk_so2_relationships_tenant FOREIGN KEY(tenant_id) REFERENCES public.tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_so2_relationships_party FOREIGN KEY(tenant_id,party_id) REFERENCES public.parties(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_so2_relationships_organization FOREIGN KEY(tenant_id,organization_unit_id) REFERENCES public.organization_units(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT fk_so2_relationships_location FOREIGN KEY(tenant_id,location_id) REFERENCES public.locations(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_so2_relationships_type CHECK(relationship_type_code=lower(btrim(relationship_type_code)) AND length(relationship_type_code)>0),
    CONSTRAINT ck_so2_relationships_status CHECK(lifecycle_status IN ('prospect','active','inactive','ended')),
    CONSTRAINT ck_so2_relationships_source CHECK(source_code IS NULL OR (source_code=lower(btrim(source_code)) AND length(source_code)>0)),
    CONSTRAINT ck_so2_relationships_preferences CHECK(jsonb_typeof(preferences)='object'),
    CONSTRAINT ck_so2_relationships_period CHECK(effective_to IS NULL OR effective_to>=effective_from),
    CONSTRAINT ck_so2_relationships_version CHECK(row_version>=1)
);
CREATE INDEX ix_so2_relationships_tenant_party ON public.so2_operational_relationships(tenant_id,party_id,lifecycle_status);
CREATE INDEX ix_so2_relationships_tenant_type ON public.so2_operational_relationships(tenant_id,relationship_type_code,lifecycle_status);

CREATE TABLE public.so2_relationship_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    relationship_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL,
    from_status VARCHAR(16) NULL,
    to_status VARCHAR(16) NOT NULL,
    reason_code VARCHAR(120) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_so2_relationship_history_sequence UNIQUE(tenant_id,relationship_id,sequence),
    CONSTRAINT fk_so2_relationship_history_relationship FOREIGN KEY(tenant_id,relationship_id) REFERENCES public.so2_operational_relationships(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_so2_relationship_history_sequence CHECK(sequence>=1),
    CONSTRAINT ck_so2_relationship_history_from CHECK(from_status IS NULL OR from_status IN ('prospect','active','inactive','ended')),
    CONSTRAINT ck_so2_relationship_history_to CHECK(to_status IN ('prospect','active','inactive','ended')),
    CONSTRAINT ck_so2_relationship_history_reason CHECK(reason_code=lower(btrim(reason_code)) AND length(reason_code)>0)
);

CREATE TABLE public.so2_relationship_compatibility_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    relationship_id BIGINT NOT NULL,
    source_authority VARCHAR(120) NOT NULL,
    source_record_id VARCHAR(160) NOT NULL,
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_so2_relationship_compatibility_source UNIQUE(tenant_id,source_authority,source_record_id),
    CONSTRAINT fk_so2_relationship_compatibility_relationship FOREIGN KEY(tenant_id,relationship_id) REFERENCES public.so2_operational_relationships(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT ck_so2_relationship_compatibility_source CHECK(length(btrim(source_authority))>0 AND length(btrim(source_record_id))>0),
    CONSTRAINT ck_so2_relationship_compatibility_evidence CHECK(jsonb_typeof(evidence)='object')
);

CREATE TABLE public.so2_relationship_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_key VARCHAR(160) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    command_type VARCHAR(40) NOT NULL,
    result_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_so2_relationship_commands_key UNIQUE(command_key),
    CONSTRAINT fk_so2_relationship_commands_result FOREIGN KEY(result_id) REFERENCES public.so2_operational_relationships(id) ON DELETE RESTRICT,
    CONSTRAINT ck_so2_relationship_commands_fingerprint CHECK(request_fingerprint~'^[0-9a-f]{64}$'),
    CONSTRAINT ck_so2_relationship_commands_type CHECK(command_type IN ('establish','change_status','update_preferences')),
    CONSTRAINT ck_so2_relationship_commands_result CHECK((result_id IS NULL AND completed_at IS NULL) OR (result_id IS NOT NULL AND completed_at IS NOT NULL))
);

COMMENT ON TABLE public.so2_operational_relationships IS 'SO2 tenant-scoped operational participation around a PC2 Party; never Party identity, authentication role or financial truth.';
COMMENT ON COLUMN public.so2_operational_relationships.preferences IS 'Operational-use metadata only; canonical contact values and consent authority are excluded.';
COMMENT ON TABLE public.so2_relationship_compatibility_mappings IS 'Explicit bridge for legacy customer/vendor references; no bulk rewrite or WND cutover.';
