"""R6 WND production cutover package.

R6.1 authorizes disposable-clone rehearsal only. It does not authorize live
production writes or writer retirement.
"""
from .contracts import (
    CANDIDATE_DATABASE,
    CANONICAL_SOURCE_STAMP,
    DISPOSABLE_DATABASES,
    EXPECTED_COUNTS,
    KITCHEN_BON_PRESERVATION,
    REFERENCE_RELEASE_PRESERVATION,
    REFERENCE_RELEASE_TAG,
    REFERENCE_SOURCE_EVIDENCE_SHA256,
    PRODUCTION_BACKEND_RELEASE_BRANCH,
    PRODUCTION_FRONTEND_RELEASE_BRANCH,
    PRODUCTION_BACKEND_HEAD,
    PRODUCTION_BACKEND_TAG,
    PRODUCTION_BRANCH_ID,
    PRODUCTION_DATABASE,
    PRODUCTION_FRONTEND_HEAD,
    PRODUCTION_TENANT_ID,
    SERVER_BACKUP_FILENAME,
    SERVER_BACKUP_SHA256,
    SERVER_BACKUP_SIZE,
    SOURCE_DATABASE,
    SOURCE_REVISION,
    TARGET_HEAD,
)

__all__ = [name for name in globals() if name.isupper()]
