"""add_tier1_business_tables

Revision ID: fff36dab3483
Revises: 86322f59e0de
Create Date: 2025-12-13 22:21:42.799862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff36dab3483'
down_revision: Union[str, Sequence[str], None] = '86322f59e0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billable_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_billable_unit_sku_per_tenant')
    )
    op.create_index('ix_billable_unit_tenant_active', 'billable_units', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_billable_units_tenant_id'), 'billable_units', ['tenant_id'], unique=False)
    op.create_table('taxonomy_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('semantic_level', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'parent_id', 'name', name='uq_taxonomy_node_name_per_parent')
    )
    op.create_index(op.f('ix_taxonomy_nodes_parent_id'), 'taxonomy_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_taxonomy_nodes_tenant_id'), 'taxonomy_nodes', ['tenant_id'], unique=False)
    op.create_index('ix_taxonomy_tenant_parent', 'taxonomy_nodes', ['tenant_id', 'parent_id'], unique=False)
    op.create_table('billable_unit_taxonomy',
    sa.Column('billable_unit_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billable_unit_id'], ['billable_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('billable_unit_id', 'taxonomy_node_id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('billable_unit_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billable_unit_id'], ['billable_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_item_tenant_branch', 'inventory_items', ['tenant_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_billable_unit_id'), 'inventory_items', ['billable_unit_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_branch_id'), 'inventory_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_tenant_id'), 'inventory_items', ['tenant_id'], unique=False)
    op.create_index('uq_inventory_item_branch_unit', 'inventory_items', ['branch_id', 'billable_unit_id'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('billable_unit_id', sa.Integer(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billable_unit_id'], ['billable_units.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movement_branch_unit_time', 'inventory_movements', ['branch_id', 'billable_unit_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_billable_unit_id'), 'inventory_movements', ['billable_unit_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_branch_id'), 'inventory_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_id'), 'inventory_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_tenant_id'), 'inventory_movements', ['tenant_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_tenant_branch_created', 'sales', ['tenant_id', 'branch_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sales_branch_id'), 'sales', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sales_cashier_id'), 'sales', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_sale_status', 'payments', ['sale_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.create_index(op.f('ix_payments_sale_id'), 'payments', ['sale_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('billable_unit_id', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['billable_unit_id'], ['billable_units.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_item_sale', 'sale_items', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_items_billable_unit_id'), 'sale_items', ['billable_unit_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    #op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_billable_unit_id'), table_name='sale_items')
    op.drop_index('ix_sale_item_sale', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_sale_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index('ix_payment_sale_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_cashier_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_branch_id'), table_name='sales')
    op.drop_index('ix_sale_tenant_branch_created', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_inventory_movements_tenant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_branch_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_billable_unit_id'), table_name='inventory_movements')
    op.drop_index('ix_inventory_movement_branch_unit_time', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('uq_inventory_item_branch_unit', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_tenant_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_branch_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_billable_unit_id'), table_name='inventory_items')
    op.drop_index('ix_inventory_item_tenant_branch', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('billable_unit_taxonomy')
    op.drop_index('ix_taxonomy_tenant_parent', table_name='taxonomy_nodes')
    op.drop_index(op.f('ix_taxonomy_nodes_tenant_id'), table_name='taxonomy_nodes')
    op.drop_index(op.f('ix_taxonomy_nodes_parent_id'), table_name='taxonomy_nodes')
    op.drop_table('taxonomy_nodes')
    op.drop_index(op.f('ix_billable_units_tenant_id'), table_name='billable_units')
    op.drop_index('ix_billable_unit_tenant_active', table_name='billable_units')
    op.drop_table('billable_units')
    # ### end Alembic commands ###
