"""M8.3 is a schema-neutral hardening and recovery-evidence package."""

SCHEMA_NEUTRAL = True
MIGRATION = None
WRITES_DEVELOPMENT_DATABASE = False
USES_DISPOSABLE_DATABASES = True
USES_TEMPORARY_BACKUP = True
FABRICATES_FINANCIAL_HISTORY = False
LIVE_PROVIDER_CALLS = False
REROUTES_LEGACY_WRITERS = False
CUTOVER_AUTHORIZED = False
