"""M8.4 is a schema-neutral pack-conformance and readiness-evidence package."""

SCHEMA_NEUTRAL = True
MIGRATION = None
WRITES_NEW_TABLES = False
CREATES_PACK_FINANCIAL_AUTHORITY = False
DIRECT_FINANCIAL_MUTATION_ALLOWED = False
REROUTES_LEGACY_WRITERS = False
CUTOVER_AUTHORIZED = False
WRITER_RETIREMENT_EXECUTED = False
LIVE_CUTOVER_OWNER = "R6"
