"""M8.5 is release evidence only and creates no persistence authority."""

SCHEMA_NEUTRAL = True
MIGRATION = None
WRITES_NEW_TABLES = False
CREATES_FINANCIAL_AUTHORITY = False
MUTATES_DEVELOPMENT_DATA = False
REROUTES_LEGACY_WRITERS = False
CUTOVER_AUTHORIZED = False
WRITER_RETIREMENT_EXECUTED = False
LIVE_CUTOVER_OWNER = "R6"
